### ISSUE TITLE
Need to be able to use SSH Agent Jenkins Plugin

### ISSUE THREAD

**Issue by Dizdarevic-Glitch** [openshift/jenkins#1004]
Hi,

We need to be able to utilize the Global Git SSH Credentials to retrieve and push release tags over SSH from our Jenkins pipeline.

The way this seems to be typically done is by using the SSH Agent Jenkins plugin.

To accomplish this, we need:
1. Bouncycastle API plugin updated to at least version 2.17, because SSH Agent requires at least that version of Bouncycastle API.

2. SSH Agent (version 1.17? not sure if version will matter) plugin added

3. SSH Credentials plugin updated to at least version 1.17.3
- If this plugin isn't updated, SSH Agent has issues using the provided GIT private SSH key that doesn't utilize a passphrase.

Example of what I'm trying to accomplish:
```
stage ("Git push new tag") {
    steps {
        sshagent (credentials: ['git-secret']) {
            sh 'git tag -a v0.0.2 -m "version 0.0.2"'
            sh 'git push origin --tags'
        }
    }
}
```

for reference, we need it alongside of these: https://github.com/openshift/jenkins/blob/openshift-3.11/2/contrib/openshift/base-plugins.txt

Thanks!

**Comment by cnash6** [comment]
Looks like this has been discussed before in 2018: https://github.com/openshift/jenkins/pull/617

Any chance the discussion on this item has changed?
