### ISSUE TITLE
out of sync docker hub - openshift/jenkins-2-centos7:latest #993

### ISSUE THREAD

**Issue by tbugfinder** [openshift/jenkins#1008]
Hey,

I'd like to reopen #993 as I still think it's not correct.
Unfortunately quay.io does not include any build for 3.x.
There's also issue #1006 which would require an updated build which could then be tagged :latest.

Thanks & Best

**Comment by akram** [comment]
Hi @tbugfinder 

I just commented #993 to explain what we release for 3.11 now.

To sum up:
the most recent jenkins image for 3.11 will always be:
hub.docker.io/openshift/jenkins-2-centos7:v3.11


All 4.x images will be:
https://quay.io/repository/openshift/origin-jenkins?tab=tags

**Comment by tbugfinder** [comment]
Thanks for another clarification.
