### ISSUE TITLE
Defaulting Jenkins GC settings to G1

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins#1011]
openshift/jenkins [defaults Java GC configuration](https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L299) to rely upon the default JDK 8 GC when [CloudBees](https://support.cloudbees.com/hc/en-us/articles/222446987-Prepare-Jenkins-for-Support) and the [Jenkins community](https://jenkins.io/blog/2016/11/21/gc-tuning/) have found that G1, which became the default GC with JDK 9, to be more appropriate.  While the end user has an option of overriding this, this decision should be revisited with potentially new default GC settings.

**Comment by akram** [comment]
Hi @andyfeller 
thank you for reporting this. I had a long look at this, and the article also states that the benefits are important for Jenkins instances having large heaps (>24GB) which is not the most common scenario for us. As we tend to encourage to have one Jenkins per application or domain and reuse agents.

I will close the issue then, but feel free to re-open it if you think it requires a deeper look.
Akram

**Comment by andyfeller** [comment]
> As we tend to encourage to have one Jenkins per application or domain and reuse agents.

I’m not sure that’s historically been a recommendation or expectation around this project though I invite @gabemontero and @bparees to correct me if I’m wrong.  What’s more, that was our initial direction when we adopted openshift/jenkins and found it exponentially increased toil in the form of managing patches, upgrades, and cognitive load of end users.

By organizing Jenkins around our OUs, were able to more effectively enforce our infosec policies around who can do what, provide a centralized place that improves visibility and cognitive load, and reduces maintenance costs.

All that being said, the times are always changing and this will change with the move to JDK 11 or newer not to mention a general action taken by most Java shops due to the impact on GC and pausing.

**Comment by bparees** [comment]
The best defaults are always going to be a struggle for something used in as many different ways as jenkins and in general we've had a hard time getting it right for any java app.

But assuming G1 has no clear drawbacks(I have done zero research on the subject) for most deployments, it seems worth considering using as the default, even if the benefits only apply to a small percentage of deployments.

If nothing else perhaps it's worth a doc note so consumers are aware of what the defaults are that they might want to change.

**Comment by gabemontero** [comment]
Yeah in the past the openshift org collaborated with the middleware folks and open jdk folks on OOTB jvm heap/gc settings, typically following their lead.

With the JDK 11 full support for this image "close" (once the openjdk fixes the TLS bug we found which breaks the login plugin :-) ), it seems appropriate to me that @akram and @siamaksade might have a card in an upcoming sprint to reach out again to middleware/openjdk and start exploring these type questions (if they do not have such activity planned already).

I would not be inclined to have such changes here done in a vacuum, without collaborating with those folks.

And a +1 on the doc hit.  Minimally noting in this repo's readme the env vars we have in this space, and links to the default settings in the run script.

**Comment by akram** [comment]
/reopen

Let's keep this one open then to track this documentation update and deeper investigations on it.
For sure, there are different scenario and usages, and not setting it to default would not prevent from changing it. In terms of performance and tuning, there is  definitely no "one size fit all" stratergy.
