### ISSUE TITLE
java.io.IOException: well-known file /tmp/.java_pid356 is not secure: file's group should be the current group (which is 0) but the group is 1000270000

### ISSUE THREAD

**Issue by jelmew** [openshift/jenkins#1018]
Hi all,

While trying to run maven test ona maven slave for jenkins in openshift, the following error happens when running the test:

```
java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7193666c
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.io.IOException: well-known file /tmp/.java_pid356 is not secure: file's group should be the current group (which is 0) but the group is 1000270000
```

I could not find any reference on how this might be solved online. The best option would probably be to force ByteBudy to ignore the group permission, but how is this done?

**Comment by akram** [comment]
Hi @jelmew ,
I have raised the following issue with them.
If it is not blocking your pipeline, I think you can silently ignore this error until we get it fixed.

Thanks for reporting it

**Comment by raphw** [comment]
This is [a JVM restriction](http://hg.openjdk.java.net/jdk/jdk/file/932418820c80/src/jdk.attach/linux/native/libattach/VirtualMachineImpl.c#l167) to avoid that a process attaches to another user's process. In case of running in a container, this would not be necessary as sandboxing already is achieved but I do not think that it can be avoided in HotSpot.

**Comment by akram** [comment]
thank you @raphw for explicating and explaining this. 
@jelmew , can you give more context and what are the consequences of this error?
I think you have probably extended the images to add things using JNI ? or you are using native calls from the pipeline?

**Comment by raphw** [comment]
It's probably triggered by a library such as Mockito which uses self-attachment to get access to the instrumentation API. I'm a bit confused why the file is not owned by the user of the process. The process is normally creating this file.

**Comment by jelmew** [comment]
> It's probably triggered by a library such as Mockito which uses self-attachment to get access to the instrumentation API. I'm a bit confused why the file is not owned by the user of the process. The process is normally creating this file.

Dingding,  it is mockito/junit5 thingy. I am also confused why this happens. The command run is simply mvn clean test, so you would say it would own this.

**Comment by raphw** [comment]
Mockito uses Byte Buddy which spawns a process if you use the inline mock maker. This is to attach an agent to itself which cannit happen from equal l process ids. I do however wonder why this new process would be owned by a different user.

**Comment by jelmew** [comment]
Do you want a simple reproducer to test this?

**Comment by raphw** [comment]
If you can create one, I'd certainly have a look!

**Comment by laetho** [comment]
We have ran into a similar issue with Kotlin and Mockk. The Pod specification we use gets the openshfit "restricted" SCC "policy".

The uid and gid ranges are from you namespace (oc describe namespace <yourns>). 

For us the id of the user can look like this:
```
bash-4.2$ id
uid=1000610000(default) gid=0(root) groups=0(root),1000610000
```

Everything works as expected and files are created with the permissions according to policy:
```
1000610000@javaci-45-7cq22-1vtrw:~$ id
uid=1000610000(1000610000) gid=0(root) groups=0(root),1000610000
1000610000@javaci-45-7cq22-1vtrw:~$ touch FILE
1000610000@javaci-45-7cq22-1vtrw:~$ ls -lh FILE
-rw-r--r--. 1 1000610000 1000610000 0 Mar 12 14:11 FILE
1000610000@javaci-45-7cq22-1vtrw:~$ 
```
But somehow it gets confused and thinks the current group should be 0 when checking the permissions for the /tmp/.tmpPID file.

**Comment by akram** [comment]
@laetho and @raphw  to my understanding the primary group of the user is 0 here and 1000610000 is only a secondary group. 
On my jenkins pods, if I rsh and do touch /tmp/file , then, the owner group is 0 not 1000610000

```
oc rsh jenkins-1-txw9t
sh-4.2$ id
uid=1000620000(1000620000) gid=0(root) groups=0(root),1000620000
sh-4.2$ touch /tmp/file
sh-4.2$ ls -lan /tmp/file
-rw-r--r--. 1 1000620000 0 0 Mar 12 21:51 /tmp/file
sh-4.2$
```

**Comment by laetho** [comment]
@akram Actually, that is absolutely correct. The primary group is 0, I just don't understand the mechanics of it using the secondary group or "supplementalGroup" in openshift context when creating files inside the container. I might be able to "trick" it with changing the primary group in /etc/passwd for the dynamic user.

**Comment by laetho** [comment]
@akram Can you check what scc policy you pod object got after admission controllers and scheduler modified it? It should be in the annotation section of the pod specification.

**Comment by laetho** [comment]
I have worked around our issue by adding the serviceaccount we used in the namespace to the anyuid scc:

```
oc prjoect YOUR-NAMESPACE
oc adm policy add-scc-to-user anyuid -z YOUR-SERVICEACCOUNT 
```

Then modified the Pod specification used by the Jenkins kubernetes plugin:
```
...
annotations:
  openshift.io/scc: anyuid
...
spec:
  securityContext:
    runAsUser: YOUR_PREFERED_PID
    runAsGroup: 0
...
```

I'll log an issue with RedHat regarding the restricted SCC which really should have worked in my opinion. Atleast to figure out why the supplementalGroup becomes the primary group.

**Comment by lbourgeois76** [comment]
there is any news about this subject ?

**Comment by isantiagom** [comment]
If you cannot apply the workaround of changing the policy is there any other solution?

**Comment by adenhartog** [comment]
This issue only occurs when building on a Jenkins agent, the Jenkins master can build these projects just fine.

We fixed this issue by changing the Jenkins working dir in the Pod template (Pod Templates -> <specific template> -> Containers -> Container Template -> Working directory) from /tmp to /var/tmp. 

I suspect that the cause has to do with Jenkins changing the owning group of the Jenkins working dir to one of those very high OpenShift numbers we see earlier in this thread, which changes the ownership of files created withinin this directory. Combined with the fact that OpenShift Jenkins uses /tmp as working directory for agents by default in the pod templates. Other processes in the Jenkins agent that use /tmp will be affected by Jenkins changing the ownership. It would help tremendously if the Jenkins that comes with Openshift out of the box, uses /var/tmp (or anything other than /tmp) as the working directory by default for pod templates. The problem is not seen on the Jenkins master because it does not use /tmp for working directory.

**Comment by adenhartog** [comment]
I am not familiar with this code base but I do see a reference to the workingDir here: https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh

Maybe that needs to be changed?

**Comment by Lonor** [comment]
Same error occurred on JDK 8 agent, but not on JDK 11.
