### ISSUE TITLE
OpenShift 3.11 Jenkins maven agent with Maven 3.6.x

### ISSUE THREAD

**Issue by shnplr** [openshift/jenkins#1040]
Will there be a Jenkins maven slave image for Maven 3.6.x?

The S2I java 8 image appears to support Apache Maven 3.6.1 (Red Hat 3.6.1-6.3).

**Comment by waveywaves** [comment]
Currently we have no plans of doing so, but you can go ahead and create your own agent based off of the `slave-base` scaffold present in the root of this repo. https://github.com/openshift/jenkins/tree/master/slave-base
