### ISSUE TITLE
go-init permission denied when running with podman

### ISSUE THREAD

**Issue by AbdulR3hman** [openshift/jenkins#1058]
Hi,

I'm having a problem building the go-init slave-base. The error is shown below;

podman build -t go-init-example .
STEP 1: FROM openshift/origin-release:golang-1.12 AS builder
STEP 2: COPY ./ /go/src/go-init
c9732b81e04f593170977d4930ca27fc709dc839db835517aab385fa87947a66
STEP 3: RUN go install go-init
can't load package: package go-init: open /go/src/go-init: permission denied
Error: error building at STEP "RUN go install go-init": error while running runtime: exit status 1

I have not edit the docker file, and I am running from master. ( I also tried the release-4.7 branch, same issue)

I'm running it on Rhel 7 with podman: 

podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

Is there something I might be missing here? Thanks in advance.

**Comment by akram** [comment]
Hi @AbdulR3hman ,

are you running the image form master?
if yes, I suspect that a recent security fix that we added may be not working with podman on rhel7.
Can you confirm ?
