### ISSUE TITLE
release 4.4 - git plugin - java.lang.NoSuchMethodError: 'org.eclipse.jgit.lib.Ref org.eclipse.jgit.lib.Repository.getRef' 

### ISSUE THREAD

**Issue by bszeti** [openshift/jenkins#1059]
In release 4.4. the installed Git plugins has a problem that causes an exception with pipelines from SCM. Problem is probably caused by incompatibility between [installed plugins](https://github.com/openshift/jenkins/blob/a08ad146ce5ccd847e534f91e1b24a3134d2dac6/2/contrib/openshift/base-plugins.txt):
- git-client:3.0.0
- git:3.9.3
See related ticket: https://issues.jenkins-ci.org/browse/JENKINS-53004?focusedCommentId=389294&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-389294

Effected container image:
https://catalog.redhat.com/software/containers/detail/5cdd918ad70cc57c44b2d279?tag=v4.4.0-202005121717&architecture=amd64

The issue is probably fixed on master, so it will be fixed in later releases, but the current 4.4 (latest) release is effected.

**Comment by akram** [comment]
Hi @bszeti , thanks for reporting this, we will have a look at it
