### ISSUE TITLE
Cannot delete Jenkins job (permission denied)

### ISSUE THREAD

**Issue by dokaspar** [openshift/jenkins#1060]
Hi,

In our Openshift environment, we run a Jenkins that I have built with a three-liner Dockerfile like this:
```
FROM registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.11.154-1
USER root
RUN yum install -y -q <somemorepkgs> && yum clean all && rm -rf /var/cache/yum

# USER ?
```
I may have made a mistake in not setting another USER after running as root...
So my first question is:
- **Which user should be set again after `USER root`?**

I assume that this is the reason that Jenkins now is unable to remove some directories. Everything in my persistent volume /var/lib/jenkins is owned by `default:2001` (and I have no clue what group 2001 is!) but some directory that was seemingly created by a plugin, is owned by `root:2001` and I have found no way of removing this directory:
```
drwxr-sr-x. 3 root 2001 20 Apr  6 14:03 workspace_ws-cleanup_1586181715781
```
So my second question is:
- **How is it possible that a plugin can write directories as root and how can I delete them again?**

Regards,
Dominik

**Comment by akram** [comment]
Hi @dokaspar 

indeed, you should not hardcode `USER` , as this is something we consider that it can bring security issues, and especially if you set root.

The images that we provide are intended to be used on OpenShift, and openshift for security reason, by default, runs any image with an arbitrary random user higher than 100000000 ; this user is kept accross restarts so files continue to belong to the same user.

OpenShift 4.2+ also relies on cri-o which is in charge of creating this arbitrary user and to inject it in /etc/passwd of the container. That allows the user running the container to write directories and to delete them again.
