### ISSUE TITLE
openshift/jenkins-2-centos7 image throwing javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by mesadhan** [openshift/jenkins#1062]
I'm using `openshift/jenkins-2-centos7` docker image in the on-premise `OKD Cluster v3.11`. When deploying that everything working perfectly but it throwing below expectations. 

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching ip address found.
```

So I can't connect Jenkins server for plugin update related issue. Most importantly I cannot clone git repository.

**Comment by akram** [comment]
Hi @mesadhan ,

can you give more context about the exception ?
