### ISSUE TITLE
OpenShift Jenkinsfile access git branch name and other environment variables

### ISSUE THREAD

**Issue by khteh** [openshift/jenkins#1088]
How to retrieve git branch name and other standard/built-in environment variables in BuildConfig / Jenkinsfile? I have had the necessary git plugins installed. However, everything is null / empty when referenced in Jenkinsfile / BuildConfig template

env.GIT_BRANCH or GIT_BRANCH is empty.

**Comment by akram** [comment]
Hi @khteh 

BuildConfig is only a configuration object and not a runtime object, it is used to trigger a build. Once the build is created (oc start-build) it is materialiazed as a pod and it has SOURCE_REPOSITORY, SOURCE_URI, etc... where we can get what you need.

Jenkinsfile describre a pipeline which is a wider context, and you can use any classic jenkins dsl based object to get  the git context you need. The branch name is usually env.BANCH_NAME in a Jenkins pipeline

**Comment by khteh** [comment]
@akram I `echo "Branch: ${env.BRANCH_NAME}"` in Jenkinsfile and the value is NULL!

/open
