### ISSUE TITLE
Dockerfile not build inside 2 folder

### ISSUE THREAD

**Issue by shakenfr** [openshift/jenkins#1105]
hello, 
I take this dockerfile to add addtional package that miss for me (like ksh package). 
When I try a docker build .
I have an error when It tries to install yum packages

could not resolve host : base-4-6.ocp.svc; unknow  error

How can I correct this ?
best
bruno

**Comment by akram** [comment]
you are probably using the rhel7 dockerfile which is supposed to run on a rhel7 host.
Use the Dockerfile.localdev instead that uses a CentOS based image and that can be built on any platform.
