### ISSUE TITLE
openshift3/jenkins-2-rhel7:v.3.11 add option to skip TLS verification when install plugins

### ISSUE THREAD

**Issue by chan43999** [openshift/jenkins#1144]
In the `jenkins/2/contrib/jenkins/install-plugins.sh`. [line 229](https://github.com/openshift/jenkins/blob/openshift-3.11/2/contrib/jenkins/install-plugins.sh#L229). When trying to `curl` to download plugins. Can we add some code to read the system environment like 'SKIP_SSL_VERIFY' and add the `--insecure` flag to the`curl` command

**Comment by akram** [comment]
Hi @chan43999 

this is available in more recent images by using the environment variable JENKINS_UC_INSECURE

https://github.com/openshift/jenkins/blob/release-4.6/2/contrib/jenkins/install-plugins.sh#L229

**Comment by chan43999** [comment]
@akram We are using Openshift 3.11 and this image [openshift3/jenkins-2-rhel7](https://catalog.redhat.com/software/containers/openshift3/jenkins-2-rhel7/581d2f4500e5d05639b6517b?tag=v3.11.248-4). Im not sure which version of image contains the changes above because the image version is still 3.11 so I understand that it still use the branch `openshift-3.11`

**Comment by akram** [comment]
it is available in 4.x images (starting from 4.2 iirc).
You can reuse the same approach that the one  in the script or see if migrating to 4.x would be better for you.

**Comment by chan43999** [comment]
Any chance to add this to version 3.11.x images in the future as well? So i don't have to customize the script by my self

**Comment by akram** [comment]
@chan43999 , we are only maintaining the 3.11 version. Such a feature being not vital nor a security issue; we don't plan to backport it
