### ISSUE TITLE
Bump jenkins version as 2.235 is 9 months old

### ISSUE THREAD

**Issue by cmoulliard** [openshift/jenkins#1206]
## Proposition

Bump jenkins to a more recent version as the one packaged which is `2.235` is [9 months old](https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.235).

See package included within the image: https://catalog.redhat.com/software/containers/openshift3/jenkins-2-rhel7/581d2f4500e5d05639b6517b?container-tabs=packages -> `jenkins-2.235.5.1600415953-1.el7.noarch`

Latest release of jenkins is : https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.277

**Comment by akram** [comment]
Hi @cmoulliard 
we are in the process of upgrading to 2.263.3 LTS.

**Comment by cmoulliard** [comment]
Super :-) When is it planned to release a new image as this one still uses 2.235 - https://catalog.redhat.com/software/containers/openshift3/jenkins-2-rhel7/ ? @akram

**Comment by akram** [comment]
we are now on 2.277.x

/close
