### ISSUE TITLE
Bug: Jenkins will failed to notify stash/bitbucket when there is multiple routes in namespace

### ISSUE THREAD

**Issue by tobyqin** [openshift/jenkins#1241]
Hi team, we met an issue that Jenkins will failed to notify stash with below error:

```
[Pipeline] step
Cannot notify Stash! (Jenkins Root URL not configured)
[Pipeline] sh
```
As we found the `JENKINS_URL` was not set correctly in `/var/lib/jenkins.model.JenkinsLocationConfiguration.xml` file.

After digging into log and source code, we found a bug in bellow file:

https://github.com/openshift/jenkins/blob/84056bf7c0fc2b42b118761e610953e9b2fc89c5/2/contrib/s2i/run#L19

```
--> JENKINS_URL="$JENKINS_SCHEME$(oc get routes -o json | jq -c -r '.items[0].spec | select (.to.name == env.JENKINS_SERVICE_NAME ) | .host ')"
```
It was trying to get `JENKINS_URL` from 1st route in namespace, however, we have multiple routes in namespace currently, jenkins route is not the first one.

Could you please confirm the issue and get it fixed?

**Comment by akram** [comment]
Hi @tobyqin ,

to my understanding we are getting the first route in the current namespaces matching also the JENKINS_SERVICE_NAME.
So, indeed, if you are exposing the service using 2 different routes the JENKINS_URL will be set to the first one.

There cannot be a silver bullet for that. If you really need 2 or n routes and pass this to your notification system, you will have to have multiple env vars matching your needs.
If it is only the order, then, you can safely delete the routes and create them in the right order, or adapt the script to make it match the route you want.

Greetings
Akram

**Comment by tobyqin** [comment]
> to my understanding we are getting the first route in the current namespaces matching also the JENKINS_SERVICE_NAME.

This is the expectation but not implementation, the implementation is:

```
get all routes => use first route spec => select name if equals JENKINS_SERVICE_NAME => return host
```

expectation should be:

```
get route with jenkins label => use its spec => select name if equals JENKINS_SERVICE_NAME => return host
```

The bug we met is like this:

1. I have jenkins route in namespace, named as `jenkins-xxx-route`
2. When I deployed another app with route as `abc-route`, jenkins will fail to notify stash, as `abc-route` is ordered before `jenkins`
3. When I removed this `abc-route` and redeploy, jenkins will be able to notify stash
4. When I deployed another app with route as `xyz-route`, jenkins is working correctly, as `xyz-route is ordered after `jenkins`

Hope I had explained this issue clearly.

**Comment by akram** [comment]
I have missed that part:
```
get route **with jenkins label** 
```

**Comment by akram** [comment]
Filtering on the jenkins label or not will not solve the issue, as multiple routes can have the jenkins label, it will just move the problem to take the first route with jenkins label and point to service JENKINS_SERVICE_NAME.
As a workaround, I can only suggest you to rename your route so the script will pick the one matching your needs. Or you can propose another solution with a PR.

**Comment by tobyqin** [comment]
I will try to create a PR for this issue, any guide should I follow?

**Comment by aiman-alsari** [comment]
Have pushed a fix for this
