### ISSUE TITLE
Ideas for getting JSON or other rich logging format for better APM integration

### ISSUE THREAD

**Issue by erikhjensen** [openshift/jenkins#1243]
We're currently using Jenkins Masters in OpenShift and it seems to use the java.util.logging simple formatter.  I can teach our APM likely how to ingest the single line log files properly so that the severity maps correctly but the APM team's recommendation is to adjust the source appender instead.

Is it possible for us to adjust the Jenkins container to use log4j or another framework which would allow this JSON format so that the fields are more easily consumable by the log processing tool we use?

for the most part we use the jenkins persistent catalogue item in OpenShift.

**Comment by akram** [comment]
Hi @erikhjensen  
to do that, you can indeed use a customer formatter which is compatible with java.util.logging API (JUL) which is the one that we use and configure for our Jenkins image.

You can use an already existant jar (GELF Formatter for example) or develop your own and make sure it is available somewhere in the classpath so the JVM finds it; then you have to reference it and configure it in /var/lib/jenkins/logging.properties 

HTH

**Comment by erikhjensen** [comment]
Thanks very much, I had a look for *gelf*.jar and it doesn't look like that's in our file system.  Are you specifically referring to a .jar that's part of Jenkins on OpenShift or, were you referring to a .jar available in industry?

Erik
