### ISSUE TITLE
Jenkins service account is not propagated to slaves

### ISSUE THREAD

**Issue by tnozicka** [openshift/jenkins#128]
Jenkins slaves are missing service account **jenkins** and have only the default one. They should have the same one as master.

My current workaround is:
```groovy
#!/usr/bin/groovy
def k8s_token = '<unknown>'

node ('master') {
    k8s_token = readFile '/var/run/secrets/kubernetes.io/serviceaccount/token'
}

node ('nodejs') {
    // use ${k8s_token}
}
```

I would like to get rid of it.

**Comment by bparees** [comment]
the k8s plugin claims to support setting a service account in the pod template definition for the node:
https://github.com/jenkinsci/kubernetes-plugin/commit/49cd23fd47e66d79744d5fa6a95767ee33a7d436#diff-7ce44bbe5d164ad0631710f06a682472

but i'm not seeing the config field in the jenkins configuration page.  will investigate further.

**Comment by bparees** [comment]
@iocanel you added the service account config support to the k8s plugin, are you aware of any issues with it not showing up on the jenkins config page?

**Comment by bparees** [comment]
looks like we need a new release of the plugin to get the service account feature, i've requested one:
https://issues.jenkins-ci.org/browse/JENKINS-36891
