### ISSUE TITLE
Update jenkins-ephemeral 

### ISSUE THREAD

**Issue by Dennis-kw-yiu** [openshift/jenkins#1284]
Hi all,

I am newbie to openshift when I build new app from the jenkins-ephemeral using the command "oc new-app jenkins-ephemeral -p MEMORY_LIMIT=2048Mi" , I found that some of the script in my jenkins file not works. The root cause seems due to the version of the Jenkins is not up-to-date. Is there any recommended way to update the Jenkins that built from the template?

Environment
Openshift 4.x

Thank you.

**Comment by akram** [comment]
Hi @Dennis-kw-yiu ,

can you share any logs?
the current version of Jenkins that we are using in our images are based on 2.277.x and new ones are coming with the latest LTS .

**Comment by Dennis-kw-yiu** [comment]
Hi @akram 

However, when I check the version from the jenkins, it is 2.204.2 and found the version 2.289.1 is available

![image](https://user-images.githubusercontent.com/44917409/122452001-58d3e000-cfdb-11eb-9669-aa8aba09f167.png)
![image](https://user-images.githubusercontent.com/44917409/122452025-612c1b00-cfdb-11eb-8a1e-77f5c7c4502b.png)

**Comment by akram** [comment]
Since this issue, earlier version of the Jenkins image has been released. 
If you need to build your own image, please consider having a look at the provided 2/Dockerfile and specifgy an earlier version.

/close
