### ISSUE TITLE
Git is not working properly on slaves

### ISSUE THREAD

**Issue by tnozicka** [openshift/jenkins#130]
```bash
docker run -it --rm openshift/jenkins-slave-nodejs-centos7 bash
$ git clone https://github.com/tnozicka/nodejs-ex.git /home/jenkins/nodejs-ex
```
ends up with error:
```
Cloning into '/home/jenkins/nodejs-ex'...
remote: Counting objects: 393, done.
remote: Total 393 (delta 0), reused 0 (delta 0), pack-reused 393
Receiving objects: 100% (393/393), 119.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (161/161), done.
fatal: unable to look up current user in the passwd file: no such user
Unexpected end of command stream
```

Same for maven one:
```bash
docker run -it --rm openshift/jenkins-slave-maven-centos7 bash
$ git clone https://github.com/tnozicka/nodejs-ex.git /home/jenkins/nodejs-ex
```
```
Cloning into '/home/jenkins/nodejs-ex'...
remote: Counting objects: 393, done.
remote: Total 393 (delta 0), reused 0 (delta 0), pack-reused 393
Receiving objects: 100% (393/393), 119.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (161/161), done.
fatal: unable to look up current user in the passwd file: no such user
bash-4.2$ Unexpected end of command stream
```

Surprisingly, this is not a problem when running Jenkins on `oc cluster up`. When using ADB/CDK all attempts to checkout repositories on slaves fail with these errors.

(There is probably a different policy to get UID from or something like that.)

I am not sure about the proper solution here, but we had a hack in our images before summit to fix it: https://github.com/tnozicka/dockerfiles/blob/master/openshift-nodejs-builder/Dockerfile#L3

Running the commands like 
```bash
GIT_COMMITTER_NAME='<unknown>' GIT_COMMITTER_EMAIL='<unknown>' git clone https://github.com/tnozicka/nodejs-ex.git /home/jenkins/nodejs-ex
```
helps.

@rupalibehera @bparees

**Comment by bparees** [comment]
The image isn't intended to be run that way, the problem is this:
```
$ docker run -it --rm openshift/jenkins-slave-nodejs-centos7 bash
bash-4.2$ whoami
whoami: cannot find name for user ID 1001
```

the slave startup script that is invoked when you use this image as a proper slave uses nss wrapper to setup a fake passwd file that ensures the uid can be resolved.

if you want to use this image manually, you need to do the same steps:
```
bash-4.2$ USER_ID=$(id -u)
bash-4.2$ GROUP_ID=$(id -g)
bash-4.2$  NSS_WRAPPER_PASSWD=/tmp/nss_passwd
bash-4.2$     NSS_WRAPPER_GROUP=/etc/group
bash-4.2$ 
bash-4.2$     cat /etc/passwd | sed -e 's/^default:/builder:/' > $NSS_WRAPPER_PASSWD
bash-4.2$ 
bash-4.2$     echo "default:x:${USER_ID}:${GROUP_ID}:Default Application User:${HOME}:/sbin/nologin" >> $NSS_WRAPPER_PASSWD
bash-4.2$ 
bash-4.2$     export NSS_WRAPPER_PASSWD
bash-4.2$     export NSS_WRAPPER_GROUP
bash-4.2$     export LD_PRELOAD=libnss_wrapper.so
```

which results in:
```
bash-4.2$ whoami
default
```

**Comment by tnozicka** [comment]
@bparees This was just an example, but it happens to real slaves as well. The error is exactly the same. It only manifests in ADB because of the admission policy.

> if you want to use this image manually, you need to do the same steps:

Actually [the script](https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/generate_container_user) was called. I did not change the the entrypoint at all, I changed only command. And entrypoint [sources](https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L7) this nss wrapping script. 

The problem is the **[condition](https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/generate_container_user#L5)**. You are refusing to generate the entry for id=1001 but the entry is not there! 

That's most probably why it's not working in ADB because it allows you to run it as the default user 1001 as specified in your [Dockerfile](https://github.com/openshift/jenkins/blob/master/slave-nodejs/Dockerfile#L25). There is no entry in /etc/passwd for user 1001 and you are refusing to generate it.

**Comment by bparees** [comment]
@tnozicka yeah normally our base images define uid 1001 as a real use, but that wasn't the case for the slave images.  i'll remove the conditional.
