### ISSUE TITLE
Jenkins pods termination if DNS pod is restarting 

### ISSUE THREAD

**Issue by yanivpaz** [openshift/jenkins#1309]
I suggest making the code below more resilient :
https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L121

so when  DNS is not responding (because of DNS pod restart),
the pod will not be terminated as seen below :

Downloading <Jenkins host>:18080/jnlpJars/remoting.jar ...
+ curl -sS <Jenkins host>:18080/jnlpJars/remoting.jar -o /home/jenkins/remoting.jar
curl: (6) Could not resolve host: <Jenkins host>
Terminated Kubernetes instance for agent ....

I want to open PR to retry the curl commands 5 times.
please let me know what you think

**Comment by akram** [comment]
Hi @yanivpaz ,
DNS pod restart while Jenkins agent startup is supposedly, a very rare case to happen. Can you describe the scenario where this is happening? is that specific to a Jenkins use case or a buggy DNS pod restarting too often?

**Comment by yanivpaz** [comment]
hi @akram  is a buggy DNS pod that sometimes restarts. 
do you see issue to add  retry like described here: https://stackoverflow.com/questions/42873285/curl-retry-mechanism

**Comment by akram** [comment]
@yanivpaz  You can submit a PR then. That may be useful to community indeed.

**Comment by yanivpaz** [comment]
Yes, I am testing it.
 which minimum curl version do you think that we need to rely on?

# will run 6 iterations ( after 1,2,4,8,16,32,64 seconds) 
curl --connect-timeout 5 \
    --retry-connrefused  --max-time 10 \
    --retry 6 \
    --retry-delay 0 \
    --retry-max-time 40 \
    'http://localhost'

**Comment by akram** [comment]
@yanivpaz 5 retries would be sufficient because failing after too long may have other impacts.
