### ISSUE TITLE
Update jenkins in the branch openshift-3.11 for latest security bugfixes.

### ISSUE THREAD

**Issue by lslebodn** [openshift/jenkins#1311]
The branch openshift-3.11 contains LTS version of jenkis with known CVEs
jenkins-2.289.1  https://github.com/openshift/jenkins/blob/10eb612c7632d519de712ca76ac63167574dd1ed/2/Dockerfile#L41

Upstream report for CVE
https://www.jenkins.io/security/advisory/2021-06-30/#SECURITY-2278

We use downstream version of s2i image as part of dogfooding in RH.
We would like to be compliant with all necessary security requirements and still use our own products.

An upgrade from jenkins-2.289.1 to at least jenkins-2.289.2 should not be a huge change 
Or maybe even into 2.289.3
https://www.jenkins.io/changelog-stable/

Let us know whether you need also downstream BZ for that or what are your plans with upgrade.

**Comment by akram** [comment]
Fixed by https://github.com/openshift/jenkins/pull/1317

/close

**Comment by akram** [comment]
/reopen
I didn't notice that this was for 3.11
