### ISSUE TITLE
SElinux and git-client

### ISSUE THREAD

**Issue by blazmanx34** [openshift/jenkins#1323]
Hello,
since we have upgraded our Jenkins to the last version : v3.11.521, we are not able to pull source code in our pipelines.

This message appears in the logs for each scm checkout : 

```
The recommended git tool is: NONE
using credential builder-image-cicd-git-sshkey-gituser
Cloning the remote Git repository
Cloning repository git@git.mycompany.fr:project/builder-image/builder-image-cicd.git
 > git init /var/lib/jenkins/jobs/builder-image-cicd/jobs/builder-image-cicd-global-configure-pipeline/workspace # timeout=10
Fetching upstream changes from git@git.mycompany.fr:project/builder-image/builder-image-cicd.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials builder-image-cicd-git-sshkey-gituser
[INFO] Currently running in a labeled security context
 > git /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/builder-image-cicd/jobs/builder-image-cicd-global-configure-pipeline/workspace@tmp/jenkins-gitclient-ssh11251408264134958478.key
[WARNING] Failed (1) performing chcon helper command for SELinux: git /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/builder-image-cicd/jobs/builder-image-cicd-global-configure-pipeline/workspace@tmp/jenkins-gitclient-ssh11251408264134958478.key:
=== STDERR:
/usr/bin/chcon: failed to change context of ‘/var/lib/jenkins/jobs/builder-image-cicd/jobs/builder-image-cicd-global-configure-pipeline/workspace@tmp/jenkins-gitclient-ssh11251408264134958478.key’ to ‘system_u:object_r:ssh_home_t:s0’: Operation not supported

====
IMPACT: if SELinux is enabled, access to temporary key file may be denied for git+ssh below
 > git fetch --tags --progress git@git.mycompany.fr:project/builder-image/builder-image-cicd.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@git.mycompany.fr:project/builder-image/builder-image-cicd.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse origin/develop^{commit} # timeout=10
Checking out Revision 221de630ddbc0b68dc617286965c9239fa579823 (origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 221de630ddbc0b68dc617286965c9239fa579823 # timeout=10
Commit message: "xxxxxx"
```

It seems the problem is linked to SELinux.
With the previous version we used (v3.11.346), there were no problem.

Have you got an idea for a solution to solve this problem ?

In advance, thanks for your answer.

**Comment by akram** [comment]
Hi @blazmanx34,

can you give a bit more of a context? How are you using `git` here? Is it a direct call to the git binary from an `sh` directive in pipeline or are you using the git plugins one?
Did you perform a custom git install? is it in an agent? are you using a custom version of the ssh plugin?

Greetings
Akram

**Comment by akram** [comment]
@blazmanx34 can you please have a look at this: https://issues.jenkins.io/browse/JENKINS-64913 ?
it seems to be your issue and a workaround is proposed. The issue you are seeing could be related to the introduction of a git+ssh which is SELinux aware. I don't know if it is the case after v3.11.521

**Comment by blazmanx34** [comment]
Thanks @akram for your answer.

We use the docker image of jenkins as it provided by RedHat. We have perform no custom git install.
The error appears on the jenkins master : https://catalog.redhat.com/software/containers/openshift3/jenkins-2-rhel7/581d2f4500e5d05639b6517b?container-tabs=overview
I can't use an agent for instance.

We use declarative pipelines.
The error appear in the "Declarative: Checkout SCM" stage and in our own "checkout" stage.

We use this method in our own "checkout" stage, to checkout source code :
```
// Récupération des sources à la référence demandée
    checkout([$class                         : 'GitSCM',
            branches                         : ....,
            doGenerateSubmoduleConfigurations: .....,
            extensions                       : ......,
            userRemoteConfigs                : ......])

```

**Comment by blazmanx34** [comment]
@akram I have already read this issue.
It seems indeed that my problem seems to be linked to this issue.
I confess that that I don't understand how can I make a workaround...

`A short-term workaround at this point was to save into Jenkins Credentials a copy of the key without a passphrase` ?
We have no passphrase in our credential.

**Comment by blazmanx34** [comment]
@akram I have installed libselinux-utils in the jenkins image container and SELINUX is disabled

```
sh-4.2$ setenforce 0
setenforce: SELinux is disabled
```

However, the git client plugin behaves as if the SELinux Enforced mode is enable because :
* `/usr/bin/chcon` is executable
* `/proc/self/attr/current` contains ":"
* `/sys/fs/selinux` directory exists
* `/sys/fs/selinux/enforce` doesn't exist

(https://github.com/jenkinsci/git-client-plugin/blob/14c222da49aae7265a74d5d61ad6de2bc356165e/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L2118)

**Comment by blazmanx34** [comment]
@akram After several unsuccessful attempts to modify the image, I am at the same state.
For you, what is a possible workaround ?

**Comment by blazmanx34** [comment]
For information, there is no problem since version v3.11.570

**Comment by akram** [comment]
@blazmanx34 thank you for the feedback

/close
