### ISSUE TITLE
Update jenkins to the latest LTS version

### ISSUE THREAD

**Issue by lslebodn** [openshift/jenkins#1330]
The upstream jenkins page mentions 2.303.2 as the latest LTS version.
https://www.jenkins.io/changelog-stable/

And it was released almost a month ago (2021-10-06)
https://www.jenkins.io/changelog-stable/#v2.303.2

It would be good to upgrade to latest LTS version with all CVE bugfixes at least in master branch.
Upgrade in the **release-4.9** branch would be appreciated as well.

**Comment by adambkaplan** [comment]
The Jenkins image has now been upgraded to v2.303.3, which includes additional security fixes.
