### ISSUE TITLE
Support for websocket connection

### ISSUE THREAD

**Issue by jemerald** [openshift/jenkins#1343]
See https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc

Around Jan 2020 Jenkins has added support for WebSocket connection from inbound agents.

This greatly simplifies the setup of Jenkins on OpenShift when slave pods needs to be spawn up in different namespace or even different cluster.

Without this, the Jenkins master deployment would require nodePort to be configured so that the slaves can communicate with the master using Jenkins tunnel.

[This change in Kubernetes plugin](https://github.com/jenkinsci/kubernetes-plugin/pull/661/files#diff-07d3a3100d41642c232eaf8786fc1e3f480e581662df30d0ec568bdfd7877a7dR349-R351) added the "WebSocket" option
![image](https://user-images.githubusercontent.com/9168432/141921646-cff684f6-15a6-46b7-8da5-165d2388c111.png)
and sets the `JENKINS_WEB_SOCKET` environment variable when the cluster is configured with it. However the slaves provided by OpenShift does not honor this.

Please consider adding the following code to `slave-base/contrib/bin/run-jnlp-client` to support websocket connection:

```sh
  if [[ "$@" != *"-webSocket"* ]]; then
    if [ "$JENKINS_WEB_SOCKET" = true ]; then
      PARAMS="$PARAMS -webSocket"
    fi
  fi
```

**Comment by akram** [comment]
Fixed by #1312
/close
