### ISSUE TITLE
Does Jenkins / Jenkins Slave need the sys_chroot capability to run on Openshift

### ISSUE THREAD

**Issue by samkhamk** [openshift/jenkins#1381]
Hello Team,

We wants to know Does Jenkins / Jenkins Slave need the sys_chroot capability to run on Openshift ? if yes why and if no how we can use any opensource Jenkins image and deploy  it on Openshift as container without sys_chroot capability,

Does the official redhat Jenkins image works without sys_chroot capability also can we get information  how Redhat deploys the Jenkins in Openshift by default.

We are able to deploy Jenkins on openshift but to connect with slave container we are using ssh and to get that working we need to enable sys_chroot capability on cluster, but this is not the best way to enable sys_chroot capability since it will bring risk in cluster security.

Regards,
SAM

**Comment by akram** [comment]
Hi @samkhamk ,
the Jenkins image as provided by Red Hat usually runs on openshift under the `restricted`  SCC. 
This SCC does not allow the `CHROOT` capability:

```
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
```

Our Jenkins image does not use SSH for server-agent communication but the JNLP protocol.

**Comment by akram** [comment]
Hi @samkhamk ,
the Jenkins image as provided by Red Hat usually runs on openshift under the `restricted` SCC.
If you are running on openshift/okd you need to check if the SCC does not drop the `CHROOT` capability.

```
oc edit scc <your-scc>
```
Our Jenkins image does not use SSH for server-agent communication but the JNLP protocol.
