### ISSUE TITLE
[Pipeline-sync] Pipeline build, started before Jenkins is deployed, gets deleted

### ISSUE THREAD

**Issue by tnozicka** [openshift/jenkins#139]
If I create a pipeline BC and trigger it for the first time, it triggers jenkins deployment into that namespace and deletes the build. Starting it for the second time, after Jenkins is deployed, works.

Steps to reproduce:
 1. $ oc cluster up --version=v1.3.0-alpha.3 && oc process -f https://github.com/tnozicka/nodejs-ex/raw/kontinu8-next/.openshift-pipeline/pipeline-template.yaml -v 'GIT_URL=https://github.com/tnozicka/nodejs-ex.git,GIT_REF=kontinu8-next' | oc apply -f - && oc start-build nodejs-ex-pipeline && oc get build
 2. # you can see build nodejs-ex-pipeline-1
 3. # wait until Jenkins is deployed and ready
 4. $ oc get build  # shows no build at all
 5. $ oc start-build nodejs-ex-pipeline
 6. $ oc get build  # will show only the second one (nodejs-ex-pipeline-2) (+the source build)

@bparees

**Comment by bparees** [comment]
@gabemontero @jimmidyson i can't imagine what is deleting these builds (but i was able to recreate).  Are there any conditions under which the sync plugin would delete a build out of openshift?

**Comment by bparees** [comment]
it certainly used to be that if you created the build before jenkins existed, it would simply get run when jenkins started up (though there were some issues reported about cases where it didn't run it, but it certainly didn't delete it)

**Comment by jimmidyson** [comment]
The sync plugin deletes builds if the BuildConfig is deleted. IIRC that's the only place where OS builds are deleted.

**Comment by gabemontero** [comment]
Yep, the pipeline plugin does not delete builds.

**Comment by bparees** [comment]
QE has also just reported this issue here:
https://bugzilla.redhat.com/show_bug.cgi?id=1366223

I would have to assume the sync plugin is doing it, @jimmidyson is there some debug we can turn on or logging that would show up when the sync plugin deletes a build?

**Comment by bparees** [comment]
@jimmidyson and it seems likely this is related:
https://bugzilla.redhat.com/show_bug.cgi?id=1366200

(old builds being deleted when the buildconfig is modified)

**Comment by tnozicka** [comment]
It has been happening for at least a week or 2. I just got myself to properly investigate it today, sorry.

Also, as @bparees mentioned, there was a problem even before Summit that the first build failed when triggered by ConfigChange, but we have removed that trigger so I am not sure if it's an issue anymore.

**Comment by jimmidyson** [comment]
Sorry about that - fixed now.
