### ISSUE TITLE
System email address gets reset after restart

### ISSUE THREAD

**Issue by gaborfinta** [openshift/jenkins#1405]
Hello!

We have a Jenkins deployment running on Openshift and whenever the pod gets restarted, the System Admin e-mail address gets reset to the default nobody.
I identified _/opt/openshift/configuration/jenkins.model.JenkinsLocationConfiguration.xml.tpl_ file as the template that is used on every startup. It is used to generate the location configuration file but only the Jenkins URL is substituted so the _adminAddress_ field gets reset. I couldn't find a way to persist the email address after restarts. Could this be a bug or is there another way to keep the email address after restarts?

**Comment by gaborfinta** [comment]
This is still an issue for us. Is there a chance this will be fixed?

**Comment by akram** [comment]
@gaborfinta do you have the possibility to use the casc plugin to configure that?
The default casc config is in `/var/lib/jenkins/proxy.yaml`

**Comment by gaborfinta** [comment]
We do not use that plugin.
Since the configuration file is a template file, it would be the best to substitute all values in it. For example, the email address would get its value from a "JENKINS_EMAIL" environment variable.
