### ISSUE TITLE
extending image with s2i: proxy env variables for build only?

### ISSUE THREAD

**Issue by dakky** [openshift/jenkins#144]
Hello

I have another Problem when extending the jenkins image via s2i.
I added the following settings to the build config:
```
[...]
		"strategy": {
			"sourceStrategy": {
				"env": [
					{
						"name": "https_proxy",
						"value": "proxy:3128"
					},
					{
						"name": "http_proxy",
						"value": "proxy:3128"
					},
					{
						"name": "no_proxy",
						"value": "openshift.default.svc.cluster.local,localhost"
					}
[...]
```

Why? I need to use a proxy in order to download the additional plugins from jenkins-ci
Whats the problem? 
The problem is, that these env variables also exist in the running image and not onyl the builder. This forces me, to have an exessive long no_proxy host list (partial wildcards like *.interndon't work), so i have to list EVERY possible internal host.

So my Question:
Is there a way, to have these proxy settings only while assembling the image? Or unset them after that?
I don't want to copy the complete run script just to extend it with the line ``unset https_proxy``.

Any suggestions?

Thanks
Dakky

**Comment by bparees** [comment]
you can update the deploymentconfig to set http_proxy/etc to "" in your pod template.

but no, there is no way to set env variables at build time only today.  they will always exist in the final image.  so you have to override the value in the deploymentconfig for the image if you don't like that value.

**Comment by dakky** [comment]
a that was easy :D thanks
