### ISSUE TITLE
[sync-plugin] - Pipeline stage duration are not synced after deleting the pipeline and creating it again

### ISSUE THREAD

**Issue by tnozicka** [openshift/jenkins#145]
$(subject) + it shows the old durations and does not make sense.
#### Steps to reproduce:
1. $ oc cluster up --version=v1.3.0-alpha.3
2. $ oc process -f https://github.com/tnozicka/nodejs-ex/raw/kontinu8-next/.openshift-pipeline/pipeline-template.yaml -v 'GIT_URL=https://github.com/tnozicka/nodejs-ex.git,GIT_REF=kontinu8-next' | oc apply -f -
3. $ oc start-build nodejs-ex-pipeline
4. # wait for it to complete
5. oc delete bc/nodejs-ex bc/nodejs-ex-pipeline dc/mongodb dc/nodejs-ex routes/nodejs-ex svc/mongodb svc/nodejs-ex # this will not intentionally delete the imagestream which makes it faster next time
6. oc process -f https://github.com/tnozicka/nodejs-ex/raw/kontinu8-next/.openshift-pipeline/pipeline-template.yaml -v 'GIT_URL=https://github.com/tnozicka/nodejs-ex.git,GIT_REF=kontinu8-next' | oc apply -f -
7. Let the pipeline finish

After the second generation pipeline finishes you see the durations from first generation and it does not make sense. The whole duration of the pipeline is now 59 seconds, but e.g. "Create image" stage supposedly took 1 m 31 s. (The whole pipeline actually took 59 s now.)
#### Screenshots:

Generation 1, Run 1
![g1-r1](https://cloud.githubusercontent.com/assets/11869554/17806540/7b491e88-6605-11e6-853d-aecd58fca696.png)
Generation 1, Run 2
![g1-r2](https://cloud.githubusercontent.com/assets/11869554/17806542/7e1f09ce-6605-11e6-9c11-5573a5d5e17c.png)
Generation 2, Run 1
![g2-r1](https://cloud.githubusercontent.com/assets/11869554/17806543/8144f6f4-6605-11e6-90f2-85663a45fa1e.png)

@bparees @jimmidyson ideas?

**Comment by bparees** [comment]
@jwforres is this value coming from the web console or the sync plugin?

**Comment by bparees** [comment]
also @tnozicka for future reference this issue probably should have been filed against either the sync plugin:
https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues

or the origin web console:
https://github.com/openshift/origin-web-console/issues

**Comment by tnozicka** [comment]
@bparees ok, I will file next issues there

btw. At some point I have seen there something like '-40005'. (@jwforres)

**Comment by bparees** [comment]
I was not able to recreate this, though I did see some disturbing behavior with respect to resetting the build sequence in jenkins when the builds were deleted and buildconfig recreated.  things didn't work properly until the new build sequence number exceeded the previous number that was deleted.  

I wonder if, in your case, something was picking up data from the old build objects. (though it sounds like you deleted them since builds get deleted when the buildconfig is deleted)

**Comment by bparees** [comment]
@tnozicka if you can recreate it, it would be useful to see a dump of "oc get builds -o json" and "oc get buildconfigs -o json" along w/ the other information you've provided.

**Comment by tnozicka** [comment]
@bparees I can provide more precise info next week, but I remember checking it through `oc get all` to make sure there is only the imagestream and jenkins boilerplate. (Builds were not there; they were deleted as you say.) I would guess the data from build was only incorrectly preserved in a cache with regard to sync-plugin. Not sure why you could not reproduce it, I have tried it several times.

**Comment by bparees** [comment]
@tnozicka are you still able to recreate this w/ the latest jenkins centos image (centos because they contains a more updated sync plugin)?  if so can you provide the output i requested above?

**Comment by tnozicka** [comment]
@bparees I am on PTO right now; I can get you the data once I am back in January.

But I have found similar issue last month (https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/107)

**Comment by bparees** [comment]
similar perhaps, but i don't think related.

**Comment by bparees** [comment]
@tnozicka bump

**Comment by tnozicka** [comment]
sorry, I have been really busy lately. Just letting you know that it is still in my inbox and I should get to testing it in few days time

**Comment by bparees** [comment]
@tnozicka bump

**Comment by tnozicka** [comment]
@bparees my apologies for taking so long. 

I have tested it and with new jenkins images and `v1.5.0-alpha.2+e4b43ee-dirty` it does not happen anymore.
