### ISSUE TITLE
Update to Jenkins version 2.346.x

### ISSUE THREAD

**Issue by ma-fall** [openshift/jenkins#1456]
The last jenkins image is providing 2.319.3 which was release more than 4 months ago.

It would be great if you could provide an up to date image with the latest LTS 😊

**Comment by coreydaley** [comment]
/close
The current version of Jenkins being used on the master branch is 2.361.1 (https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/jenkins-version.txt), which is also being backported to previous versions.
