### ISSUE TITLE
Upgrade Jenkins LTS Version to fulfill Security Advisory Report Findings

### ISSUE THREAD

**Issue by saschalaudien** [openshift/jenkins#1457]
We are using the RedHat Openshift Jenkins Image. Currently we are trying to update the plugins from the Jenkins Security Advisor Report from May (https://www.jenkins.io/security/advisory/2022-05-17/) Unfortunately some of the plugins which which are using in our Jenkins Platform needs at least the Jenkins LTS Version 2.332.1. So that an update to the fixed plugin version will not work e.g., the script security plugin and the Pipeline: Groovy Plugin. Because the latest Jenkins Version which you offer is 2.319.3.

So, at the moment we can’t upgrade our Jenkins environment that all of the security fixes are in. The Jenkins LTS Version 2.332.1 which we need as a minimum was already released in March (https://www.jenkins.io/changelog-stable/) 

When do you plan to integrate this Jenkins Version or a more common version in your [RedHat Openshift Jenkins image](https://catalog.redhat.com/software/containers/openshift4/ose-jenkins/5cdd918ad70cc57c44b2d279?container-tabs=packages&tag=v4.10.0-202205311508.p0.gc8d7a0e.assembly.stream&push_date=1654608210000)?

**Comment by saschalaudien** [comment]
@coreydaley I saw that you made an update of the Jenkins Version here: https://github.com/openshift/jenkins/commit/0a97a57213eac438c4468345018c4fd9da8020dd
Any idea when a new openshift image will drop out of this? Usually we look here for an update: https://catalog.redhat.com/software/containers/openshift4/ose-jenkins/
But I can't see any updates there with the new Jenkins Version.

**Comment by coreydaley** [comment]
4.12 (master) has not been released yet, we are currently working on release a new 4.11, hopefully it will be available next week.
