### ISSUE TITLE
Kubernetes plugin is old

### ISSUE THREAD

**Issue by jlebon** [openshift/jenkins#1493]
The base image is currently shipping [`kubernetes:1.31.0`](https://github.com/openshift/jenkins/blob/c93cf5ddee06bfd299dc0991837333281500fe57/2/contrib/openshift/bundle-plugins.txt#L65), which is almost 10 months old now. There have been [many new releases](https://github.com/jenkinsci/kubernetes-plugin/releases) since then. Is there a reason the Kubernetes plugin pin hasn't been bumped in a while?

Or is the policy to only update plugins as necessary to conform with CVEs and satisfy the depsolver when Jenkins is rebased? If that's the case, I wonder if we should have a subset of core plugins not fall in this category but instead e.g. get bumped in master soon after we branch for a release.

**Comment by coreydaley** [comment]
We don't usually bump a plugin version unless it is 1.) affected by a CVE or 2.) a dependency of a plugin that is affected by a CVE. Is there a specific security or compatibility issue that you are running into?

**Comment by dustymabe** [comment]
> We don't usually bump a plugin version unless it is 1.) affected by a CVE or 2.) a dependency of a plugin that is affected by a CVE.

It would seem on a development branch (i.e. `master` in this case) we'd periodically bump to latest version of whatever plugins existed that our jenkins version supported. Is that not the case?

We hit this because another plugin we install pulls in a newer version of `kubernetes-client-api`:

```
Upgrading previously downloaded plugin kubernetes-client-api at 5.10.1-171.vaa0774fb8c20 to 5.12.1-187.v577c3e368fb_6
```

And then we hit https://issues.jenkins.io/browse/JENKINS-67483

So we needed a newer version of the `kubernetes` plugin and we found there were 10+ releases since `1.31.0` so we thought we'd ask.

**Comment by jlebon** [comment]
The policy seems reasonable though it means that people adding their own plugins may end up actually pulling later versions of base plugins as minimum requirements in the ecosystem move forward. This increases the delta from what was tested in OpenShift.

**Comment by coreydaley** [comment]
Our hope going forward is that we can periodically bump to the `latest` version of plugins and test them thoroughly, but we have some work to do before we get to that point.

Do you have any idea what the oldest version of the kubernetes-client-api that would be compatible with what you are doing would be?

**Comment by coreydaley** [comment]
It looks like https://github.com/jenkinsci/kubernetes-plugin/releases/tag/3578.vb_9a_92ea_9845a_ bumps the kubernetes-client-api to 5.12.1-187.v577c3e368fb_6. Will that work?

**Comment by dustymabe** [comment]
> Our hope going forward is that we can periodically bump to the `latest` version of plugins and test them thoroughly, but we have some work to do before we get to that point.

That's good news!

> 
> Do you have any idea what the oldest version of the kubernetes-client-api that would be compatible with what you are doing would be?

Don't worry too much about this specific problem. We can handle overrides on our own (see https://github.com/coreos/fedora-coreos-pipeline/commit/4a6513d572cf06bcedca8c22fda0d7dec31d8c42).

We thought we were reporting a bug (i.e. somehow automation failed to update that plugin for some reason), but it sounds like this is as designed.

**Comment by coreydaley** [comment]
Ok. Let us know if you need anything else from us.
/close
