### ISSUE TITLE
icons missing form dashboard Jenkins 2.346.3

### ISSUE THREAD

**Issue by kurisd** [openshift/jenkins#1494]
Out of the box missing some ui element!
During the latest update to Jenkins 2.346.3 icons changed from png to svg inline in code but left some old png ref.
example:
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/29768572/194027045-a7b9ccde-df28-4a1f-a400-06a1492eef8a.png">

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/29768572/194028147-1ef76c96-d527-4aa3-8baa-62b62e142f5c.png">

Architecture: amd64 Tag: v4.10.0-202209270517.p0.g67bd879 Jenkins 2.346.3

**Comment by coreydaley** [comment]
We are currently using 2.361.1 on the master branch and are working on backporting it to previous versions. https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/jenkins-version.txt

**Comment by kurisd** [comment]
The latest version in redhat catalog is Jenkins 2.346.3
Could you release a newer version from master which contain Jenkins 2.361.1?
[latest redhat jenkins2](https://catalog.redhat.com/software/containers/openshift4/ose-jenkins/5cdd918ad70cc57c44b2d279?push_date=1664882830000&container-tabs=overview&architecture=amd64&tag=v4.10.0-202209270517.p0.g67bd879.assembly.stream)

**Comment by coreydaley** [comment]
We are working on it.

**Comment by michelmeeuwissen** [comment]
Any update on 4.10 version? with latest Jenkins. The Github plugin is unavailable on this 4.10:latest version

![image](https://user-images.githubusercontent.com/7009844/197965924-7767a19c-7918-47c4-9948-78502e230641.png)

**Comment by coreydaley** [comment]
The Jenkins 4.10 image is currently using version 2.361.1 which should correct this issue.
Please open a new issue if you experience issues.
/close
