### ISSUE TITLE
/usr/libexec/s2i/run: line 578: [: ==: unary operator expected

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [openshift/jenkins#1533]
Please change https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L578

from
```
if [ $( oc get routes -o json | jq -c -r '.items[0].spec.tls')  == "null" ]; then
```
to
```
if [[ $( oc get routes -o json | jq -c -r '.items[0].spec.tls')  == "null" ]]; then
```

**Comment by coreydaley** [comment]
Thank you for letting us know, 
Please feel free to open a pull request which we will review.

**Comment by YevheniiPokhvalii** [comment]
> Thank you for letting us know, Please feel free to open a pull request which we will review.

Unfortunately, I have no permissions to submit pull requests to your repository.
```
fatal: unable to access 'https://github.com/openshift/jenkins.git/': The requested URL returned error: 403
```
