### ISSUE TITLE
warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [openshift/jenkins#1536]
Please add `glibc-langpack-en` to 
https://github.com/openshift/jenkins/blob/master/2/Dockerfile.localdev#L52

To avoid `warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)` and similar warnings in the container.

**Comment by coreydaley** [comment]
Thank you for letting us know!
Please feel free to open a pull request and we will test/approve it.
