### ISSUE TITLE
Remove Java8 from docker images

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [openshift/jenkins#1537]
Please remove Java8 since it may cause problems during installations of new Jenkins versions:
https://github.com/openshift/jenkins/blob/master/2/Dockerfile.rhel8#L65

**Comment by coreydaley** [comment]
That should be taken care of by https://github.com/openshift/jenkins/pull/1517

**Comment by nhojpatrick** [comment]
What is the last image to include Java 1.8???
I'm happy with Java 1.8 being removed, as long as it's clear what tag/hash people who still need Java 1.8 can pull.

**Comment by coreydaley** [comment]
Jenkins version >= 2.361.1 require Java 11 to run, however it looks like Java 8 is still supported for running builds. We are currently updating Jenkins >= 4.11 to use Java 11 to run Jenkins, but will leave Java 8 as long as it is available to install from the RHEL repositories.

@nhojpatrick Does that answer your question sufficiently?
