### ISSUE TITLE
Install Jenkins plugins with their new Plugin Installation Manager Tool for Jenkins

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [openshift/jenkins#1538]
The new Jenkins approach for installing plugins is with using this tool: https://github.com/jenkinsci/plugin-installation-manager-tool
instead of installation using bash scripts.
Nowadays they run this script that picks up Plugin Installation Manager Tool: https://github.com/jenkinsci/docker/blob/master/jenkins-plugin-cli.sh
I myself locally modified your Docker file to this:
```
RUN PLUGIN_CLI_URL="https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/${PLUGIN_CLI_VERSION}/jenkins-plugin-manager-${PLUGIN_CLI_VERSION}.jar" && \
    curl -fsSL ${PLUGIN_CLI_URL} -o /opt/jenkins-plugin-manager.jar && \
    /usr/local/bin/jenkins-plugin-cli.sh -l -w ${JENKINS_WAR} -f /opt/openshift/bundle-plugins.txt -d /opt/openshift/plugins/

```

**Comment by coreydaley** [comment]
Please feel free to submit a pull request and we will review it.

**Comment by coreydaley** [comment]
/assign @divyansh42 @mbharatk 
Can one of you please investigate using this tool instead of our current process?
What are the pros/cons etc.

**Comment by YevheniiPokhvalii** [comment]
Hi @coreydaley 
If you ask me, I moved to this tool personally because bash scripts did not install the correct plugin versions in some cases when there were some complex version naming like in 5.12.2-193.v26a_6078f65a_9.
