### ISSUE TITLE
How are plugins copied from /opt/openshift/plugins to /var/lib/jenkins/plugins ?

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [openshift/jenkins#1551]
Hi,

Could you help me to make out how plugins are copied from `/opt/openshift/plugins` to `/var/lib/jenkins/plugins` ?
I checked the code and did not find where it happens. Neither I found any soft links.

Could you let me know how you accomplish it?

**Comment by YevheniiPokhvalii** [comment]
Sorry, I guess, I found it:
https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L143

**Comment by coreydaley** [comment]
Looks like you found the answer on your own.
