### ISSUE TITLE
Question - openshift release to jenkins version mapping

### ISSUE THREAD

**Issue by nhojpatrick** [openshift/jenkins#1559]
What is the image hash I need for Jenkins v2.346.x LTS? aka last LTS to support Java 1.8.

Ideally the OpenShift v4.10.x stream as that is what I'm using this week.

I'm talking about these image streams;
quay.io/openshift/origin-jenkins
quay.io/openshift/origin-jenkins-agent-maven

I've worked out the new approach is using https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/jenkins-version.txt but I can work out what the last image was before this commit f9620999c0388870c113865ab082ac5b7e2913e2.

**Comment by coreydaley** [comment]
I only see the last 24 hours of history for a tag on quay.io. You may have to build your own image.
