### ISSUE TITLE
Enabling Systemd service in jenkins-1-centos7 image

### ISSUE THREAD

**Issue by akshayakhare** [openshift/jenkins#163]
I have a situation where I need to start some services within this jenkins container to make it work in our project. So i need Systemd enabled in order to do that...

As of now I get the below error when I try to run "systemctl" command within this container:
> Failed to get D-Bus connection: Operation not permitted
Which is expected.

Now on my research, I found that if we use the below docker file to create an image and then run a container, we should be able to run systemctl commands:

>FROM centos:7
>MAINTAINER "you" <your@email.here>
>ENV container docker
>RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i ==
>systemd-tmpfiles-setup.service ] || rm -f $i; done); \
>rm -f /lib/systemd/system/multi-user.target.wants/*;\
>rm -f /etc/systemd/system/*.wants/*;\
>rm -f /lib/systemd/system/local-fs.target.wants/*; \
>rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
>rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
>rm -f /lib/systemd/system/basic.target.wants/*;\
>rm -f /lib/systemd/system/anaconda.target.wants/*;
>VOLUME [ "/sys/fs/cgroup" ]
>CMD ["/usr/sbin/init"]

Now I believe this should work fine with the docker file which is provided for given image.
So I  updated the DOCKERFILE present in the slave-base folder, by adding the above commands.

After creating the image successfully, and running with the below command:

> docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8080:8080 __image-name__

Still the systemctl command fails...

My question is, what else do I need to do to enable systemctl commands.
There are currently 3 slave folders in this repository, do i need to update all three?

**Comment by bparees** [comment]
the systemctl commands failed when you ran "docker run" with your image?

**Comment by csrwng** [comment]
You may need to specify --privileged as well... see http://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container/

However, the issue of running systemd inside a Docker container has been discussed in many other places and has nothing to do with this repository. For example:  http://unix.stackexchange.com/questions/305340/how-to-run-systemd-services-in-arch-linux-docker-container

I am closing this issue. Please reopen if you feel there's something specific to the Jenkins image that is preventing you from doing what you want.

**Comment by akshayakhare** [comment]
Well that's ok...
I get the error after i try running the command in the bash after this command
> docker exec -i -t --user root --privileged=true  __image-id__ /bin/bash

And I tried running a new image with --privileged, with the same results...
