### ISSUE TITLE
yum install "returned a non-zero code:47"

### ISSUE THREAD

**Issue by deanpeterson** [openshift/jenkins#164]
I try to do a build using the Dockerfile.rhel7 and it fails at the yum install. It starts out not being able to find a bunch of packages:

No package jenkins-plugin-kubernetes available.
No package jenkins-plugin-openshift-pipeline available.
No package jenkins-plugin-openshift-login available.
No package jenkins-plugin-credentials available.
No package jenkins-plugin-ace-editor available.
No package jenkins-plugin-branch-api available.
No package jenkins-plugin-cloudbees-folder available.
No package jenkins-plugin-durable-task available.
No package jenkins-plugin-git available.
No package jenkins-plugin-git-client available.
No package jenkins-plugin-git-server available.
No package jenkins-plugin-handlebars available.
No package jenkins-plugin-jquery-detached available.
No package jenkins-plugin-mapdb-api available.
No package jenkins-plugin-matrix-project available.
No package jenkins-plugin-mercurial available.
No package jenkins-plugin-momentjs available.

...
then it fails with:
F1014 18:34:30.453952       1 builder.go:204] Error: build error: The command '/bin/sh -c yum-config-manager --disable epel >/dev/null || : &&     INSTALL_PKGS="rsync gettext git tar zip unzip nss_wrapper java-1.8.0-openjdk java-1.8.0-openjdk-devel atomic-openshift-clients jenkins-1.651.2 jenkins-plugin-kubernetes jenkins-plugin-openshift-pipeline jenkins-plugin-openshift-login jenkins-plugin-credentials jenkins-plugin-ace-editor jenkins-plugin-branch-api jenkins-plugin-cloudbees-folder jenkins-plugin-durable-task jenkins-plugin-git jenkins-plugin-git-client jenkins-plugin-git-server jenkins-plugin-handlebars jenkins-plugin-jquery-detached jenkins-plugin-mapdb-api jenkins-plugin-matrix-project jenkins-plugin-mercurial jenkins-plugin-momentjs jenkins-plugin-multiple-scms jenkins-plugin-pipeline-build-step jenkins-plugin-pipeline-input-step jenkins-plugin-pipeline-rest-api jenkins-plugin-pipeline-stage-step jenkins-plugin-pipeline-stage-view jenkins-plugin-pipeline-utility-steps jenkins-plugin-plain-credentials jenkins-plugin-scm-api jenkins-plugin-script-security jenkins-plugin-ssh-credentials jenkins-plugin-structs jenkins-plugin-subversion jenkins-plugin-workflow-aggregator jenkins-plugin-workflow-api jenkins-plugin-workflow-basic-steps jenkins-plugin-workflow-cps jenkins-plugin-workflow-cps-global-lib jenkins-plugin-workflow-durable-task-step jenkins-plugin-workflow-job jenkins-plugin-workflow-multibranch jenkins-plugin-workflow-remote-loader jenkins-plugin-workflow-scm-step jenkins-plugin-workflow-step-api jenkins-plugin-workflow-step-api jenkins-plugin-workflow-support jenkins-plugin-openshift-sync" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all  &&     localedef -f UTF-8 -i en_US en_US.UTF-8' returned a non-zero code: 47

**Comment by bparees** [comment]
@deanpeterson are you building on a rhel subscribed machine?
@tdawson would we expect these packages to be available to a normal rhel box today?

**Comment by deanpeterson** [comment]
Yes, I am building on a rhel subscribed machine. I am using a build config
in openshift, but I also grabbed the command and ran it on the host. I get
the same thing.

**Comment by tdawson** [comment]
Since Docker.rhel7 is only enabling epel, I wouldn't expect it to work.
There are two problems.
1 - Not all of the jenkins plugins are in Fedora
2 - Looks like Fedora packaging, and my packaging, have different names and have the .hpi in different locations.

 jenkins-plugin-credentials -> jenkins-credentials-plugin
/usr/lib64/jenkins/credentials.hpi -> /usr/share/jenkins/plugins/jenkins-credentials-plugin/credentials.hpi

**Comment by deanpeterson** [comment]
I'm having to switch back to the rhel version since the build is behind a proxy server that does not allow me to access yum packages for centos in anything except the standard rhel repo.  I am not sure I follow the statement above. Are the jenkins plugins this Dockerfile uses not available to a subscribed/registered RHEL 7.2 machine?  I am just looking for a stock Jenkins Dockerfile I can use to build jenkins with a custom JENKINS_HOME on a registered rhel machine without needing to access files on external networks with curl or other commands. Is the Docker.rhel7 file not meant for this?

**Comment by tdawson** [comment]
I'm sorry, I had misread the epel line.  And now that I read my comment, I can understand why it doesn't make sense.  Disregard what I said.

Most machines do not have the openshift repo enabled.  I think if you put in
--enablerepo=rhel-7-server-ose-3.3-rpms
things should work.

**Comment by deanpeterson** [comment]
Great, thanks!

**Comment by deanpeterson** [comment]
I was just able to get access to the rhel-7-server-ose-3.3-rpms repo, successfully enabled it and tried again. I get the exact same issue: https://gist.github.com/deanpeterson/f9ef1f99716196ad857daff4f6a1aad2

**Comment by deanpeterson** [comment]
Oh, I see. I have to yum install each of those packages separately.

**Comment by deanpeterson** [comment]
On my host, I am able to install all the missing packages. However, in a Docker build, I cannot get past all the errors seen here: https://gist.github.com/deanpeterson/f9ef1f99716196ad857daff4f6a1aad2

I am not able to use the subscription-manager within a container. I see the docker statements to modify the yum config to use the ose repo, yet all of the packages are still missing? How do I get my containers to see the packages my host sees?

**Comment by deanpeterson** [comment]
I had to make some changes to get the Dockerfile.rhel7 to work: https://gist.github.com/deanpeterson/3e7e57f5b70fa6089481e0a9bcdba8f0

Notice I had to add
`RUN yum repolist --disablerepo=* && \
    yum-config-manager --enable rhel-server-rpms > /dev/null && \
    yum-config-manager --enable rhel-7-server-extras-rpms > /dev/null && \
    yum-config-manager --enable rhel-7-server-ose-3.3-rpms > /dev/null && \
    INSTALL_PKGS="rsync gettext...`

I also had to remove jenkins-plugin-openshift-login from the yum install.  That package no longer seems to be available?

**Comment by bparees** [comment]
the jenkins-plugin-openshift-login might only be in the ose-3.4 repo and might not be public yet.

as for the rest we'll need @tdawson to weigh in again, i'm not a rhel subscription/yum repo guru, but in general when you docker build on a rhel machine, the container you're building is supposed to pick up the subscription/repos from the host machine.  So if you can yum install a package on your host, you should be able to yum install it within a container as part of a docker build.

Whether we have the right set of repos enabled during our Dockerfile's yum install commands is again, where we'll really need @tdawson's expertise.  We build the rhel image in a specialized internal environment which is why the Dockerfile.rhel7 files don't just "work out of the box" for you on a standard rhel system, my apologies for that.

**Comment by bparees** [comment]
@tdawson any advice you can offer here?

**Comment by tdawson** [comment]
@bparees is correct.  Those rpm's are only in the ose-3.4 repo.  So you need to change rhel-7-server-ose-3.3-rpms to rhel-7-server-ose-3.4-rpms

**Comment by tdawson** [comment]
We haven't every backfilled the jenkins-plugin rpms to older ose releases.  Is this something that needs to be done?

**Comment by bparees** [comment]
@tdawson no i don't think so.

**Comment by bparees** [comment]
@deanpeterson guessing you've long since given up or found another way to get this built, i'm closing this but feel free to comment/reopen if it's still something we can help you with.
