### ISSUE TITLE
Error: build error: contrib/openshift: no such file or directory

### ISSUE THREAD

**Issue by deanpeterson** [openshift/jenkins#165]
I was having trouble building the rhel7 version so I switched to the centos version.  Now I see this error:

Step 6 : COPY ./contrib/openshift /opt/openshift
928	F1014 19:21:03.004407       1 builder.go:204] Error: build error: contrib/openshift: no such file or directory

**Comment by bparees** [comment]
when building on openshift?  can you share your buildconfig?

**Comment by deanpeterson** [comment]
I am using this build config:
https://gist.github.com/deanpeterson/75852e0a84cc69bfd9b3546836a9b2c5

And the Dockerfile in http://openshift@stash-d00
/projects/OP/repos/jenkins.git is here:
https://github.com/openshift/jenkins/blob/master/1/Dockerfile

**Comment by bparees** [comment]
does that stash contain the contrib directory?  your git repo needs to basically contain everything here:
https://github.com/openshift/jenkins/tree/master/1
(you don't need the test dir or dockerfile.rhel7)

**Comment by deanpeterson** [comment]
That was dumb of me. I'm looking at about 20 things today and some basic
knowledge of Docker slipped my mind. Thanks!
