### ISSUE TITLE
Centos Permission denied error

### ISSUE THREAD

**Issue by deanpeterson** [openshift/jenkins#166]
I even tried adding USER root in the Dockerfile and I still get:

[91m/bin/sh: /usr/local/bin/plugins.sh: Permission denied
658	F1014 20:18:14.636754       1 builder.go:204] Error: build error: The command '/bin/sh -c /usr/local/bin/plugins.sh /opt/openshift/base-plugins.txt &&     touch /opt/openshift/plugins/credentials.jpi.pinned &&     touch /opt/openshift/plugins/subversion.jpi.pinned &&     touch /opt/openshift/plugins/ssh-credentials.jpi.pinned &&     touch /opt/openshift/plugins/script-security.jpi.pinned &&     chown -R 1001:0 /opt/openshift &&     /usr/local/bin/fix-permissions /opt/openshift &&     /usr/local/bin/fix-permissions /var/lib/jenkins' returned a non-zero code: 126

**Comment by bparees** [comment]
guessing plugins.sh doesn't have +x permissions in your git repo...

**Comment by deanpeterson** [comment]
Yes, that was it. Thanks!
