### ISSUE TITLE
No user exists for uid XXXX when trying to run scp command 

### ISSUE THREAD

**Issue by marodriguez-llbean** [openshift/jenkins#168]
When I try to run an scp command from my jenkins pod hosted in openshift, or any ssh-related command I got errors like these:

$ ssh  
No user exists for uid 1000060000  
$ id  
uid=1000060000 gid=0(root) groups=0(root),1000060000  
$                

doing some research, the root cause is that jenkins-openshift image is using a numeric user ID and not a fully featured Named user.  This post provides great level of detail: http://blog.dscpl.com.au/2015/12/random-user-ids-when-running-docker.html.

A possible solution is to consider using the nss_wrapper library, details explained here:  http://blog.dscpl.com.au/2015/12/unknown-user-when-running-docker.html

**Comment by bparees** [comment]
the jenkins image already implements nss_wrapper to assign a named user.
https://github.com/openshift/jenkins/blob/master/1/contrib/jenkins/jenkins-common.sh#L13-L29

how are you launching the image and are you sure you're using the latest version of our jenkins image (openshift/jenkins-1-centos7 or openshift/jenkins-2-centos7)?

**Comment by marodriguez-llbean** [comment]
I'm using the jenkins-persistent image available on the "Add to Project" menu , in OpenShift 3.2

**Comment by bparees** [comment]
i strongly suspect you do not have the latest jenkins image available in your cluster.  what does "oc get is jenkins -n openshift -o yaml" show you?

**Comment by marodriguez-llbean** [comment]
this is the YAML output

apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2016-06-22T15:09:32Z
  creationTimestamp: 2016-06-22T15:09:25Z
  generation: 2
  name: jenkins
  namespace: openshift
  resourceVersion: "367"
  selfLink: /oapi/v1/namespaces/openshift/imagestreams/jenkins
  uid: 4e8f755e-388b-11e6-a637-0050569f3e1f
spec:
  tags:
  - annotations:
      description: Provides a Jenkins server
      iconClass: icon-jenkins
      tags: jenkins
      version: 1.x
    from:
      kind: DockerImage
      name: openshift/jenkins-1-centos7:latest
    generation: 2
    importPolicy: {}
    name: "1"
  - annotations:
      description: Provides a Jenkins server
      iconClass: icon-jenkins
      tags: jenkins
    from:
      kind: ImageStreamTag
      name: "1"
    generation: 1
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: 172.30.100.235:5000/openshift/jenkins
  tags:
  - items:
    - created: 2016-06-22T15:09:32Z
      dockerImageReference: openshift/jenkins-1-centos7@sha256:c68cb58548525f235555fc542ab48917828177a5708e35fc9f1ed6778d49d48c
      generation: 2
      image: sha256:c68cb58548525f235555fc542ab48917828177a5708e35fc9f1ed6778d49d48c
    tag: "1"
  - items:
    - created: 2016-06-22T15:09:32Z
      dockerImageReference: openshift/jenkins-1-centos7@sha256:c68cb58548525f235555fc542ab48917828177a5708e35fc9f1ed6778d49d48c
      generation: 2
      image: sha256:c68cb58548525f235555fc542ab48917828177a5708e35fc9f1ed6778d49d48c
    tag: latest

**Comment by bparees** [comment]
that appears to have been imported in june which is quite old at this point.  You should have your admin run oc import-image to update the imagestream to the newest image available.

for comparison here are the values from just importing today:

```
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2016-10-18T03:16:26Z
  creationTimestamp: 2016-10-18T03:15:30Z
  generation: 2
  name: jenkins
  namespace: openshift
  resourceVersion: "681"
  selfLink: /oapi/v1/namespaces/openshift/imagestreams/jenkins
  uid: 2002b479-94e1-11e6-b192-507b9d27b5d9
spec:
  tags:
  - annotations:
      description: Provides a Jenkins server
      iconClass: icon-jenkins
      tags: jenkins
      version: 1.x
    from:
      kind: DockerImage
      name: registry.access.redhat.com/openshift3/jenkins-1-rhel7:latest
    generation: 2
    importPolicy: {}
    name: "1"
  - annotations:
      description: Provides a Jenkins server
      iconClass: icon-jenkins
      tags: jenkins
    from:
      kind: ImageStreamTag
      name: "1"
    generation: 1
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: 172.30.179.15:5000/openshift/jenkins
  tags:
  - items:
    - created: 2016-10-18T03:16:26Z
      dockerImageReference: registry.access.redhat.com/openshift3/jenkins-1-rhel7@sha256:5827c32e10233f75fb26d82f37bd1a3ad460f06079c7a71a76b795afef22dcf1
      generation: 2
      image: sha256:5827c32e10233f75fb26d82f37bd1a3ad460f06079c7a71a76b795afef22dcf1
    tag: latest
  - items:
    - created: 2016-10-18T03:16:26Z
      dockerImageReference: registry.access.redhat.com/openshift3/jenkins-1-rhel7@sha256:5827c32e10233f75fb26d82f37bd1a3ad460f06079c7a71a76b795afef22dcf1
      generation: 2
      image: sha256:5827c32e10233f75fb26d82f37bd1a3ad460f06079c7a71a76b795afef22dcf1
    tag: "1"
```

in the meantime, you can create a jenkins imagestream in your own project using the imagestream definition here:
https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-rhel7.json#L536-L571

And then when you instantiate the template you'll need to specify the NAMESPACE parameter value w/ your project name so it finds the correct imagestream:
https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-persistent-template.json#L277-L281

i'm not sure if the version of the template you have will have the NAMESPACE parameter, so you may need to grab the template from my link above.

**Comment by marodriguez-llbean** [comment]
will this image update affect the existing jenkins configuration ?  plugins? pipelines ?

**Comment by bparees** [comment]
it should be a compatible update.

**Comment by marodriguez-llbean** [comment]
sorry for keep asking but do I know the I will picking a compatible image ?  I'm not familiar with this process

**Comment by bparees** [comment]
if you want to be sure you'll have to test the new image by creating a new imagestream for it, importing the new image, and deploying it with your config.

**Comment by marodriguez-llbean** [comment]
is there anything else we had to do to fix this "No user exists for uid 1000060000" issue besides updating the jenkins image? 

just updated from openshift 3.2 to openshift 3.3 and just deploy a new jenkins 2.x image (IS description below) and still keep getting the same error when kick off SSH related commands .  Also, looking at the jenkins-common.sh file, I see the generate_passwd_file() function there with the NSS wrapper.

`
oc export imagestreamtag jenkins:latest -n openshift
apiVersion: v1
generation: 5
image:
  dockerImageLayers:
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 32
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:8d30e94188e7f13642d975e70c484e48c33867f3ede3277df1145803fa996ac1
    size: 70591526
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:de85c99a33997c2638066f603b493fb0c20f4013524fb965485b16860235da41
    size: 178701517
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:5573c181bbd58f12cf70e29ffd8723429024be2c4809f73da38504504d95870f
    size: 4318
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:b5e53325387ddc22b7d96d7706ea8c8cd3e2e96a5fb5b6b17297d022bdda7c85
    size: 6221
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:071b1401a1a16769985c3954b286bce9b865e9068b1a73e1acc4e8c45d8ce332
    size: 2333
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:883ad527148551bf278e0d6753f024d6e10b3f04f3a6dcf5edd622592e9c7ce8
    size: 48383366
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - mediaType: application/vnd.docker.container.image.rootfs.diff+x-gtar
    name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  dockerImageManifestMediaType: application/vnd.docker.distribution.manifest.v1+json
  dockerImageMetadata:
    Architecture: amd64
    Author: Ben Parees <bparees@redhat.com>
    Config:
      Cmd:
      - /usr/libexec/s2i/run
      Env:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - JENKINS_VERSION=2.7
      - HOME=/var/lib/jenkins
      - JENKINS_HOME=/var/lib/jenkins
      - JENKINS_UC=https://updates.jenkins-ci.org
      ExposedPorts:
        8080/tcp: {}
        50000/tcp: {}
      Hostname: 719d8d68f3dc
      Image: sha256:86cccb1912c9cd2f980329948fae2f624725878ea25d1b8a677f9ef54211ab6a
      Labels:
        build-date: "20160906"
        io.openshift.builder-version: 9b820bf
        io.openshift.s2i.scripts-url: image:///usr/libexec/s2i
        k8s.io.description: Jenkins is a continuous integration server
        k8s.io.display-name: Jenkins 2.7
        license: GPLv2
        name: CentOS Base Image
        openshift.io.expose-services: 8080:http
        openshift.io.tags: jenkins,jenkins1,ci
        vendor: CentOS
      User: "1001"
      Volumes:
        /var/lib/jenkins: {}
    Container: 55facb3b0b25a50214e7f546298c0a4c2392a36d5a33353aef52a59350880a44
    ContainerConfig:
      Cmd:
      - /bin/sh
      - -c
      - '#(nop) LABEL io.openshift.builder-version=9b820bf'
      Env:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - JENKINS_VERSION=2.7
      - HOME=/var/lib/jenkins
      - JENKINS_HOME=/var/lib/jenkins
      - JENKINS_UC=https://updates.jenkins-ci.org
      ExposedPorts:
        8080/tcp: {}
        50000/tcp: {}
      Hostname: 719d8d68f3dc
      Image: sha256:86cccb1912c9cd2f980329948fae2f624725878ea25d1b8a677f9ef54211ab6a
      Labels:
        build-date: "20160906"
        io.openshift.builder-version: 9b820bf
        io.openshift.s2i.scripts-url: image:///usr/libexec/s2i
        k8s.io.description: Jenkins is a continuous integration server
        k8s.io.display-name: Jenkins 2.7
        license: GPLv2
        name: CentOS Base Image
        openshift.io.expose-services: 8080:http
        openshift.io.tags: jenkins,jenkins1,ci
        vendor: CentOS
      User: "1001"
      Volumes:
        /var/lib/jenkins: {}
    Created: 2016-10-23T08:04:13Z
    DockerVersion: 1.10.3
    Id: 5431954252c3d03e582dc4af59ce4182d026936bd3ab28e0efdf2cccb7378850
    Parent: 514a68b2a7d09770eb4b1125f41e26ab75f4ebd1a63988a9c5f792c759b705ca
    Size: 297689313
    apiVersion: "1.0"
    kind: DockerImage
  dockerImageMetadataVersion: "1.0"
  dockerImageReference: openshift/jenkins-2-centos7@sha256:36fe5ba7f39e56f017f034872c02aaf271e3e8e02b658aff064412145b6baa6e
  metadata:
    annotations:
      description: Provides a Jenkins server
      iconClass: icon-jenkins
      tags: jenkins
    creationTimestamp: null
    name: sha256:36fe5ba7f39e56f017f034872c02aaf271e3e8e02b658aff064412145b6baa6e
kind: ImageStreamTag
metadata:
  annotations:
    description: Provides a Jenkins server
    iconClass: icon-jenkins
    tags: jenkins
  creationTimestamp: null
  name: jenkins:latest
tag:
  annotations:
    description: Provides a Jenkins server
    iconClass: icon-jenkins
    tags: jenkins
  from:
    kind: ImageStreamTag
    name: "1"
  generation: 1
  importPolicy: {}
  name: latest
`

**Comment by bparees** [comment]
are you running the commands from within a jenkins job definition, or are you rsh'ing into the pod and running commands, or some other mechanism?

**Comment by bparees** [comment]
(the NSS logic only takes effect for the jenkins process' environment and jobs spawned from it).

**Comment by marodriguez-llbean** [comment]
I bash into the jenkins pod and also run them from the jenkins pod terminal on the openshift web console

**Comment by bparees** [comment]
yes, if you run it from within a jenkins job it should work fine.

for example if you create a quick freeform job w/ a shell step that runs "whoami" and execute it, you will see it reports "default" in the build log.

the NSS config is not setup when you ssh/rsh into the pod because it requires some env variable and other config be run which we don't have a mechanism to tie into.

**Comment by bparees** [comment]
again the agent process itself should be running as a "known" user due to:
https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L18
https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/generate_container_user

whatever uid the container is running as, should be represented in the /etc/passwd within that container.  you can double check it.
