### ISSUE TITLE
create_jenkins_location_configuration_xml in s2i running everytime and removing email address

### ISSUE THREAD

**Issue by jonespm** [openshift/jenkins#1705]
We're running Jenkins using s2i on Openshift and every restart the email address was getting removed and replaced with

"address not configured yet <nobody@nowhere>"

I tracked it down to this function running here 
https://github.com/openshift/jenkins/blob/57d4ffbf08c29bd2e74fb4a5bec5240b62c1f313/2/contrib/s2i/run#L573

and it's executed immediately afterward every restart at
https://github.com/openshift/jenkins/blob/57d4ffbf08c29bd2e74fb4a5bec5240b62c1f313/2/contrib/s2i/run#L587

The value it's replacing is with the one in `jenkins.model.JenkinsLocationConfiguration.xml.tpl` in
https://github.com/openshift/jenkins/tree/master/2/contrib/openshift/configuration

Am I missing a step in the setup? The only thing I can think of to work around this without fixing this file are:

* Mount a volume at `${image_config_dir}` with my own custom files. `${image_config_dir}` is hardcoded to `/opt/openshift/configuration` so this can't be changed even with an existing persistent volume. Downside is if these files change I have to update them.
* Create a copy of this run file and use that as the ENTRYPOINT modifying it so it doesn't replace the value every time. Also same downside if the run script changes.
* Pass another script as a parameter that's on the persistent vlume that will fix-up the email address that the run resets. This seems the safest.

Is there something I'm missing. I don't think this function needs to even run every time. It could check if `${JENKINS_HOME}/configured` is set and avoid doing it again like other functions do. 

Thanks!

**Comment by coreydaley** [comment]
I wonder if it would make sense to make it an env var instead that gets replaced into the template the same way?

**Comment by jonespm** [comment]
The current env var of `JENKINS_URL` is also set by this code and can't be overridden by the environment. I think it could also be a solution if the script would check if both of those were already set or not in the environment and use what's there like it does with `JENKINS_JAVA_OPTIONS`, `JENKINS_SERVICE_NAME `and some others. Then I could pass `JENKINS_ADMIN_ADDRESS ` and be good to go too.

**Comment by coreydaley** [comment]
If you would like to put together a proposal/pull request I would be happy to review it.

**Comment by jonespm** [comment]
I haven't had a chance to try to fix this here yet. I've just been working around this with this groovy script running after Jenkins starts. I just set the `JENKINS_ADMIN_EMAIL` and have this file on the persistent volume in `/var/lib/jenkins/init.groovy.d`

```groovy
// This groovy script works around the bug on https://github.com/openshift/jenkins/issues/1705 and sets the email to match JENKINS_ADMIN_EMAIL
// Just place this in /var/lib/jenkins/init.groovy.d/update-email-address.groovy

import jenkins.model.Jenkins
import jenkins.model.JenkinsLocationConfiguration

// Check if the email address is set in the environment
def adminEmail = System.getenv("JENKINS_ADMIN_EMAIL")

// If the environment variable is not set, use a default value
if (adminEmail == null || adminEmail.isEmpty()) {
    adminEmail = "admin@jenkins.com" // Default email address
}

// get Jenkins location configuration
def jenkinsLocationConfiguration = JenkinsLocationConfiguration.get()

// set Jenkins admin email address
jenkinsLocationConfiguration.setAdminAddress(adminEmail)

// save current Jenkins state to disk
jenkinsLocationConfiguration.save()
```
