### ISSUE TITLE
Replace blue ocean with pipeline graph view

### ISSUE THREAD

**Issue by brandonmosher** [openshift/jenkins#1710]
Blue Ocean is no longer receiving updates and recommends using pipeline stage view or pipeline graph view instead. Can this be replaced with pipeline graph view which provides a similar visualization?

https://github.com/jenkinsci/blueocean-plugin
https://plugins.jenkins.io/pipeline-graph-view/

**Comment by coreydaley** [comment]
Is this a direct replacement (remove old, add new) or will we have to do any type of code updates to support this?
