### ISSUE TITLE
Switching Java versions by specifying USE_JAVA_VERSION no longer works

### ISSUE THREAD

**Issue by dominik0711** [openshift/jenkins#1712]
Hi team,

I have noticed that the [commit](https://github.com/openshift/jenkins/commit/f5deb0ab0e8dc96878c0ebf36d3adeea373ebb4c#diff-2d78b9157beed695d8f20444794c5a3372110ee103bee8db4a6b8fa808e747e2) from May 11  2023, removes the possibility to set the **JAVA_VERSION** by providing the environment variable **USE_JAVA_VERSION** for the shell script: _run-jnlp-client_ 

This setting of the Java version is described in [BASIC_USAGE.md](https://github.com/openshift/jenkins/blob/master/BASIC_USAGE.md) 

We rely on this possibility in our own jenkins-agent-builder images that use your image as our base. The script _run-jnlp-client_ still has the variable [**JAVA-VERSION**](https://github.com/openshift/jenkins/blob/57d4ffbf08c29bd2e74fb4a5bec5240b62c1f313/slave-base/contrib/bin/run-jnlp-client#L16) but the given value will not be used anymore. 

The script: _run-jnlp-client_ pins the java version to the default value **java-11** and can't be set from outside.

To make this work again, the deleted code needs to be reintroduced again:

```
if [[ "$(uname -m)" == "x86_64" ]]; then
	alternatives --set java $(alternatives --display java | grep $JAVA_VERSION | awk '/family.*x86_64/ { print $1; }')
	alternatives --set javac $(alternatives --display javac | grep $JAVA_VERSION | awk '/family.*x86_64/ { print $1; }')
#set JVM for all other archs
else
  alternatives --set java $(alternatives --display java | grep $JAVA_VERSION | awk '/family.*'$(uname -m)'/ { print $1; }')
  alternatives --set javac $(alternatives --display javac | grep $JAVA_VERSION | awk '/family.*'$(uname -m)'/ { print $1; }')
fi
```

**Comment by simonkrenger** [comment]
I have created https://issues.redhat.com/browse/OCPBUGS-24387 to track this on the Red Hat side
