### ISSUE TITLE
kube-slave-common.sh not working with a new jenkins-slave imagestream

### ISSUE THREAD

**Issue by jr00n** [openshift/jenkins#210]
With my OpenShift Origin 1.3 setup i get problems when i try make a new jenkins-slave image.
I've made a proper new imagestream with label "role=jenkins-slave" for my jenkins-slave

But then Jenkins got an corrupted config.xml because go template is not working on my system:

oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://10.2.2.2:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4

The {{index ...}} is not working for me.

https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L89

example:
oc get is/jenkins-slave-maven3-ibmjdk8  --template={{if index .metadata.annotations \"slave-directory\"}}{{index .metadata.annotations \"slave-directory\"}}{{else}}${DEFAULT_SLAVE_DIRECTORY}{{end}}
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'oc get resource/<resource_name>' instead of 'oc get resource resource/<resource_name>'

When i process the whole template:

oc get is/jenkins-slave-maven3-ibmjdk8 -o templatefile --template template.txt
error: error parsing template <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
```
    <name>{{.metadata.name}}</name>
    <image>{{.status.dockerImageRepository}}</image>
    <privileged>false</privileged>
    <command></command>
    <args></args>
    <instanceCap>5</instanceCap>
    <volumes/>
    <envVars/>
    <nodeSelector/>
    <serviceAccount>${oc_serviceaccount_name}</serviceAccount>
    <remoteFs>{{if index .metadata.annotations \"slave-directory\"}}{{index .metadata.annotations \"slave-directory\"}}{{else}}${DEFAULT_SLAVE_DIRECTORY}{{end}}</remoteFs>
    <label>{{if index .metadata.annotations \"slave-label\"}}{{index .metadata.annotations \"slave-label\"}}{{else}}${name}{{end}}</label>
  </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
```
, template: output:12: unexpected "\\" in operand

**Comment by bparees** [comment]
can you share your slave imagestream definition?

**Comment by bparees** [comment]
for comparison here is my imagestream which seems to work fine:
```
{
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "ruby",
        "annotations": {
          "openshift.io/display-name": "Ruby",
          "slave-directory": "/tmp/slavedir"
        },
        "labels": {
          "role": "jenkins-slave"
        }
      },
      "spec": {
        "tags": [
          {
            "name": "latest",
            "annotations": {
              "openshift.io/display-name": "Ruby (Latest)",
              "description": "Build and run Ruby applications on CentOS 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-ruby-container/tree/master/2.3/README.md.\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version of Ruby available on OpenShift, including major versions updates.",
              "iconClass": "icon-ruby",
              "tags": "builder,ruby",
              "supports": "ruby",
              "sampleRepo": "https://github.com/openshift/ruby-ex.git"
            },
            "from": {
              "kind": "ImageStreamTag",
              "name": "2.3"
            }
          },
         <more imagestream tags truncated>
```

**Comment by jr00n** [comment]
Thanks for your response...I tried it again and now it's working better...strange, now there is an node defined in the plugin, but not with a proper label...do i something wrong? Image and stream are defined in  https://github.com/jr00n/jenkins-jos-os <https://github.com/jr00n/jenkins-jos-os>

Regards,

Jeroen

  "kind": "ImageStream",
  "apiVersion": "v1",
  "metadata": {
    "name": "jenkins-slave-maven3-ibmjdk8",
    "labels": {
      "app": "jenkins-slave-maven3-ibmjdk8",
      "role": "jenkins-slave"
    },
    "annotations": {
      "label": "maven-ibmjdk8",
      "slave-directory": "/tmp"
    }
  },
  "spec": {},
  "status": {}
}

**Comment by bparees** [comment]
That looks correct, can you paste the jenkins config.xml PodTemplate entry?

**Comment by jr00n** [comment]
```
<templates>
        <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          <name>maven</name>
          <image>openshift/jenkins-slave-maven-centos7</image>
          <privileged>false</privileged>
          <command></command>
          <args></args>
          <instanceCap>2147483647</instanceCap>
          <label>maven</label>
          <volumes/>
          <envVars/>
          <nodeSelector/>
          <remoteFs>/tmp</remoteFs>
          <serviceAccount>jenkins</serviceAccount>
        </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
        <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          <name>nodejs</name>
          <image>openshift/jenkins-slave-nodejs-centos7</image>
          <privileged>false</privileged>
          <command></command>
          <args></args>
          <instanceCap>2147483647</instanceCap>
          <label>nodejs</label>
          <volumes/>
          <envVars/>
          <nodeSelector/>
          <remoteFs>/tmp</remoteFs>
          <serviceAccount>jenkins</serviceAccount>
        </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>

  <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
    <name>jenkins-slave-maven3-ibmjdk8</name>
    <image>172.30.53.244:5000/jos/jenkins-slave-maven3-ibmjdk8</image>
    <privileged>false</privileged>
    <command></command>
    <args></args>
    <instanceCap>5</instanceCap>
    <volumes/>
    <envVars/>
    <nodeSelector/>
    <serviceAccount>jenkins</serviceAccount>
    <remoteFs>/tmp</remoteFs>
    <label>jenkins-slave-maven3-ibmjdk8</label>
  </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
</templates>
```

**Comment by bparees** [comment]
> strange, now there is an node defined in the plugin, but not with a proper label

it looks like it has a label to me:
`<label>jenkins-slave-maven3-ibmjdk8</label>`

am i missing something?

**Comment by jr00n** [comment]
Aha i've found it. My Bad....The annotation in my imagestream is:
"label": "maven-ibmjdk8"
and not
"slave-label: "maven-ibmjdk8"

Your scripts is working as designed ;)

**Comment by bparees** [comment]
excellent :)
