### ISSUE TITLE
S2I Assemble Script Does Not Support Hidden Folder In The Configuration Directory

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins#212]
This is problematic if you want to version control `.m2/settings.xml`. This can be done with some additionally configuration, but it would be nice to support this scenario out of the box.

The issue is that https://github.com/openshift/jenkins/blob/master/1/contrib/s2i/assemble#L34 is using `mv` which does not support hidden files. Does it make sense to look for `.m2` specifically? Or is there a more general purpose solution here?

Happy to submit a patch to v1 and v2 once direction is decided.

**Comment by bparees** [comment]
Just an oversight/unconsidered scenario.  I think the proper fix would be to include all hidden files, eg:
http://ram.kossboss.com/shoptdotglob-copy-hidden-files-secrets-of-bash-what-does-asterick-selects/

so just add a `shopt -s dotglob` call before the mv.

**Comment by bparees** [comment]
@sherl0cks were you interested in submitting a PR for this?  (setting shopt -s dotglob)?

**Comment by sherl0cks** [comment]
Yes I am, life has just been hectic the last week. I can look at it next
work, or you can go ahead and make the change. I won't be heart broken.

On Dec 16, 2016 11:27 AM, "Ben Parees" <notifications@github.com> wrote:

@sherl0cks <https://github.com/sherl0cks> were you interested in submitting
a PR for this? (setting shopt -s dotglob)?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/openshift/jenkins/issues/212#issuecomment-267662428>,
or mute the thread
