### ISSUE TITLE
Is there an easy way to upgrade the Maven version for the maven slave?

### ISSUE THREAD

**Issue by petenorth** [openshift/jenkins#216]
In the Docker file for the maven slave image it has

ENV MAVEN_VERSION=3.0.5

The maven version required by the fabric8 goals I think needs to be higher than this

https://github.com/fabric8io/fabric8-maven-plugin/issues/556

It seems a bit onerous to go the s2i route to create a new Jenkins Maven Slave image with an updated ENV variable? Is there an easier way?

I tried setting an environment variable on the jenkins deployment config but it isn't picked up by the slave (which didn't suprise me!).

Peter.

**Comment by bparees** [comment]
the environment variable doesn't control the maven version, it's informational about what maven version was installed when the image was built:

https://github.com/openshift/jenkins/blob/master/slave-maven/Dockerfile#L12

I don't actually remember if there's a good reason we even define it (though as you can see for the centos image, we use it to drive which version we download.  for the rhel image, we don't).

So you are indeed going to have to create a new image if you want a different maven version, not to set the env variable, but to actually install the different package.  (and for rhel, we're installing the most current version provided as an rpm, as far as i know).
