### ISSUE TITLE
When upgrading plugins in a Jenkins image plugins are not overwritten

### ISSUE THREAD

**Issue by rawlingsj** [openshift/jenkins#255]
If we are using persistent storage and mounting a PV on $JENKINS_HOME then the  `$JENKINS_HOME/plugins/*` survive pod restart.  If however we update the Jenkins image which includes a plugin version update when jenkins starts the plugin on the PV is used and not the updated version.

This comment here suggests this behaviour is intentional https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/install-plugins.sh#L54 I wonder if we could have an env var or something to say override instead of skip, would that make sense?

**Comment by bparees** [comment]
I don't think that's the issue.  The way the jenkins image works, when you build the image we populate /opt/openshift with all your plugins, jenkins config, etc.

Then when the image starts, we check if /var/lib/jenkins is populated.  If it's not, we move the content from /opt/openshift over to /var/lib/jenkins.  If it *is* populated, then we don't do anything.

In other words, once you populate /var/lib/jenkins, that becomes the root of your jenkins installation.

https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L74-L117

You could change the run script in your image to always copy plugins over if you want.

**Comment by rawlingsj** [comment]
Ok thanks @bparees I'll have a go at that.

**Comment by rawlingsj** [comment]
I finally got around to this https://github.com/fabric8io/jenkins-openshift-base/commit/fa9ce3e9bb75d9a34e0e33dadc97f8e5619b1ab7 - thanks Ben!
