### ISSUE TITLE
can the jenkins2 image be tagged?

### ISSUE THREAD

**Issue by rawlingsj** [openshift/jenkins#256]
We're using the jenkins2 image and the s2i tool to layer on top plugins.  
```
s2i build . openshift/jenkins-2-centos7:latest fabric8/jenkins-openshift:latest --copy
```
Is it possible to tag the jenkins 2 images please?  I think just hit an issue where there was already an old :latest tag on our CD infra and that image was used rather than the latest in dockerhub.
 https://hub.docker.com/r/openshift/jenkins-2-centos7/tags/

**Comment by rawlingsj** [comment]
Our pipelines now pull the latest image to make sure so we avoid our issue but it might help others to use a tagged version.

**Comment by bparees** [comment]
i'm not sure how us tagging the images would help you, if you continue to reference "latest" you're still going to have this problem, and if you pick a different tag you're never going to get a newer image until you see there is a new tag available and reference it.

if you want to be using the latest images, you can always pass `--pull-policy=always`, and of course every image has a unique sha you could reference it by as well.

if we were to start tagging them, what sort of tagging scheme are you asking for?  Do you want a new tag every time we push a new image (eg using the git commit?)  or some sort of a versioned tag that we only update when we make "significant" changes to the image?  So far we've avoided this preferring instead to tell people to use latest and for us to not make compatibility-breaking changes in the image.

**Comment by rawlingsj** [comment]
> i'm not sure how us tagging the images would help you, if you continue to reference "latest" you're still going to have this problem, and if you pick a different tag you're never going to get a newer image until you see there is a new tag available and reference it.

I want to use a tagged version and not latest to ensure our releases are based on known versions.

> if we were to start tagging them, what sort of tagging scheme are you asking for? Do you want a new tag every time we push a new image (eg using the git commit?) or some sort of a versioned tag that we only update when we make "significant" changes to the image? 

Yeah either or TBH, we use both strategies on our own images.  For example this is the jenkins-openshift image that is created by our release pipelines https://hub.docker.com/r/fabric8/jenkins-openshift/tags/, 

If just in the short term each commit used the short git sha that would be great, until a more complete approach is decided.

Then I'll add to our pipeline whenever there's a new `openshift/jenkins-2-centos7` version available in dockerhub our fabric8 image pipeline will trigger, build, deploy, test and release.  

> So far we've avoided this preferring instead to tell people to use latest and for us to not make compatibility-breaking changes in the image.

Yeah and that's totally fair enough, I guess the detail I left off was we are planning to use this Jenkins2 base image in the DevTools SaaS so having tagged versions is going to be handy for us.

**Comment by bparees** [comment]
@rawlingsj ok, we'll see about at least pushing the commit tags for now.

**Comment by rawlingsj** [comment]
closing as we have a fork which is tagged + pushed to dockerhub https://hub.docker.com/r/fabric8/jenkins-openshift-base/tags/
