### ISSUE TITLE
Can't access jenkins API with OPENSHIFT_ENABLE_OAUTH=true

### ISSUE THREAD

**Issue by megnere** [openshift/jenkins#260]
Hi 

The authentication through the Openshift Login Plugin (with OPENSHIFT_ENABLE_OAUTH=true) works fine with a browser, but we can't access to jenkins API directly. Here is an example :
 _**curl -X GET -H "Authorization: Bearer $(our token)" https://${our_jenkins_url}/api/json?pretty=true -k -v**

With this requests, we always get this message :

**Authentication required

You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer**

We have used the namespace admin token and the jenkins service account secret.  
What are we missing here ?
Thanks for your help

**Comment by gabemontero** [comment]
3 things:
1) what version of the plugin is being used
2) can you supply the jenkins logs
3) if i recall correctly there was a issue with curl -k and jenkins; try
with http:// instead

Thanks

**Comment by megnere** [comment]
1) We are using OpenShift Login Plugin **0.1**
2) There are no logs related to authentication
3) with http://, i am redirected to https:// url.

**Comment by gabemontero** [comment]
You minimally need 0.10 to get the bearer token feature.  Assuming you are using the openshift jenkins image, you must be using an older RHEL one.

Either manually upgrade the plugin from the jenkins download center at https://updates.jenkins-ci.org/download/plugins/openshift-login (the latest is 0.11), find the newer rhel image (I believe the 3.5 jenkins rhel image should have this), or try the latest centos image from docker hub.

Also, for the login plugin to work in general, you must be at least at 3.4 for your openshift master.

**Comment by megnere** [comment]
Thank you,
The Bearer works fine with the 0.11 version.
We are using the latest Jenkins image in the Red Hat repository registry.access.redhat.com/openshift3/jenkins-2-rhel7. The Jenkins image embeds the 0.9 version of the plugin
