### ISSUE TITLE
Slaves offline

### ISSUE THREAD

**Issue by patrickw276** [openshift/jenkins#275]
I'm trying to run a Jenkins pipeline in enterprise OCP and can't get the slave images to run. I created a simple slave image similar to the nodejs example:

```Docker
FROM openshift/jenkins-slave-base-rhel7

MAINTAINER Patrick Williams <...>

ENV BASH_ENV=/usr/local/bin/scl_enable \
    ENV=/usr/local/bin/scl_enable \
    PROMPT_COMMAND=". /usr/local/bin/scl_enable"

COPY contrib/bin/scl_enable /usr/local/bin/scl_enable

RUN yum repolist > /dev/null && \
    yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    yum-config-manager --enable rhel-7-server-optional-rpms && \
    yum-config-manager --enable rhel-7-server-ose-3.2-rpms && \
    yum-config-manager --disable epel >/dev/null || : && \
    INSTALL_PKGS="rh-python35 rh-python35-python-devel rh-python35-python-setuptools rh-python35-python-pip rh-python35-python-psycopg2" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
```

After building the image and pushing it to an image stream, I configured the Jenkins Kubernetes plugin to use this image, called 'python35'.

I've got a pipeline buildconfig that uses this jenkinsfile:
```groovy
node('python35') {
    stage('test') {
        sh 'python --version'
    }
}
```

When I run the pipeline, I can see that pods are stood up in kubernetes but they never fully start. The jenkins build outputs something like:
```
[Pipeline] node
Still waiting to schedule task
python35-f448d26c2f442 is offline
```
while waiting for the pod to start.

It seems like the slave client isn't starting on the pods. There is no output when I do `oc logs -f python35-....`. Any advice on getting the client to start? Am I missing something in the docs?

**Comment by bparees** [comment]
do an oc describe on the slave pod.

i suspect you'll see it failed to pull the image... how did you reference the image name in the slave pod template configuration?  it should be something like "internalregistryip/yournamespace/python35" because it has to be a pullable reference.

**Comment by patrickw276** [comment]
Thanks for the quick response @bparees. The image pull doesn't seem to be the problem. I am using the value under "DOCKER REPO" from `oc get is jenkins-slave-python35` as the Docker image kubernetes config, which lines up with your example string. When I run `oc describe pod` it says the pod is terminated due to an error with exit code 139. The description shows events include "Pulled", "Created", "Started", and "Scheduled". I think the pod itself runs fine but something is stopping the jenkins slave client from running when it is started.

**Comment by bparees** [comment]
can you get the logs from the pod?

**Comment by patrickw276** [comment]
The pods don't log anything, they immediately terminate with no information. Looking at the "run-jnlp-client" script, I'm wondering if no arguments are being provided when the pod runs, making the script execute `exec "$@"` which just returns immediately. Is this possible? How is the script supposed to get it's arguments passed?

**Comment by bparees** [comment]
how did you setup your slave pod template?  did you mirror the existing examples?

https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L95

**Comment by patrickw276** [comment]
I'm just using the default generated pod template:

```
        <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          <name>jenkins-slave-python35</name>
          <image>{image name reference}</image>
          <privileged>false</privileged>
          <alwaysPullImage>false</alwaysPullImage>
          <command></command>
          <args></args>
          <remoteFs>/tmp</remoteFs>
          <instanceCap>5</instanceCap>
          <label>python35</label>
          <serviceAccount>jenkins</serviceAccount>
          <nodeSelector></nodeSelector>
          <resourceRequestCpu></resourceRequestCpu>
          <resourceRequestMemory></resourceRequestMemory>
          <resourceLimitCpu></resourceLimitCpu>
          <resourceLimitMemory></resourceLimitMemory>
          <volumes/>
          <envVars/>
          <annotations/>
          <imagePullSecrets/>
        </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
      </templates>
```

I see that it looks pretty different from what's generated by the script you linked. I'm wondering if theres a version conflict somewhere.

**Comment by bparees** [comment]
hm.  are you using our latest jenkins master image?  (centos/jenkins-2-centos7)?  you may need to pull a new version.

**Comment by bparees** [comment]
actually I guess i should ask, "generated by what"?

if you just went into the jenkins config page and defined the pod template, you definitely need to fill in additional information.

if you used the slave-label on an imagestream technique to get the pod template defined, it should be correct as long as your jenkins image is current.

**Comment by patrickw276** [comment]
I'm using the image stream slave-label technique along with the latest jenkins image from the Red Hat Container Catalog (registry.access.redhat.com/openshift3/jenkins-2-rhel7).

**Comment by bparees** [comment]
> I see that it looks pretty different from what's generated by the script you linked. I'm wondering if theres a version conflict somewhere.

no i think that's just because the script i referenced is for a newer version of the k8s plugin that the image now uses.  Since you're on an older image, your config is also (correctly) different.

are you able to successfully run jobs using the default maven or nodejs slaves?  trying to figure out if this is a config issue w/ your master, or w/ your slave.

**Comment by patrickw276** [comment]
I can successfully run jobs using the default maven slave so I guess that points to an issue with my custom slave pod.

**Comment by bparees** [comment]
yes, although just looking at your dockerfile certainly nothing stands out to me as obviously wrong.

139 is effectively a segfault for the JVM which is particularly odd.

**Comment by patrickw276** [comment]
Figured it out. There were a couple of things wrong:
1. My contrib/bin/scl_enable script was wrong. I accidentally had `source scl_enable enable rh-python35` vs `source scl_source enable rh-python35`. 
2. Our environment has a proxy set up for pulling code from our git repository. The environment variables `http_proxy`, `https_proxy`, `HTTP_PROXY`, and `HTTPS_PROXY` were automatically being set in the pod. The slave was trying to connect through the proxy, which couldn't reach the master. I unset those variables.

Many thanks for the support @bparees.

**Comment by bparees** [comment]
@patrickw276 awesome, glad to hear it and thanks for reporting back what the issue was!

**Comment by vamsi248** [comment]
Hello folks..
any idea why my jenkins master is not running with my own image container.. its always running job by using jnlp-slave default image. 
to stop this issue i tried one way..
i change container name as jnlp to my own image then pending node-hgf78 is offline,  jenkins is not running the job. Any hint please

regards
krish

**Comment by bparees** [comment]
If your image is not a jenkins-slave enabled image, then setting the container name to "jnlp" will not work.

You either need to make your image be a jenkins slave image (such as by basing it off our jenkins slave base image that we provide), or you need to follow the kubernetes plugin instructions for running multiple containers and running specific commands in specific containers within your slave pod:

https://github.com/jenkinsci/kubernetes-plugin#pipeline-support  (Specifically, see the "container" syntax which runs those specific pipeline commands within that particular container within the slave pod)

**Comment by vamsi248** [comment]
@bparees thanks for ur suggestion.. i cant use in freestyle job.. because the link u provided is showing for the pipeline job. but i  am using freestyle job..
and second doubt? if i want to make my image as jenkins slave image how i need to do... in my image i use nodejs as my dependencies..

**Comment by bparees** [comment]
> @bparees thanks for ur suggestion.. i cant use in freestyle job.. because the link u provided is showing for the pipeline job. but i am using freestyle job..

You'd be best served by asking those questions of the maintainers of the kubernetes plugin for jenkins.  I don't know if it is possible.

> and second doubt? if i want to make my image as jenkins slave image how i need to do... in my image i use nodejs as my dependencies..

you can use our nodejs slave image(openshift/jenkins-slave-nodejs-centos7).  If you want to extend it, just write a new dockerfile that starts with "FROM openshift/jenkins-slave-nodejs-centos7"

Or if you want to start from something cleaner and install your own nodejs packages, you can use "FROM openshift/jenkins-slave-base-centos7"

**Comment by vamsi248** [comment]
@bparees thanks for ur help... i am not using openshift.. i am using kubeadm in kubernetes..... 
i can make my docker file by typing in dockerfile
From jenkins/jenkins-slave 
because i am combing dotnet core and nodejs in one image..
