### ISSUE TITLE
Missing UTF-8 support, environment variable LANG not set

### ISSUE THREAD

**Issue by ropsahl** [openshift/jenkins#279]
Environment variable LANG not set, leading to missing UTF-8 support and Jenkins unable to handle non ASCII characters.
Workaround To get UTF-8 support add following to Dockerfile
ENV LANG="en_US.UTF-8"

**Comment by bparees** [comment]
You can also just set that env variable on the pod/container you're running, I would assume?

**Comment by bparees** [comment]
In general we don't explicitly set a LANG on any of our images.

**Comment by ropsahl** [comment]
I can make my own jenkins, with a dockerfile like:
```
FROM openshift/jenkins-2-centos7
COPY plugins.txt /opt/openshift/configuration/plugins.txt
RUN /usr/local/bin/install-plugins.sh /opt/openshift/configuration/plugins.txt
ENV LANG="en_US.UTF-8"
```
I would prefer using using the solution right out of the box, and I expect more users not to familiar with such configurations ending up spending much time chasing down the problem and finding a solution.

In the container UTF-8 is already set for Jenkins, but the shell where it is running is not. The effect is that I can make a new project in Jenkins with non ASCII characters like Å (LATIN CAPITAL LETTER A WITH RING ABOVE) and it will show correctly in the GUI, however I can not delete it as java.nio access to delete the work area will throw an exception, the same goes for working with source files having UNICODE letters in their path.

A short example from  running bash in a openshift/jenkins-2-centos7 container:
(Probably need UNICODE support in browser to )
Create file and show ls output:
```
$ docker exec -i -t $(docker ps|grep jenkins|awk '{print $1}') bash
bash-4.2$ touch /tmp/æøå_ÆØÅ.tmp
bash-4.2$ ls -lrt /tmp/*.tmp
-rw-r--r--. 1 default root   90382 Apr 25 05:13 jffi7904311933604650928.tmp
-rw-r--r--. 1 default root       0 Apr 25 05:17 ????????_??????.tmp
```
Setting LANG and filename is shown correctly:
```
bash-4.2$ export LANG="en_US.UTF-8"
bash-4.2$ ls -lrt /tmp/*.tmp
-rw-r--r--. 1 default root   90382 Apr 25 05:13 jffi7904311933604650928.tmp
-rw-r--r--. 1 default root       0 Apr 25 05:17 åæøå_ÆØÅ.tmp
```

Jenkins is started with file.encoding UTF8
```
bash-4.2$ ps -ef |grep java
default       1      0 15 05:12 ?        00:00:54 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -Duser.home=/var/lib/jenkins -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
default     188    137  0 05:18 ?        00:00:00 grep java
```

**Comment by bparees** [comment]
Thanks for the additional background.  I've got an open PR to add the variable:
https://github.com/openshift/jenkins/issues/280
