### ISSUE TITLE
Add podTemplate Volume to allow to persist .m2/repository for maven build

### ISSUE THREAD

**Issue by cmoulliard** [openshift/jenkins#283]
The existing template which is used to generate the podTemplate from an imagestream

```
# convert_is_to_slave converts the OpenShift imagestream to a Jenkins Kubernetes
# Plugin slave configuration.
function convert_is_to_slave() {
  [ -z "$oc_cmd" ] && return
  local name=$1
  local template_file=$(mktemp)
  local template="
  <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
    <inheritFrom></inheritFrom>
    <name>{{.metadata.name}}</name>
    <instanceCap>5</instanceCap>
    <idleMinutes>0</idleMinutes>
    <label>{{if not .metadata.annotations}}${name}{{else}}{{if index .metadata.annotations \"slave-label\"}}{{index .metadata.annotations \"slave-label\"}}{{else}}${name}{{end}}{{end}}</label>
    <serviceAccount>${oc_serviceaccount_name}</serviceAccount>
    <nodeSelector></nodeSelector>
    <volumes/>
    <containers>
      <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
        <name>jnlp</name>
        <image>{{.status.dockerImageRepository}}</image>
        <privileged>false</privileged>
        <alwaysPullImage>false</alwaysPullImage>
        <workingDir>/tmp</workingDir>
        <command></command>
        <args>\${computer.jnlpmac} \${computer.name}</args>
        <ttyEnabled>false</ttyEnabled>
        <resourceRequestCpu></resourceRequestCpu>
        <resourceRequestMemory></resourceRequestMemory>
        <resourceLimitCpu></resourceLimitCpu>
        <resourceLimitMemory></resourceLimitMemory>
        <envVars/>
      </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
    </containers>
    <envVars/>
    <annotations/>
    <imagePullSecrets/>
    <nodeProperties/>
  </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
  "
  echo "${template}" > ${template_file}
  $oc_cmd get -n "${PROJECT_NAME}" is/${name} -o templatefile --template ${template_file}
  rm -f ${template_file} &>/dev/null
}
```

doesn't allow to mount a [volume](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L86) to by example persist the .m2/repository used by the pod to build a maven project

Proposition is to add a PersistentVolumeClaim using as parameter the claimName and mounthPath

```
 <volumes>                                                                                                                                                                     
            <org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>                                                                                                     
              <mountPath>/home/jenkins/.m2</mountPath>                                                                                                                                  
              <claimName>jenkins-maven</claimName>                                                                                                                                      
              <readOnly>false</readOnly>                                                                                                                                                
            </org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>                                                                                                    
 </volumes>  
```

**Comment by bparees** [comment]
I don't think we want to make that change since it would require users have a free PV available to claim.

For now users are free to modify the slave configuration in their jenkins server after standing it up (or providing their own configuration via an s2i build of a new jenkins image, and run that jenkins image instead).

We are also working on a new feature this sprint to allow users to provide slave configuration via a ConfigMap object, so you could define your "PVC-enabled" maven slave definition via that mechanism.

But i don't think we want to hardcode the behavior in this way.  Sound reasonable?

@oatmealraisin fyi

**Comment by bparees** [comment]
Also this change would require the user define a PVC w/ that name in their project, right?  that is also likely to trip people up.

**Comment by cmoulliard** [comment]
> Sound reasonable?

This is reasonable

**Comment by cmoulliard** [comment]
> PVC w/ that name in their project,

I agree with you that this approach will bring more complexity.

**Comment by bparees** [comment]
Thanks, closing this issue, the feature for better configuration of slaves is being tracked here:
https://trello.com/c/hS9lzo1v

**Comment by cmoulliard** [comment]
> better configuration

Is there something already [available](https://trello.com/c/hS9lzo1v) that we could use as for the moment we are stuck to fork the jenkins 2 centos image and override the PodTemplate to pass the volume definition

```
<volumes>                                                                                                                                                                     
            <org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>                                                                                                     
              <mountPath>/home/jenkins/.m2</mountPath>                                                                                                                                  
              <claimName>jenkins-maven</claimName>                                                                                                                                      
              <readOnly>false</readOnly>                                                                                                                                                
            </org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>                                                                                                    
 </volumes>  
```

As, since OCP 1.6 we can pass ENV vars from the BuildConfig, we could override the existing [script](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh) to pass 2 keys that we could test within the shell script to include a volume -- make sense ? 

```
env:
  - name: mountPath
    value: /home/jenkins/.m2
  - name: claimName
     value: jenkins-maven
```

**Comment by bparees** [comment]
> Is there something already available that we could use as for the moment we are stuck to fork the jenkins 2 centos image and override the PodTemplate to pass the volume definition

i'm not sure i'd call that a fork, it's more like extending the existing image w/ a new layer that contains your customized slave-config script (or just provide your hardcoded jenkins config files w/ the right slave definitions in your customized image).  

another option would be to mount your config into the jenkins pod from a PV.

But otherwise no, there's nothing at the moment that you can do to use the existing jenkins image, as is, but get the pod template configuration you want.

> As, since OCP 1.6 we can pass ENV vars from the BuildConfig, we could override the existing script to pass 2 keys that we could test within the shell script to include a volume -- make sense ?

no i'm afraid i don't understand the suggestion.  The shell script that generates the slave pod template configuration is independent of (and has no access to) your buildconfig definitions.  When you provide env variables in your buildconfig, they are made available to the associated pipeline in general, not to a slave pod specifically.
