### ISSUE TITLE
flake on publishing test success

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins#294]
You'll see this in the merge output:

```
+ test_pull_requests --mark_test_success --repo jenkins --config /var/lib/jenkins/.test_pull_requests_jenkins.json
  Marking SUCCESS for pull request #--repo in repo ''
/usr/share/ruby/net/http/response.rb:119:in `error!': 404 "Not Found" (Net::HTTPServerException)
	from /bin/test_pull_requests:543:in `block in get_comments'
	from /bin/test_pull_requests:535:in `each'
	from /bin/test_pull_requests:535:in `get_comments'
	from /bin/test_pull_requests:1074:in `get_comment_matching_regex'
	from /bin/test_pull_requests:1090:in `get_comment_with_prefix'
	from /bin/test_pull_requests:779:in `mark_test_success'
	from /bin/test_pull_requests:2358:in `<main>'
Build step 'Execute shell' marked build as failure
```

**Comment by bparees** [comment]
i've added a kind/test-flake label to this repo (And this issue) since we'll probably need it in the future, but this particular issue probably belongs on the vagrant-openshift repo since it's not specific to the jenkins repo.  (and I'm assuming that rosie is smart enough to accept a test-flake issue from another repo, but @stevekuznetsov would have to confirm that).  (and of course the vagrant openshift repo probably doesn't have the kind/test-flake label either, yet).

**Comment by gabemontero** [comment]
On Sat, May 13, 2017 at 12:41 PM Ben Parees <notifications@github.com>
wrote:

> i've added a kind/test-flake label to this repo (And this issue) since
> we'll probably need it in the future, but this particular issue probably
> belongs on the vagrant-openshift repo since it's not specific to the
> jenkins repo. (and I'm assuming that rosie is smart enough to accept a
> test-flake issue from another repo, but @stevekuznetsov
> <https://github.com/stevekuznetsov> would have to confirm that). (and of
> course the vagrant openshift repo probably doesn't have the kind/test-flake
> label either, yet).
>
agreed / thanks

**Comment by stevekuznetsov** [comment]
> rosie is smart enough to accept a test-flake issue from another repo

She is -- I had assumed the majority of flakes you'd hit would be in Origin, as is the case with other repos, but the tests are divorced from the rest of the product enough that this is probably not the case. I've changed the Rosie config to expect `kind/test-flake` tags on issues in this repo, instead.

**Comment by gabemontero** [comment]
Thanks for the confirm @stevekuznetsov

Given what you are uncovering/fixing in the actual pull I am going to close this one out.

**Comment by bparees** [comment]
> She is -- I had assumed the majority of flakes you'd hit would be in Origin, as is the case with other repos, but the tests are divorced from the rest of the product enough that this is probably not the case. I've changed the Rosie config to expect kind/test-flake tags on issues in this repo,

can we just make her accept a kind/test-flake tag on any repo?

**Comment by stevekuznetsov** [comment]
> can we just make her accept a kind/test-flake tag on any repo?

@bparees today the code is written to accept only from one repo. If we end up needing that change I can look into it. Alternatively, [this](https://github.com/openshift/test-pull-requests/blob/master/test_pull_requests#L1369-L1436) is the section of code that drives that logic. We should be OK to just change the repository field to be a list, however "fancy" links that GitHub interprets and hyperlinks in the web UI will be hard to detect for other repos. Literal URLs should be fine.
