### ISSUE TITLE
MaxMetaspaceSize is too small and not variable

### ISSUE THREAD

**Issue by donnydavis** [openshift/jenkins#296]
MaxMetaspaceSize value is hardcoded, and this value should be variable. 

When running a pipeline build against openshift I receive out of memory errors, as does this issue filed against fabric8

https://github.com/fabric8io/fabric8-ui/issues/1279

Here are the references values
https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L65
https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L86

**Comment by bparees** [comment]
it's not hardcoded, you can override JAVA_GC_OPTS to set any value you want.

**Comment by donnydavis** [comment]
Copy that, thanks @bparees
