### ISSUE TITLE
Provide tagged version of openshift/jenkins images

### ISSUE THREAD

**Issue by iocanel** [openshift/jenkins#304]
Currently the openshift/jenkins images just use the `latest` tag.
For the obvious reasons, this can be problematic.

For example in the sysndesis propject we are using s2i with the `openshift/jenkins-2-centos7:latest` image. Every now and then a new latest tag comes out, using different plugin versions and completely breaking our ci.

Please provide actual tags, for us to use :-)

**Comment by gabemontero** [comment]
yep, per recent discussions between @bparees , @jupierce , @tdawson ( with his role transitioned to @smunilla ) and myself we are going to start doing this with v3.6 of openshift (which GA's in July of this year).

**Comment by iocanel** [comment]
Awesome! Thanks!

**Comment by bparees** [comment]
well, technically all we signed up to do was create branches of the repo to mark releases, not push images with a particular tag.

I think when @rawlingsj asked for this he ultimately decided to just use an image sha instead of latest, is not that an option for you?

**Comment by wei-lee** [comment]
any update on this? We are having the same issue. @bparees I think SHA value is an option, but it's hard to track which version the SHA value is pointed to.  Having  version tags will make it easier to know which version if being used.

**Comment by bparees** [comment]
when i cut the 3.6 branch of this repo (which i plan to do today), I will tag the docker hub image as 3.6.

**Comment by wei-lee** [comment]
@bparees good to know. Thanks.

**Comment by bparees** [comment]
tag 3.6.0 has been created: https://hub.docker.com/r/openshift/jenkins-2-centos7/tags/
