### ISSUE TITLE
Jenkins runs occasions out of memory

### ISSUE THREAD

**Issue by steven166** [openshift/jenkins#311]
We use this Docker image to run Jenkins in our Openshift cluster. We use the BitBucket branch source plugin to build all our microservices (40+) using Jenkinsfiles. When a lot of these builds happens at the same time, the Jenkins master throws a lot of **Out Of Memory Exceptions: Metaspace** before the slave node started. 

How can we fine-tune the memory settings so this doesn't happen anymore? Increasing memory doesn't do the trick.

**Comment by bparees** [comment]
Pass your own JAVA_GC_OPTS env variable which will supercede the 100m metadata value being configured here:
https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L65

**Comment by steven166** [comment]
Thanks, I'll try that

**Comment by bparees** [comment]
closing, but let us know if you are still having issues after trying it.
