### ISSUE TITLE
Git plugin

### ISSUE THREAD

**Issue by hbenmansour** [openshift/jenkins#33]
Hi, 

Since Git is the preferred SCM to be used with Openshift, is it a desired behavior that the Git plugin is not included in the image ? 

Regards

**Comment by bparees** [comment]
we're looking into what plugins to package with the image directly, there's some internal processes we need to deal with to publish a supportable image with additional plugins.

In the meantime hopefully you've seen the doc about how to extend this image with additional plugins?
https://github.com/openshift/jenkins#plugins

@mfojtik @gabemontero fyi.

**Comment by mfojtik** [comment]
@hbenmansour @bparees correct, you can rebuild the image to include your plugins as I did here:

https://github.com/mfojtik/jenkins-ci/blob/master/openshift/jenkins-master-ephemeral.json#L115
https://github.com/mfojtik/jenkins-ci/blob/master/jenkins-master/Dockerfile#L14

We are going to package some of the plugin as RPM's soon as we sort out the list we want to package.

**Comment by bparees** [comment]
@mfojtik where did this land w/ @tdawson.  did we package this one/are we going to?

**Comment by PI-Victor** [comment]
is this issue still ongoing?

**Comment by bparees** [comment]
looks like we are now packaging jenkins-plugin-git, jenkins-plugin-git-client, and jenkins-plugin-git-server.
centos:
https://github.com/openshift/jenkins/blob/master/1/contrib/openshift/base-plugins.txt#L59-L60
https://github.com/openshift/jenkins/blob/master/1/contrib/openshift/base-plugins.txt#L43

rhel:
https://github.com/openshift/jenkins/blob/master/1/Dockerfile.rhel7#L37
