### ISSUE TITLE
jenkins default to 32bit java when OPENSHIFT_JENKINS_JVM_ARCH is not defined

### ISSUE THREAD

**Issue by dnguyen9** [openshift/jenkins#364]
in the run script, the java version is set to 64bit if the OPENSHIFT_JENKINS_JVM_ARCH variable is not defined[1], however, it is set back to 32bit when calculating the HEAP_LIMIT [2].  This will cause the run script to exit with an error since the jenkins-agent java is build with 64bit.

(1)
# set the java version used based on OPENSHIFT_JENKINS_JVM_ARCH
if [ -z $OPENSHIFT_JENKINS_JVM_ARCH  ]; then
    echo "Using 64 bit Java since OPENSHIFT_JENKINS_JVM_ARCH is not set (historic setting)"
    alternatives --set java $JVMPath64bit

(2)
    if [[ -z $OPENSHIFT_JENKINS_JVM_ARCH && "${CONTAINER_HEAP_MAX}" -lt "${HEAP_LIMIT_FOR_32BIT_IN_MB}"  ]]; then
      echo "max heap in MB is ${CONTAINER_HEAP_MAX} and 64 bit was not explicitly set so using 32 bit Java"
      alternatives --set java $JVMPath32bit
      export MALLOC_ARENA_MAX=1
    fi

**Comment by bparees** [comment]
I don't see any issue when using the 32bit jvm explicitly:

```
OPENSHIFT_JENKINS_JVM_ARCH is set to i686 so using 32 bit Java
Downloading http://172.30.201.118:80/jnlpJars/remoting.jar ...
Running java -XX:+UseParallelGC -XX:MaxPermSize=100m -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -cp /home/jenkins/remoting.jar hudson.remoting.jnlp.Main -headless -url http://172.30.201.118:80 -tunnel 172.30.173.25:50000 7eb7c69e3240b932a81cd474e6f338368d4427a82b14c1023f3121e4d1b766ed nodejs-84e8a6bd058f
OpenJDK Server VM warning: ignoring option MaxPermSize=100m; support was removed in 8.0
Aug 23, 2017 10:05:51 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: nodejs-84e8a6bd058f
Aug 23, 2017 10:05:51 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Aug 23, 2017 10:05:52 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://172.30.201.118:80]
Aug 23, 2017 10:05:52 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, JNLP-connect, Ping, JNLP2-connect]
Aug 23, 2017 10:05:52 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: 172.30.173.25
  Agent port:    50000
  Identity:      46:9c:58:65:bc:fb:e9:ce:44:fe:f1:18:b2:f9:de:80
Aug 23, 2017 10:05:52 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Aug 23, 2017 10:05:52 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 172.30.173.25:50000
Aug 23, 2017 10:05:52 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Aug 23, 2017 10:05:53 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: 46:9c:58:65:bc:fb:e9:ce:44:fe:f1:18:b2:f9:de:80
Aug 23, 2017 10:05:53 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
```



There was an issue w/ the slave images not actually including the 32bit jvm and therefore failing when it was selected, but that has been fixed in the centos images (you may need to pull new ones) and should be fixed in the rhel images soon.

Do you have logs from your slave pod showing the failure/issue?

**Comment by bparees** [comment]
@dnguyen9 for now either switch to the centos slaves, or force your slaves to user 64 bit by setting the env var, sorry :(

new rhel images should be coming in a few weeks tops.
