### ISSUE TITLE
Issue downloading plugins from an alternative JENKINS_UC url

### ISSUE THREAD

**Issue by zonArt** [openshift/jenkins#373]
I'm trying to build a custom image based on jenkins-2-centos7 but fail to do so when setting the `JENKINS_UC` environment variable to an internal proxified repository, please have a look at the Dockerfile below:

`FROM jenkins-2-centos7
COPY jenkins/plugins_list /opt/openshift/configuration/
ENV JENKINS_UC http://<private repository>/artifactory/jenkins-plugins
RUN /usr/local/bin/install-plugins.sh /opt/openshift/configuration/plugins_list`

while it works fine if the `JENKINS_UC` is not set

This also works fine while executing the script on the running pod (strangely)

**Comment by bparees** [comment]
i'm not sure how to help you with this.  It seems the variable is being respected, but the value you are providing is not valid for the context in which the install-plugin.sh script is being run, which would point to a configuration issue at your end.

What error are you getting?  

Also you say "internally proxified repository"..  do you just mean a mirror, or is the private repository behind a proxy that also needs to be configured?

**Comment by zonArt** [comment]
Thing is that I don't have any error (at least not logged one), it looks like it is timing out as if internally the image couldn't resolve the url of my mirror (I don't see any logs on the mirror as if it doesn't receive the request at all) while it is ok when the container runs. To add some information, this was working fine when building the "official" jenkins image with same customization. To help a little further I add the full log from the docker build (don't know if it is possible to increase verbosity, would be a good start I guess)

[building_image.txt](https://github.com/openshift/jenkins/files/1276427/building_image.txt)

**Comment by zonArt** [comment]
Ok, I just found the explanation:
As I was suspecting from the beginning, `<my mirror>` url was not resolved within the image. I ran the `jenkins-2-centos7` image with bash command and tried to ping the url without success then having a look at `/etc/resolv.conf` I noticed that the dns are the google one though not possible to resolve local addresses. I now just need to understand how to give docker the option to define its own dns and I should be able to build it on my own.
Cool thing is that I can build it with no problem on OpenShift with a buildconfig I crafted correctly

**Comment by bparees** [comment]
Cool, thanks for the update, i'm going to close this as it's not an image issue.

For how to set the dns, it should pick up the /etc/resolv.conf from your host, so adding the appropriate entries to your host's /etc/resolv.conf is one way.

other options include updating the /etc/resolv.conf as a step within your dockerfile (and then potentially setting it back to the original value).
