### ISSUE TITLE
missing JDK packages on slave-base image (only JRE is being installed)

### ISSUE THREAD

**Issue by rafaeltuelho** [openshift/jenkins#383]
Looking at https://github.com/openshift/jenkins/blob/master/slave-base/Dockerfile.rhel7#L20 we see only

- java-1.8.0-openjdk-headless.x86_64 : OpenJDK Runtime Environment
- java-1.8.0-openjdk-headless.i686 : OpenJDK Runtime Environment

These packages actually installs only the JRE... The full JDK is from the following ones:

- java-1.8.0-openjdk-devel.x86_64 : OpenJDK Development Environment
- java-1.8.0-openjdk-devel.i686 : OpenJDK Development Environment

**Comment by bparees** [comment]
the devel package is installed only in the maven slave itself:
https://github.com/openshift/jenkins/blob/master/slave-maven/Dockerfile.rhel7#L23

however we do appear to be missing the 32bit devel package.
