### ISSUE TITLE
Sample does not work

### ISSUE THREAD

**Issue by johnjelinek** [openshift/jenkins#4]
When I follow the sample, this step fails:
```
cat job.xml | curl -X POST -H "Content-Type: application/xml" -H "Expect: " --data-binary @- http://$JENKINS_ENDPOINT/createItem?name=rubyJob
```

I looked into the container and saw this:
```
# docker logs -f k8s_jenkins-container.1af77831_jenkins-1-p9e0z_test_e9eee92c-1c21-11e5-a188-005056be126f_f02d302e
Running from: /usr/lib/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jun 26, 2015 4:47:16 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Jun 26, 2015 4:47:16 PM winstone.Logger logInternal
INFO: Winstone shutdown successfully
Jun 26, 2015 4:47:16 PM winstone.Logger logInternal
SEVERE: Container startup failed
java.io.FileNotFoundException: /var/jenkins_home/war/META-INF/MANIFEST.MF (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:280)
        at winstone.HostConfiguration.<init>(HostConfiguration.java:83)
        at winstone.HostGroup.initHost(HostGroup.java:66)
        at winstone.HostGroup.<init>(HostGroup.java:45)
        at winstone.Launcher.<init>(Launcher.java:143)
        at winstone.Launcher.main(Launcher.java:354)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at Main._main(Main.java:293)
        at Main.main(Main.java:98)
```

**Comment by bparees** [comment]
there are a host of currently known issues w/ this, but out of curiousity how were you running it?

https://bugzilla.redhat.com/show_bug.cgi?id=1232247
https://bugzilla.redhat.com/show_bug.cgi?id=1223249
https://bugzilla.redhat.com/show_bug.cgi?id=1213783

**Comment by johnjelinek** [comment]
I executed steps in the docs for the Jenkins sample for the cli.

**Comment by ffirg** [comment]
The make won't work on a minimal RHEL7 build. To get it to work:
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
sudo pip install -U websocket
pip install -U docker-compose

**Comment by bparees** [comment]
@johnjelinek this image has been cleaned up now and the instructions should work again.

@ffirg is that the best way to resolve the rhel issue, or is there a package that can be installed instead?  we build this image on rhel system w/o a problem, so i'm guessing there are some appropriate packages that could be installed which would be the preferred solution over downloading arbitrary content.

**Comment by ffirg** [comment]
@bparees intrigued. Do you use RHEL7 as your base build or RHEL6 per chance?

**Comment by ffirg** [comment]
@bparees suspect you have EPEL enabled?

Looks like that provides pip...

[root@dns ~]# wget https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
[root@dns ~]# rpm -ivh epel-release-7-5.noarch.rpm
[root@dns ~]# yum whatprovides pip
Loaded plugins: product-id, subscription-manager
epel/x86_64/filelists_db                                                                         | 5.8 MB  00:00:02
rhel-7-server-rpms/7Server/x86_64/filelists_db                                                   | 6.9 MB  00:00:03
python-pip-1.5.6-5.el7.noarch : A tool for installing and managing Python packages
Repo        : epel
Matched from:
Filename    : /usr/lib/python2.7/site-packages/pip



python-pip-1.5.6-5.el7.noarch : A tool for installing and managing Python packages
Repo        : epel
Matched from:
Filename    : /usr/bin/pip

**Comment by bparees** [comment]
@ffirg is your error w/ the easy_install invocation?

#  rpm -qf /bin/easy_install
python-setuptools-0.9.8-3.el7.noarch

I do not have python-pip installed.

**Comment by ffirg** [comment]
@bparees can't seem to check at the mo, having problems downloading from repos...

**Comment by bparees** [comment]
@ffirg we now have a rhel image available as well, but since it's built using our internal packaging repos you may not be able to build it.  you can pull it from registry.access.redhat.com/openshift3/jenkins-16-rhel7 (note that name is going to change very soon to jenkins-1-rhel7)

**Comment by bparees** [comment]
closing due to age, please reopen if you are still having issues with a current image and want to pursue this.
