### ISSUE TITLE
explore using --XX:ErrorFile for core file location

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins#401]
noticed in man page with open jdk 

consider if the jenkins jvm core dumps ... we want to files to go to the PV maybe so they are salvageable after Pod restarts 

@bparees @csrwng @stevekuznetsov fyi

**Comment by bparees** [comment]
i'm thinking the best option might be an env var to configure the destination.  (possibly don't even set the flag unless the user provided an env var value)

**Comment by Gl4di4torRr** [comment]
I would think an env var would be the correct approach too.

From CloudBees: 

```-XX:ErrorFile= You will need to specify the directory path for the hs_err_pidXXXX.log to be written to.
An example for Jenkins running on Linux is -XX:ErrorFile=locationOfYourChoice/hs_err_%p.log .
An example for Jenkins running on Windows is -XX:ErrorFile=“locationOfYourChoice\hs_err_%p.log” .```

Is this something you would still like to add? Maybe I can take try to implement this.

**Comment by gabemontero** [comment]
We will accept PRs for this @Gl4di4torRr

**Comment by bparees** [comment]
fixed in https://github.com/openshift/jenkins/pull/612
