### ISSUE TITLE
Use fixed versions/tags

### ISSUE THREAD

**Issue by steven166** [openshift/jenkins#403]
Could these Docker images be versioned instead of using the 'latest' tag. And could they refer to fixed versions of dependent base images. Because we had suddenly an issue with the 'oc' command, because the 'openshift/origin:latest' image is on 1.7 already. But our cluster is still at 1.5.

**Comment by bparees** [comment]
we did start publishing version tags, the first one was 3.6.0:  https://hub.docker.com/r/openshift/jenkins-2-centos7/tags/

**Comment by steven166** [comment]
But that tag is already 4 months old, so it's published before the actual 3.6.0 release?

**Comment by bparees** [comment]
in this case it was. we're still refining our process.

if you want to build your own 3.6 image you can use this branch and change the oc client that's included to be whatever version you need:
https://github.com/openshift/jenkins/blob/openshift-3.6/2/Dockerfile#L41

**Comment by steven166** [comment]
Yes I did that. But when running it by jenkins (different user I guess), it was somehow still using the 3.7 version of the oc client.
