### ISSUE TITLE
How to use those Jenkins slave images in OpenShift

### ISSUE THREAD

**Issue by eliu** [openshift/jenkins#406]
I've got frustrated on how to use the slave images (slave-base, slave-maven and slave-nodejs) and integrated in my OpenShift project. I wrapped them as image streams and referenced in the deployment template, but still got failed.

Looking into the logs of the respected containers and just stopped at 

```bash
OPENSHIFT_JENKINS_JVM_ARCH is set to i386 so using 32 bit Java
```
and nothing else ...

I also checked the main entrypoint script `run-jnlp-client` and found it needs some arguments to pass in. no further explanations about what kind of arguments we need to pass.

I need help!

**Comment by bparees** [comment]
it doesn't sound like you're using them correctly.  you don't need an imagestream and you don't need a deployment config.

https://docs.openshift.org/latest/using_images/other_images/jenkins.html#using-the-jenkins-kubernetes-plug-in-to-run-jobs

the slave images are used from jenkins when you have a jenkins master and a pipeline definition that is configured to run on a slave.

What exactly are you trying to do?

**Comment by eliu** [comment]
I created a new OpenShift project and create a new app by applying the recommended deployment template "Jenkins (Persistent)" with no problems so far. Then I was thinking if it can be configured to run jenkins jobs from respected slave containers. And I found this repo. 

I already read the doc you referenced, but still not get the point to enable slaves.

**Comment by bparees** [comment]
have you tried deploying this template and running the pipeline buildconfig it defines?

https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/samplepipeline.yaml

it will create a jenkins pipeline that runs on a slave pod.

**Comment by bparees** [comment]
specifically this part of the pipeline:
https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/samplepipeline.yaml#L111

says "run these pipeline steps on a jenkins slave node with the label `nodejs`" and if you look at the jenkins master configuration you'll find that the kubernetes plugin configuration includes the definition of a slave with the label "nodejs" by default.

**Comment by eliu** [comment]
@bparees many thanks. Finally I noticed a pod containing slave-maven or slave-nodejs image is being creating in background, when i finish the general setup for label expression in this reference https://github.com/openshift/origin/blob/master/examples/jenkins/README.md#steps-1

Is it possible to support custom image to build that slave pod? maybe we might have some other components to be installed and configured within the image.

**Comment by bparees** [comment]
you can use your own slave images if that is what you are asking.

we recommend you extend our existing slave-base image if you choose to do so as it contains all the infrastructure to startup and talk to the jenkins master correctly.  (this is the same image our slave-nodejs and slave-maven images extend).  

you can find the definitions for all those images in this repository.

the instructions for adding additional slave image configurations to Jenkins so you can use them from your jobs/pipelines are in the doc i referenced earlier.

**Comment by eliu** [comment]
that is exactly what i am looking for. i'll check out the doc to see what i can do to accomplish that.

I have another issue about this jenkins image, that is the docker 1.12.6 installed from yum by default seems not work properly on *push* operation, with error message "unauthorized: authentication required".

Should I open another issue? Since this one already got solutions.

**Comment by bparees** [comment]
i don't know what you're doing when you get the push authorization failure.  can you please provide more context?

**Comment by eliu** [comment]
I extended the image based on `openshift/jenkins-2-centos7` and install docker via yum, which is something like this:

```dockerfile
FROM openshift/jenkins-2-centos7

USER root

RUN set -x \
  && yum -y install docker

...

USER 1001
```

Then I run this image and exec into the container, typing something like this:

```bash
$ export DOCKER_HOST="tcp://<host>:2375"
$ docker login -u <user> -p <password>
Login succeed
$ docker pull hello-world
$ docker tag hello-world <user>/hello-world
$ docker push <user>/hello-world
...
521e87320aa7: Preparing
unauthorized: authentication required
```

There's no problem to do the push on my host, even on the docker official docker image `docker:1.12.6`.

**Comment by grdryn** [comment]
@eliu the problem could be that the default registry that docker is trying to push to (if not specified in the tag) isn't what you think it is. Are you trying to push to Docker Hub, or some other registry? You may need to specify that in the tag (and also maybe the login command).

What I'm saying may not make sense in this case, @bparees can hopefully correct me if I'm wrong!

**Comment by eliu** [comment]
@grdryn you can review my previous comments about this issue and you'll fiind:

- i have already run `docker login` command and docker prompt `succeeded`
- the same push statement works on my hosts and official docker 1.12.6 container, the version of which is currently the same as the one centos yum repo provide
- both docker hub and my private registry are tried and neither succeeded on this extended image

ps: later, i tried to install a latest version of docker-ce from docker official website and it works perfectly. I just want to know why this system provided docker package does not work as it is.

**Comment by bparees** [comment]
@eliu can you tag the image as "docker.io/user/hello-world" and then push it?  As @grdryn said, i suspect you are getting a different default registry than you expect.  It's better to always explicitly indicate the registry.

**Comment by bparees** [comment]
> I just want to know why this system provided docker package does not work as it is.

since you are not specifying a registry explicitly, the client will default to a registry.  The docker distributed client will default to docker.io.  The centos distributed package does not default to docker.io.

**Comment by eliu** [comment]
@bparees @grdryn Once again i tried with the same failure:

```bash
bash-4.2$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (eliu):
Password:
Login Succeeded
bash-4.2$ docker push docker.io/eliu/hello-world:latest
The push refers to a repository [docker.io/eliu/hello-world]
3a36971a9f14: Layer already exists
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

bash-4.2$
```

**Comment by bparees** [comment]
@eliu try `docker login docker.io`

and then cat ~/.docker/config.json to ensure you have an auth entry for docker.io.

**Comment by eliu** [comment]
```bash
bash-4.2# docker login docker.io
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (eliu):
Password:
Login Succeeded
bash-4.2# docker push docker.io/eliu/hello-world:latest
The push refers to a repository [docker.io/eliu/hello-world]
3a36971a9f14: Layer already exists
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

bash-4.2#
```
the config.json show below:

```bash
bash-4.2# cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "ZWxpdToxcTJ3M2U0cjV0QGRvY2tlcg=="
		}
	}
}
```

**Comment by grdryn** [comment]
@eliu In addition to what @bparees suggested, also ensure that you have a repo on docker.io under your `eliu` account, so that there's something to push to.

**Comment by grdryn** [comment]
@eliu Consider removing that auth string from the pasted `~/.docker/config.json` in your above comment!

**Comment by eliu** [comment]
Already update secret token with masks.

**Comment by eliu** [comment]
@grdryn repo has already been there: https://hub.docker.com/r/eliu/hello-world/

**Comment by bparees** [comment]
@eliu hm, well i'm out of ideas but i'm afraid you'll have to open a bug against the centos docker package for further investigation/assistance, as this isn't really related to the jenkins image.

**Comment by eliu** [comment]
@bparees it's about how the centos distributed docker package work within the container. Because there's no problems for this package if you install your centos on premise or VM.

**Comment by bparees** [comment]
@eliu ok, but unless it works in a pure "centos" image and only fails in the "jenkins" image, i don't think i'm going to be able to help you.

**Comment by grdryn** [comment]
@eliu @bparees I'm sure you've already thought of this, but for building images from Jenkins in OpenShift, I've always just delegated to OpenShift to build it, using a BuildConfig with the 'docker' strategy (I never thought of setting `DOCKER_HOST` like you have, and in most cases I wouldn't have access to a separate machine, or the OpenShift node itself).

For just pulling an image from one repo and pushing to another, I think [skopeo](https://github.com/projectatomic/skopeo) is the tool I'd have reached for, rather than the docker cli in the container pointing to a `DOCKER_HOST` on the node or somewhere else.

I'm not sure if that helps, it might give you some alternative ideas of ways you could get what you want, if you continue to hit issues with the docker cli.
