### ISSUE TITLE
When Openshift/Jenkins will decide to spin up a new Pod ?

### ISSUE THREAD

**Issue by arnaud-deprez** [openshift/jenkins#407]
Hi,

I'm not sure it's the right place to raise this issue as this could be a jenkins kubernetes issue but as I'm using it in Openshift, let's start from here.

I'm using the maven slave PodTemplate and I tried to run 3 builds simultaneously.

I've observed that the first build is executed directly and the other goes to the queue and once the first triggered job is done, the others are executed one by one until the queue gets empty.
I can see in the logs of pending jobs: `Waiting for next available executor on maven-jlsjp`

I would expect in such a situation that a new maven node would be spun up by Openshift as there is by default no limit in `max number of instances` (Integer.MAX_VALUE).

Any idea of what could be the reason of that ?

Thank you!

**Comment by csrwng** [comment]
@arnaud-deprez can you include your jenkins version and the version of the kubernetes sync plugin that is currently installed?

I have experienced delays in starting slave nodes, but haven't seen them run serially. Also, can you make sure that your job allows concurrent builds? (Should not have the `Do not allow concurrent builds` checkbox checked)

**Comment by bparees** [comment]
@arnaud-deprez in addition have you seen if the slave pods are being created in your project?  If so, what state are they in and does oc describe give any indication for why they are in that state?

**Comment by arnaud-deprez** [comment]
Hi,

Sorry for the delay.
I could reproduce it locally with minishift: `minishift start --openshift-version=v3.6.0 --memory=4GB`

Jenkins (2.73.1): 
```sh
$ cat /opt/openshift/base-plugins.txt
openshift-pipeline:1.0.52
openshift-login:0.12
openshift-client:1.0.0

# kubernetes plugin - https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin
kubernetes:1.0

# fabric8 openshift sync
openshift-sync:0.1.31

# Pipeline plugin - https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin
# 2.5 now includes pipeline-model-definition (declaritive pipeline)
# 2.4 brought in pipeline-milestone-step
workflow-aggregator:2.5

# remote loader https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Remote+Loader+Plugin
workflow-remote-loader:1.2

# mercurial - https://wiki.jenkins-ci.org/display/JENKINS/Mercurial+Plugin
mercurial:1.54
matrix-project:1.7.1
multiple-scms:0.6
ssh-credentials:1.13

# Pipeline Utility Steps Plugin - https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Utility+Steps+Plugin
pipeline-utility-steps:1.1.5

# some plugins helpful for global shared libs were broken out of workflow aggregator
pipeline-github-lib:1.0
github-organization-folder:1.6

# Jenkins v2 specific
matrix-auth:1.5
blueocean:1.1.6

# Legacy stuff
mapdb-api:1.0.1.0
subversion:2.9

# explicitly pull in plugins previously pulled in by dependencies because of
# security advisories  ...exclude plugins from
# advisories that were not previously pulled in by what is listed above
# also, as the plugins above raise their dependency levels for these plugins let's see about removing
# items from the list below
#
# processed sec adv https://jenkins.io/blog/2017/07/10/security-advisory/
# processed sec adv https://jenkins.io/security/advisory/2017-08-07/
#
config-file-provider:2.16.2
docker-commons:1.8
git:3.3.2
git-client:2.4.4
github-branch-source:2.0.8
job-dsl:1.60
parameterized-trigger:2.35.1
pipeline-build-step:2.5.1
pipeline-input-step:2.8
workflow-cps:2.39
script-security:1.31
```
@csrwng `Do not allow concurrent builds` is checked but it is fine for me. I don't want to have concurrent build for the same project, but I want concurrency for different project (my issue concern 3 different builds using the same labeled node `maven`).

@bparees Only one pod is created in my project corresponding to one slave (`maven-jlsp` in my first attempt). This pod is running correctly and when it has finished the current build, it takes the next one from the queue (expected behaviour for this Pod).
But I would expect Openshift to spin up other Pod(s) to handle the other jobs in the queue in parallel (as it is 3 different jobs for 3 different project). But instead, the other jobs log `Waiting for next available executor on maven-jlsjp` meaning, jenkins master is waiting this node to finish its current build scheduling the next one.

Perhaps there are some treshold here that needs to be met before Openshift spin up a new node but I couldn't find any information in the documentation about that.

**Comment by csrwng** [comment]
@arnaud-deprez just to clarify... 

> @csrwng Do not allow concurrent builds is checked but it is fine for me. I don't want to have concurrent build for the same project, but I want concurrency for different project (my issue concern 3 different builds using the same labeled node maven).

By project do you mean an openshift project (aka namespace)? or just a different job definition in jenkins? 

Taking a look with multiple jobs in Jenkins. I would expect all to work independently from each other.

**Comment by arnaud-deprez** [comment]
@csrwng sorry, I was meaning a different job definition in jenkins.

So I expect that, event if I do *not allow concurrent builds* per jenkins job, Openshift would be able to spin up many maven jenkins slave to handle all the enqueued jobs.

**Comment by csrwng** [comment]
@arnaud-deprez so I tested locally with the same version of the kubernetes plugin you have, and I'm not able to reproduce. I created 3 separate jobs, set them to not allow concurrent builds, and to run on the maven slave. I also put a sleep of 30 seconds in each job so that I could see if they were able to run concurrently. I started all 3 at the same time, and although the start time of each job was staggered, at some point all 3 jobs were running on 3 separate pods at the same time. 

Given this, two more questions for you:
- Is it possible that each job is finishing fast enough that it's done before the other one starts?
- Do you have quota in place that could limit the number of concurrent pods?

**Comment by arnaud-deprez** [comment]
@csrwng I didn't have quota.
It's however possible that jobs finished fast enough (but it is till ~2min) but I don't get the logic. If I increase the build time, I can now see new pods are spun up.
How does it decide it ? Is it configurable ? I couldn't find any documentation about that sorry :-S.

Anyway, it works so it's no more an issue but a question :)

**Comment by csrwng** [comment]
@arnaud-deprez It actually looks like the behavior is configurable. The plugin that handles launching slave pods is the Kubernetes plugin. Take a look at https://github.com/jenkinsci/kubernetes-plugin 
Search for "Over provisioning flags"

**Comment by arnaud-deprez** [comment]
Thank you very much for your time and sorry for this false positive bug. I was trying to figure out how it works :-).
Have a nice week-end!

**Comment by netoralves** [comment]
Hello everyone! 
I had the same behaviour, other possibility to manage this is decrease the "OpenShift Scaler" parameter, default value is 180 seconds to waiting conclude a exist jenkins-slave pod to spawn other. I set to 5 seconds and start 17 builds:

 oc get pods -o wide
NAME              READY     STATUS    RESTARTS   AGE       IP            NODE        NOMINATED NODE
jenkins-4-sr887   1/1       Running   0          19h       10.130.3.21   outlander   <none>
maven-1b2vz       1/1       Running   0          4m        10.128.2.44   tiguan      <none>
maven-41kw7       1/1       Running   0          4m        10.130.3.53   outlander   <none>
maven-6tzlj       1/1       Running   0          4m        10.128.2.43   tiguan      <none>
maven-d4dz2       1/1       Running   0          4m        10.130.3.56   outlander   <none>
maven-dlf11       1/1       Running   0          4m        10.130.3.55   outlander   <none>
maven-dz1g8       1/1       Running   0          4m        10.130.3.54   outlander   <none>
maven-f9gbz       1/1       Running   0          5m        10.128.2.42   tiguan      <none>
maven-rgxgq       1/1       Running   0          5m        10.130.3.51   outlander   <none>
maven-s68vx       1/1       Running   0          4m        10.130.3.52   outlander   <none>
maven-tmls4       1/1       Running   0          4m        10.128.2.48   tiguan      <none>
maven-wmk1h       1/1       Running   0          4m        10.128.2.46   tiguan      <none>
maven-zc2ws       1/1       Running   0          3m        10.128.2.50   tiguan      <none>
nodejs-l5mx5      1/1       Running   0          4m        10.128.2.49   tiguan      <none>
nodejs-rtxsf      1/1       Running   0          4m        10.128.2.47   tiguan      <none>
