### ISSUE TITLE
Update openshift jenkins plugins

### ISSUE THREAD

**Issue by cchet** [openshift/jenkins#409]
It seems that there are still some old openshift plugin versions used such as *openshift-sync 0.0.11* which is now available in version *0.1.32* which is a large gab

**Comment by bparees** [comment]
where do you see 0.0.11 being used?  

https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/base-plugins.txt#L10

**Comment by gabemontero** [comment]
On Sat, Oct 28, 2017 at 4:59 PM Ben Parees <notifications@github.com> wrote:

> where do you see 0.0.11 being used?
>
>
> https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/base-plugins.txt#L10
>
that was the version shipped with the 3.5 image I believe

**Comment by bparees** [comment]
newer images have updated plugin versions.
