### ISSUE TITLE
Jenkins image on registry.access.redhat.com doesn't have git command/package

### ISSUE THREAD

**Issue by nak3** [openshift/jenkins#41]
- issue

I know that it is supposed to be installed. - https://github.com/openshift/jenkins/blob/master/1/Dockerfile.rhel7#L34
However, `git` doesn't exist in the `jenkins-1-rhel7` container. Please see the output below

~~~
$ oc new-app registry.access.redhat.com/openshift3/jenkins-1-rhel7

$ oc rsh jenkins-1-rhel7-1-5hixu
bash-4.2$ git
bash: git: command not found

bash-4.2$ rpm -qa |grep git
openshift-3.0.1.0-1.git.527.f8d5fed.el7ose.x86_64
~~~

- env

~~~
$ docker images |grep jenkins
docker.io/openshift/jenkins-1-centos7                   <none>              19c8281e9fac        3 weeks ago         551 MB
registry.access.redhat.com/openshift3/jenkins-1-rhel7   latest              225d177d917d        9 weeks ago         481.1 MB
~~~

- other info

openshift/jenkins-1-centos7 (dockerhub) has git package/command.

**Comment by bparees** [comment]
the registry.access.redhat.com image hasn't been updated based on what's in github yet, i'm working on moving it through the publication process.

**Comment by nak3** [comment]
@bparees 
It looks like current release has git command. Please feel to close this issue.
~~~
$ oc rsh  jenkins-1-rhel7-1-8fq8n
bash-4.2$ git version
git version 1.8.3.1
bash-4.2$ 
~~~

**Comment by bparees** [comment]
thanks!
