### ISSUE TITLE
Request to update pipeline utility steps plugin to 1.5.1

### ISSUE THREAD

**Issue by csrwng** [openshift/jenkins#415]
Plugin: pipeline-utility-steps
Version: 1.5.1
https://plugins.jenkins.io/pipeline-utility-steps

The version of the plugin in the current Jenkins image is 1.1.5 and is missing useful utility steps like readJSON/writeJSON, readYaml/writeYaml

**Comment by csrwng** [comment]
@gabemontero

**Comment by bparees** [comment]
seems reasonable to me.

**Comment by gabemontero** [comment]
I cited the wrong issue in the above PR so this did not close automatically
