### ISSUE TITLE
test cgroup max heap behavior

### ISSUE THREAD

**Issue by bparees** [openshift/jenkins#418]
1) what heap does the -XX:+UseCGroupMemoryLimitForHeap argument actually choose for a container with a limit of X gigs and node memory of Y gigs?

2) if both -Xmx and  -XX:+UseCGroupMemoryLimitForHeap are set, which one takes effect?  Does order matter?

**Comment by gabemontero** [comment]
OK, quick reminder to myself, stuff like top is not cgroup aware, because it shows a lot more mem available thatn the 512Mi from the template's memory_limit.

That 512 holds .... see:
```
sh-4.2$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
536870912
```

The command line (with our latest image, so using the new JDK options) is:
```
java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms17m -Xmx256m -Duser.home=/var/lib/jenkins -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Djavamelody.application-name=JENKINS -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
```

And `ps -aux`

```
default      1 11.9  2.0 741124 248692 ?       Ssl  16:23   2:21 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms17m -Xmx256m -Duser.home=/var/lib/jenkins -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Djavamelody.application-name=JENKINS -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
```

If the 1/4 allocation of container memory via `-XX:+UseCGroupMemoryLimitForHeap` is true, it would appear the `-Xmx` is taking precedent.

Our jenkins image currently does not provide a means for `-Xmx` to *NOT* be set.

I'll construct a new image that does not set it, but uses `-XX:+UseCGroupMemoryLimitForHeap`, and report back.

**Comment by bparees** [comment]
i'd rather see this confirmed by taking a java core and looking at the heap settings reported by the JVM.

**Comment by gabemontero** [comment]
ok, i think this level of analysis is sufficient, but i'll circle back to java cores to be sure (in the middle of the no `-Xmx` experiment at the moment).

**Comment by gabemontero** [comment]
OK, with no `-Xmx` and `-Xms` set:

```
h-4.2$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0 99 17:18 ?        00:04:05 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Duser.home=/var/lib/jenkins -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Djavamelody.application-name=JENKINS -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
```

I'm seeing little difference in the RSS

```
default      1  121  1.9 608416 233772 ?       Ssl  17:18   4:06 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Duser.home=/var/lib/jenkins -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Djavamelody.application-name=JENKINS -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
default    201  0.0  0.0  15216  3328 ?        Ss   17:21   0:00 /bin/sh
```

tip of the hat to @bparees ;-)  .... need to analyze ... fortunately jmap makes it easy.

So:

```
h-4.2$ /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.i386/bin/jmap -heap 1
Attaching to process ID 1, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.151-b12

using thread-local object allocation.
Parallel GC with 4 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 5
   MaxHeapFreeRatio         = 10
   MaxHeapSize              = 134217728 (128.0MB)
   NewSize                  = 2621440 (2.5MB)
   MaxNewSize               = 44564480 (42.5MB)
   OldSize                  = 5767168 (5.5MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 16777216 (16.0MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 4294963200 (4095.99609375MB)
   G1HeapRegionSize         = 0 (0.0MB)

```

That looks like 1/4 of the container mem ... as reported in the customer email thread.

Have to run to an appt, but will redo the `-Xmx` run and report back with `jmap -heap 1`

**Comment by gabemontero** [comment]
When both explicit setting of the max heap and the use of the new property are employed, with the new property appearing *AFTER* the max heap setting (256m in this case):

```
default      1     0 39 19:36 ?        00:03:38 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms17m -Xmx256m -Duser.home=/var/lib/jenkins -XX:+Unloc
```

And given that we've proven the 1/4 ration of the new cgroup prop (where it was 128m, see above), the explicit map heap setting does in fact win:

```
sh-4.2$ /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.i386/bin/jmap -heap 1
Attaching to process ID 1, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.151-b12

using thread-local object allocation.
Parallel GC with 4 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 5
   MaxHeapFreeRatio         = 10
   MaxHeapSize              = 268435456 (256.0MB)
   NewSize                  = 6291456 (6.0MB)
   MaxNewSize               = 89391104 (85.25MB)
   OldSize                  = 12582912 (12.0MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 16777216 (16.0MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 4294963200 (4095.99609375MB)
   G1HeapRegionSize         = 0 (0.0MB)

```

**Comment by bparees** [comment]
so...

cgroup only - 1/4 of container
cgroup followed by xmx - xmx wins
xmx followed by cgroup - ??

**Comment by gabemontero** [comment]
On Mon, Nov 13, 2017 at 2:51 PM, Ben Parees <notifications@github.com>
wrote:

> so...
>
> cgroup only - 1/4 of container
> cgroup followed by xmx - xmx wins
> xmx followed by cgroup - ??
>
The example I posted was xmx followed by cgroup

**Comment by gabemontero** [comment]
The copy/paste between terminals may have cut things off

**Comment by bparees** [comment]
> The example I posted was xmx followed by cgroup

ps axwww is your friend :)

so i guess then my question is what about cgroup followed by xmx.

**Comment by bparees** [comment]
Also based on my findings w/ gradle, I think we need to stop and put all this in a google doc and figure our a disciplined plan for moving forward on:

1) settings for the "main" jvm process (jenkins master, jnlp client)
  - what we set, how users can override them

2) settings for maven + gradle jvms
  - what we set, how users can override

3) settings for compilation jvms launched by gradle (and presumably maven) (as discussed here: http://www.gubatron.com/blog/2014/07/29/solved-gradle-how-to-increase-the-java-compilers-available-heap-memory/)
  - what we set, how users can override

**Comment by gabemontero** [comment]
Yep I believe I proposed something similar in @jim-minter 's PR.

**Comment by gabemontero** [comment]
`-Xmx` overrides group regardless if coming before or after ... noted Xmx preceding above ... here is the Xmx after cgroups:

```
default      1 44.0  1.8 742824 226484 ?       Ssl  20:23   0:55 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Duser.home=/var/lib/jenkins -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Djavamelody.application-name=JENKINS -Xms17m -Xmx256m -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
```

```
h-4.2$ /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.i386/bin/jmap -heap 1
Attaching to process ID 1, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.151-b12

using thread-local object allocation.
Parallel GC with 4 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 5
   MaxHeapFreeRatio         = 10
   MaxHeapSize              = 268435456 (256.0MB)
   NewSize                  = 6291456 (6.0MB)
   MaxNewSize               = 89391104 (85.25MB)
   OldSize                  = 12582912 (12.0MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 16777216 (16.0MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 4294963200 (4095.99609375MB)
   G1HeapRegionSize         = 0 (0.0MB)
```

**Comment by jim-minter** [comment]
My reading is as follows: -XX:+UseCGroupMemoryLimitForHeap is a temporary flag introduced in the process of making cgroup awareness the default in the JVM.  -Xmx overrides at any time.

**Comment by bparees** [comment]
Cool, thank you @gabemontero and yeah, @jim-minter that summary sounds right and matches what we were told elsewhere.  It effectively just says "ignore the host memory, use the container memory value instead as the basis, but otherwise proceed as normal w/ allocations"

**Comment by gabemontero** [comment]
@bparees @jim-minter it is still a work in progress, but I sent you both a link to a google doc I'm composing to capture what @bparees asked for in https://github.com/openshift/jenkins/issues/418#issuecomment-344039944

**Comment by gabemontero** [comment]
Thanks for the additional clarification @jerboaa 

As it turns out, customer support / customer ran some experiments with `-XX:MaxRAMFraction=2` as well and reported the 50% result as well.

Between @jim-minter, @bparees , and myself various details on separate threads are being gathered with regard to recommendations and additional tuning in the jenkins slave / jnlp client / maven / gradle / additional processes they may fork, where we'll either update the openshift jenkins image (i.e. we very well may add `-XX:MaxRAMFraction=2` or `-XX:MaxRAMFraction=3` to our JAVA_OPTS setting) or update the documentation with various "users need to careful / cognizant" type messages.

Certainly if you have any best practices along those lines, or would like to continue to review what comes up, etc. just let us know.
