### ISSUE TITLE
Prevent leakage of zombie processes in jenkins master 

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins#421]
See https://github.com/openshift/release/issues/432 for details, including research around the core problem and how it was fixed in similar docker based images

**Comment by bparees** [comment]
@jim-minter if you find room for this in your other jenkins tech debt work this sprint, please considering knocking this out too.

I think @smarterclayton was also on board with tini.

**Comment by gabemontero** [comment]
Just started poking around as well ... assuming we only want to install the 64bit version, hopefully running a 32 bit JVM is orthogonal.  Something to include in unit testing.

**Comment by gabemontero** [comment]
Forgot ... `make test` in this repo runs 32 bit mode
