### ISSUE TITLE
New Jenkins LTS: 2.89.1

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#439]
I just saw this in one of the admin messages in my instance, so figured I'd highlight it here.

See here for more info: https://jenkins.io/changelog-stable/

**Comment by bparees** [comment]
@jupierce @adammhaile can we start the process of building a 2.89.1 rpm?

**Comment by bparees** [comment]
(thanks @grdryn)

**Comment by bparees** [comment]
looks like the rpm is built.

**Comment by sengaya** [comment]
Can someone explain or point me to some docs what the update strategies of the rhel and centos jenkins images are? The image at https://hub.docker.com/r/openshift/jenkins-2-centos7/ seems to be updated more frequently. The image at https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/openshift3/jenkins-2-rhel7 seems to be still at version 2.46 which is quite old and likely contains security bugs. Will the version 2.89.1 be pushed to both repos?

**Comment by grdryn** [comment]
There's now a 2.89.2 to address a security advisory.

https://jenkins.io/changelog-stable/
https://jenkins.io/security/advisory/2017-12-14/

**Comment by bparees** [comment]
sigh :)

i'll open a new issue for that so we can at least proceed w/ getting 2.89.1 landed.

**Comment by bparees** [comment]
issue for 2.89.2: https://github.com/openshift/jenkins/issues/445
