### ISSUE TITLE
Update to LTS 2.89.2

### ISSUE THREAD

**Issue by bparees** [openshift/jenkins#445]
@smunilla i know you just did 2.89.1 but now there's a 2.89.2..can we get it packaged?  thanks :/

**Comment by bparees** [comment]
thanks @jupierce

**Comment by pauvos** [comment]
@jupierce , I just downloaded `openshift/jenkins-2-centos7:latest` (docker.io) which is still version 2.73 and - by now - contains multiple known security issues (https://jenkins.io/security/advisory/2017-12-14/).

I understand the above link is internal (cannot resolve hostname) and only relevant for rhel-images?

Am I missing something here? Is there a self-serving way to trigger the build of centos-based images?

**Comment by bparees** [comment]
@pauvos until this PR merges, the centos image will not be updated to a new LTS.

You can build your own image based on this branch if you would like, otherwise you'll have to wait for this PR to merge.

(There is also a PR for 2.89.1 which will probably merge first): https://github.com/openshift/jenkins/pull/441
