### ISSUE TITLE
Don't use alpha clients as oc client for CentOS images

### ISSUE THREAD

**Issue by tanskann** [openshift/jenkins#446]
Currently the parent image for CentOS `Dockerfile` used is
`
FROM openshift/origin
`
Which is built with latest alpha version of oc client. We can't rely on that, but instead client built into this image should follow origin releases. Current stable version is 3.7.

Version of `oc` client with latest Jenkins image:

```
$ oc version
oc v3.9.0-alpha.0+1c24d18-233
kubernetes v1.8.1+0d5291c
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.30.0.1:443
openshift v3.7.9
kubernetes v1.7.6+a08f5eeb62
```

**Comment by bparees** [comment]
latest images are not guaranteed to be stable.  use the tagged images if you want something stable.
https://hub.docker.com/r/openshift/jenkins-2-centos7/tags/

**Comment by tanskann** [comment]
Hmm OK well that's a problem since v3.7 image is not refreshed with the latest Jenkins. Obviously I want that so that always have latest Jenkins in my v3.7 Openshift.

Maybe I'll just use the latest image then and remove the alpha client & put v3.7 client there.

**Comment by bparees** [comment]
you're certainly welcome to layer whatever oc client you want on top of the image, we fully support extending our images for specific needs.

I am going to update the v3.7 release stream to use the v3.7 base image here:
https://github.com/openshift/jenkins/pull/454

(but as you say, that will not help you if you want a newer jenkins version).
