### ISSUE TITLE
Update install-plugins script to support version specific update centers

### ISSUE THREAD

**Issue by bakito** [openshift/jenkins#447]
The install-plugins.sh from jenkinsci/docker does support version specific update centers for LTS versions. 
https://github.com/jenkinsci/docker/blob/678f3ec669666bada2f448f9da3f33c4eb0417a9/install-plugins.sh

        # If version-specific Update Center is available, which is the case for LTS versions,
        # use it to resolve latest versions.

It would be nice if this would be applied to the OpenShift Jenkins too.

**Comment by bakito** [comment]
This issue hits me when extending the jenkins with s2i.

**Comment by gabemontero** [comment]
thanks @bakito !

I should have a PR up shortly to verify that change is copacetic in our env.  Seems fine / safe upon visual examination.

**Comment by bakito** [comment]
@gabemontero Thank you very much

**Comment by gabemontero** [comment]
you're welcome @bakito and thanks again for alerting us to the update in jenkinsci/docker

**Comment by bakito** [comment]
@gabemontero your pull request was incomplete, please see my pull request #466 for a fix
