### ISSUE TITLE
Optional plugins should not all be installed by default

### ISSUE THREAD

**Issue by bakito** [openshift/jenkins#448]
The install-plugins.sh script installs all optional dependen plugins by default. According to the code this is due to a problem with the  matrix-auth plugin.

        # Note, matrix-auth plugin notes cloudbees-folder as optional in the archive, but then failed to
        # load, citing a dependency that is too old, during testing ... so we will download optional dependencies

1. Is theree still a problem with this plugin? If yes, then theproblem should be addressed in this plugin and not via work-arround in this script.
2. It it would still be nessesary to intall optional dependencies, it should be configurable to choose whether or not they are installed.

**Comment by bakito** [comment]
This issue hits me when extending the jenkins with s2i.

**Comment by gabemontero** [comment]
@bakito we do not install the optional plugin by default; we only look to see if the optional plugin was installed already, and if so, make sure the optional plugin is at a sufficient version

what happened was plugins with conflicting dependencies showing up:
1) plugin A depends on plugin C at version 2
2) plugin B has an optional dependency on plugin C at version 3

On start up, plugin B would fail if we only installed plugin C at the version plugin A needed.

However, if we removed plugin A, plugin C would *NOT* be installed.

It is not something we can address by "fixing" the plugin.

If you can supply the specifics in your s2i extension scenario, with the precise plugins and versions in question, and any logs associated, and the precise version of this repo you are using, in case you think the optional plugin was installed when it was not previously installed, reopen and we can pursue further.

**Comment by bakito** [comment]
@gabemontero Somehow I can't reproduce the problem any more. Currently it works as you described. During the time I wrote the issue, all optional dependencies where installed. 
I can't say it it was due to a problem of a plugin or something else.

Closing the issue is fine for me. Sorry for trouble.

**Comment by gabemontero** [comment]
no problem @bakito ; I may have not made this clear, but the current behavior was not always what was done; there was a time when we were always installing optional plugins, but then changed it to the current behavior; I suspect you saw this on an older version of the image, but with a later version you are good.
