### ISSUE TITLE
Warnings in Jenkins configuration screen after update to latest image

### ISSUE THREAD

**Issue by jr00n** [openshift/jenkins#470]
Hi, just used the latest image and got this message when entering the configuration page in Jenkins:

You have not configured the CSRF issuer. This could be a security issue. For more information, please refer to this page. 
You can change the current configuration using the Security section CSRF Protection.

Agent to master security subsystem is currently off. Please read the documentation and consider turning it on.

This Jenkins instance uses deprecated protocols: JNLP-connect,JNLP2-connect. It may impact stability of the instance. If newer protocol versions are supported by all system components (agents, CLI and other clients), it is highly recommended to disable the deprecated protocols. Protocol Configuration

**Comment by grdryn** [comment]
There might be some things in the discussion in #464 that are relevant to this.

**Comment by jr00n** [comment]
Thanks @grdryn i've looked at your repo and use https://github.com/feedhenry/wendy-jenkins-s2i-configuration/blob/master/configuration/config.xml.tpl in the meanwhile.

**Comment by gabemontero** [comment]
On Tue, Jan 9, 2018 at 10:00 AM Jeroen Wolff <notifications@github.com>
wrote:

> Thanks @grdryn <https://github.com/grdryn> i've looked at your repo and
> use
> https://github.com/feedhenry/wendy-jenkins-s2i-configuration/blob/master/configuration/config.xml.tpl
> in the meanwhile.
>
yep we are NOT turning on CSRF by default at this time per the discussion
thread @grdyn noted

**Comment by gabemontero** [comment]
also note ... the feature has been there for a while, jenkins upstream has simply decided to add the warning
