### ISSUE TITLE
Please remove base plugin multiple-scms-plugin

### ISSUE THREAD

**Issue by jr00n** [openshift/jenkins#472]
This plug-in is causes null pointer exceptions in the log when displaying the /configuration page.

https://github.com/openshift/jenkins/blob/bb0877cb889609432b3c7713943d0d2c579556c6/2/contrib/openshift/base-plugins.txt#L24

https://issues.jenkins-ci.org/browse/JENKINS-40545

This plugin is deprecated https://plugins.jenkins.io/multiple-scms

So maybe better to remove also with the mercurial plugin, and if one is needed, you extend this base image. Now i have to override ./s2i/bin/assemble to remove this plugin from my images to prevent those null pointers.

**Comment by gabemontero** [comment]
Thanks for the heads up on deprecation wrt multiple-scms, where generic pipeline support is claimed as the replacement, @jr00n 

I'll see about running this through our regression testing on Wednesday and if things are OK get a merge going.

Looking through the links your sent, I did not see anything referencing mercurial.  And it is not listed as deprecated on its plugin page.  Did I miss something in the pages you linked, or what was your rationale there?

**Comment by gabemontero** [comment]
ok, our plugin regression suite of freestyle and pipeline jobs passed with multiple-scms removed ... crafting a PR shortly to update the image.

per earlier comment, pending a response to my questions, refraining from deleting mercurial ... I see no NPE when entering /configure with multiple-scms gone and mercurial still there

**Comment by jr00n** [comment]
No, you are right. Mercurial slipped out my fingers. Just a plugin i don’t need, but not an issue here ;)

Regards,

Jeroen

**Comment by gabemontero** [comment]
On Fri, Jan 12, 2018 at 4:44 AM, Jeroen Wolff <notifications@github.com>
wrote:

> No, you are right. Mercurial slipped out my fingers. Just a plugin i don’t
> need, but not an issue here ;)
>

Great thanks for following up!


> Regards,
>
> Jeroen
>
