### ISSUE TITLE
Image tagging on docker hub

### ISSUE THREAD

**Issue by spicysomtam** [openshift/jenkins#481]
I notice on docker hub  that you have now started tagging the centos images with the openshift release. Thats good since there was no tagging before. But how about also tagging them with the Jenkins release too? As a devops engineer, the Jenkins version is pretty important, and tbh we need to upgrade fairly regularly the Jenkins release because of security vulnerabilities, etc. You can have multiple tags per image (in case you did not know this). Otherwise I need to download the image, spin it up, and then see what version of Jenkins it runs. Since openshift runs as non root it can be tricky updating the Jenkins.war to bring it up to date. Or you might add a wiki table somewhere which says image v3.6 runs Jenkins blah.

**Comment by gabemontero** [comment]
Adding say a table to this repo's readme with the jenkins info seems reasonable.

As to pushing multiple tags for a given image ... I suspect we might be bumping up against openshift conventions, but don't know for sure .... before saying "no", any insight / opinions @bparees ?

**Comment by bparees** [comment]
It wouldn't exactly cause a convention problem but i don't love it.

After we start making tags like "jenkins-2-centos7:openshiftv3.7-jenkinsv2.89" (which in itself is a mess) someone's going to start asking us to "please update the jenkins-2-centos7:v3.7-jenkinsv2.73" image to include the fix that was put into jenkins-2-centos7:v3.7-jenkinsv2.89".

The table is ok but someone's going to have to remember to update it every time we bump the LTS and we're probably going to forget to do that from time to time too.

Not to mention if you just look at:
https://github.com/openshift/jenkins/blob/master/2/Dockerfile#L37

You can see what LTS we're currently installing.  (jenkins-2.89.2-1.1 as of this comment).

**Comment by spicysomtam** [comment]
I could see a problem where you have two version tags (say `v3.7` and `v3.9`)  and they have the same Jenkins version, so multiple tagging could be an issue? I suppose the problem is you want to use image `v3.7` but have the ability to upgrade the Jenkins version, since Jenkins is often updated due to security vulnerabilities. Since openshift runs as non root for containers its not easy to replace the Jenkins.war without building a new image? Suppose you could mount a volume where the war file lives and then update it that way?

**Comment by bparees** [comment]
> Since openshift runs as non root for containers its not easy to replace the Jenkins.war without building a new image? 

Changing the war should always involve building a new image. Mounting the war from a volume is possible, but it's a far less stable/reproducible deployment model.  In general you want to treat your images as being as immutable as possible.

**Comment by gabemontero** [comment]
Back to indicating the jenkins version in the readme ....

I'm going to see if I can update a file in the repo that pulls the jenkins version from the resulting image as part of the build process out of the Makefile.  Then just link to that file from the readme.

**Comment by grdryn** [comment]
> Although you still have to pull an images as @spicysomtam referred to earlier, this command allows you to get the version without bringing up jenkins proper

@gabemontero if you add a label with the specific Jenkins version, then I think one would be able to use a tool such as [skopeo](https://github.com/projectatomic/skopeo) to check the version without having to pull an image. E.g.:

```
skopeo inspect docker://docker.io/openshift/jenkins-2-centos7:v3.9
```

Result:
```
{
    "Name": "docker.io/openshift/jenkins-2-centos7",
    "Digest": "sha256:161060fc6eb05adb62ef5268b0c1084d0743bfa9ef5e7c9aad007550f9e9e862",
    "RepoTags": [
        "3.6.0",
        "3.7.0",
        "latest",
        "v3.6",
        "v3.7",
        "v3.9"
    ],
    "Created": "2018-01-22T23:47:28.415547629Z",
    "DockerVersion": "1.12.6",
    "Labels": {
        "build-date": "20180107",
        "io.k8s.description": "OpenShift Origin is a platform for developing, building, and deploying containerized applications.",
        "io.k8s.display-name": "OpenShift Origin Application Platform",
        "io.openshift.builder-version": "6d8a798",
        "io.openshift.s2i.scripts-url": "image:///usr/libexec/s2i",
        "io.openshift.tags": "openshift,core",
        "k8s.io.description": "Jenkins is a continuous integration server",
        "k8s.io.display-name": "Jenkins 2",
        "license": "GPLv2",
        "name": "CentOS Base Image",
        "openshift.io.expose-services": "8080:http",
        "openshift.io.tags": "jenkins,jenkins2,ci",
        "vendor": "CentOS"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:af4b0a2388c69010cf675c050e51cb1fabbdf2303f955c31805b280324fd4523",
        "sha256:c7d156cdc7ba1611c48e6a7ea40f5bffb2d4b177777f6f63f7b085ee89575107",
        "sha256:365f9c6d2d7b5c36f70af4eb9b1c3a0726541cce30ce3cc74f7cb9943e03eb55",
        "sha256:0dcb16a1e771a03729845febcaa2057cf641d7934b7c6db704c54a0d7a46b339",
        "sha256:ab07766ca0767cd8385dedaeef942c7389fef2a27b8e69fd1a289ffd8f353ab1",
        "sha256:693acc32f4a51d6304a2a97ac8899462452587dd04ac9216bbe3a38208501203",
        "sha256:f477015332501b5d4625f5c26fa74dc06421a620de4c54fa74334509f10e1e04",
        "sha256:7d77f74f0100a3857cf0745ce1511e84304d1393147027c069dddb692bb9397b",
        "sha256:774ea521ada31bfa5d69e633fb8e27f32450594adbe8183a016a06953eeff8e1",
        "sha256:8c683f832bf0e3a8cac119eff72a925a5ac7c0f3ba41762ca53ede2d8da6a2e5"
    ]
}
```

**Comment by gabemontero** [comment]
hey @grdryn thanks for the suggestion, but the crux for us having to remember to update the label when we change the rpms used for installing jenkins, which are obtained differently for centos and rhel

the labels used to be more precise and we backed off of that cause inconsistencies would manifest

also, for centos, the precise version is part the jenkins rpm installed, which is obtainable from the dockerfile .... see https://github.com/openshift/jenkins/blob/master/2/Dockerfile#L37

and for rhel, most customers are more comfortable using the rpm related commands and repos for version checks 

so we are going to stop at what that last pull provided
