### ISSUE TITLE
New Jenkins LTS patch release available: 2.89.3

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#487]
There don't appear to be any security fixes, but there are a couple of bug fixes and enhancements. See https://jenkins.io/changelog-stable/ for more details.

**Comment by gabemontero** [comment]
OK trying out our new internal ci process.... request to update the rhel image:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/9/
