### ISSUE TITLE
Plugins installation issue

### ISSUE THREAD

**Issue by victorvoronin** [openshift/jenkins#488]
Some plugins look strange after installation.
Steps to reproduce:
1. Run container with host folder:
docker run -it -e JENKINS_PASSWORD=password -v /tmp/jenkins:/var/lib/jenkins openshift/jenkins-2-centos7
2. After container started, stop it with "Ctrl-C"
3. Look at plugins folder:
find /tmp/jenkins/plugins -name webapp
Result:
/tmp/jenkins/plugins/handlebars/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/handlebars/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp
/tmp/jenkins/plugins/momentjs/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp

Expected result:
empty output after find
and:
ls /tmp/Jenkins/plugins/momentjs/
META-INF  WEB-INF  jsmodules

Conclusion - plugins installation doesn't work as expected

**Comment by bparees** [comment]
that appears to be an issue w/ the handlebars plugin zip.  Specifically the 1.1 version:
https://updates.jenkins.io/download/plugins/handlebars/1.1/handlebars.hpi

```
$ wget http://ftp-chi.osuosl.org/pub/jenkins/plugins/handlebars/1.1/handlebars.hpi
--2018-01-22 09:44:19--  http://ftp-chi.osuosl.org/pub/jenkins/plugins/handlebars/1.1/handlebars.hpi
Resolving ftp-chi.osuosl.org (ftp-chi.osuosl.org)... 2600:3402:200:227::2, 64.50.236.52
Connecting to ftp-chi.osuosl.org (ftp-chi.osuosl.org)|2600:3402:200:227::2|:80... failed: No route to host.
Connecting to ftp-chi.osuosl.org (ftp-chi.osuosl.org)|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2138913 (2.0M) [application/vnd.hp-hpid]
Saving to: ‘handlebars.hpi’

handlebars.hpi         100%[==========================>]   2.04M  6.58MB/s    in 0.3s    

2018-01-22 09:44:20 (6.58 MB/s) - ‘handlebars.hpi’ saved [2138913/2138913]

t$ unzip handlebars.hpi
Archive:  handlebars.hpi
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF    
   creating: jsmodules/
   creating: WEB-INF/
   creating: WEB-INF/lib/
   creating: webapp/
   creating: webapp/jsmodules/
   creating: webapp/webapp/
   creating: webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/
   creating: webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/
   creating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/
  inflating: jsmodules/handlebars3.js  
  inflating: WEB-INF/lib/handlebars.jar  
  inflating: WEB-INF/licenses.xml    
  inflating: webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
  inflating: webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/webapp/jsmodules/handlebars3.js  
   creating: META-INF/maven/
   creating: META-INF/maven/org.jenkins-ci.ui/
   creating: META-INF/maven/org.jenkins-ci.ui/handlebars/
  inflating: META-INF/maven/org.jenkins-ci.ui/handlebars/pom.xml  
  inflating: META-INF/maven/org.jenkins-ci.ui/handlebars/pom.properties  
```

**Comment by bparees** [comment]
(we don't explicitly install this plugin, it's picked up as a dependency, so we can't simply move to the 1.1.1 version which does not appear to have this packaging problem).

**Comment by gabemontero** [comment]
@bparees - we *could* explicitly install it until the dependency bumps its dependency version on handlebars ... this would be similar to our adjustments for security advisories

**Comment by gabemontero** [comment]
I'm probably due to examine those explicit security advisory plugin installs as well, see if they've been picked up

**Comment by victorvoronin** [comment]
And what about momentjs?

**Comment by bparees** [comment]
@victorvoronin also appears to be a packaging issue.

**Comment by gabemontero** [comment]
Ahh... there are actually disclaimers on both the handlebars and momentjs plugins to not install it directly - https://plugins.jenkins.io/handlebars and https://wiki.jenkins.io/display/JENKINS/Moment.js

That is different than the security advisory updates I mentioned previously....there were no warnings about installing those explicitly

So yeah per the @bparees original assessment we'll defer to upstream jenkins fixing / updating their dependencies
