### ISSUE TITLE
jenkins successful test logs are not clean

### ISSUE THREAD

**Issue by bparees** [openshift/jenkins#50]
Jenkins "successful" logs contain some scary statements:

```
Dumping logs for cb827cbbd0dadd8bf4c9fe54b357460e4793fd271a1ee2fb986ccb63ea2e1ad3
+ [[ 143 != \0 ]]
+ docker logs cb827cbbd0dadd8bf4c9fe54b357460e4793fd271a1ee2fb986ccb63ea2e1ad3
Detected password change, updating Jenkins configuration ...
Processing Jenkins Kubernetes configuration (/var/lib/jenkins/config.xml.tpl) ...
Running from: /usr/lib/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
cat: /run/secrets/kubernetes.io/serviceaccount/token: No such file or directory
/usr/local/bin/jenkins-common.sh: line 51: /opt/openshift/passwd: Permission denied
NWRAP_ERROR(18) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(18) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
```

This one in particular is worrisome:
`/usr/local/bin/jenkins-common.sh: line 51: /opt/openshift/passwd: Permission denied`

As seen here:
https://ci.openshift.redhat.com/jenkins/job/jenkins/120/console

**Comment by bparees** [comment]
(near as i can tell password changing is still working since we have an explicit test for that, but the nss wrapper stuff might not be working correctly)

**Comment by mfojtik** [comment]
token error is ok but the permission one worries me. I haven't seen that
error in Jenkins logs running in OpenShift. Will have a look.

**Comment by bparees** [comment]
not seeing this is current logs.

**Comment by lvthillo** [comment]
I seem to have this issue:

```
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://name@bitbucket.org/proj/repo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: NWRAP_ERROR(668) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(668) - nwrap_files_getpwuid: Error loading passwd file
NWRAP_ERROR(670) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(670) - nwrap_files_getpwuid: Error loading passwd file
```

Don't know where it comes from. I try to pull from a bitbucket repo with username/passwd

**Comment by gabemontero** [comment]
Perhaps everyone is aware, but typically in jobs I run, I see `NSS_WRAPPER_PASSWD=/opt/openshift/passwd`.

Again, maybe everyone is already aware of this, but perhaps the SCMs in question are picking up on the env var and accessing `/opt/openshift/passwd` when they shouldn't be?

**Comment by bparees** [comment]
@lvthillo can you describe your full scenario?

**Comment by lvthillo** [comment]
@bparees I'm running a persistent Jenkins container on OpenShift Origin 1.1.6. I've installed the git plugin and try to connect to my git repository on bitbucket to pull the repo into the jenkins workspace but don't work. 

```
Started by user Jenkins Admin
Building in workspace /var/lib/jenkins/jobs/build-bluepond/workspace
Cloning the remote Git repository
Cloning repository https://user@bitbucket.org/proj/repo.git
 > git init /var/lib/jenkins/jobs/build-bluepond/workspace # timeout=10
Fetching upstream changes from https://user@bitbucket.org/proj/repo.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.username user # timeout=10
 > git config --local credential.helper store --file=/tmp/git888697302351XX50360.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://user@bitbucket.org/proj/repo.git +refs/heads/*:refs/remotes/origin/*

 > git config --local --remove-section credential # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://user@bitbucket.org/proj/repo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: NWRAP_ERROR(279) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(279) - nwrap_files_getpwuid: Error loading passwd file
NWRAP_ERROR(281) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
NWRAP_ERROR(281) - nwrap_files_getpwuid: Error loading passwd file
remote: Counting objects: 4064, done.        
remote: Compressing objects:   0% (1/2090)           
remote: Compressing objects:   1% (21/2090)           
remote: Compressing objects:   2% (42/2090)           
remote: Compressing objects:   3% (63/2090)           
remote: Compressing objects:   4% (84/2090)           
remote: Compressing objects:   5% (105/2090)           
remote: Compressing objects:   6% (126/2090)           
remote: Compressing objects:   7% (147/2090)           
remote: Compressing objects:   8% (168/2090)           
remote: Compressing objects:   9% (189/2090)           
remote: Compressing objects:  10% (209/2090)           
remote: Compressing objects:  11% (230/2090)           
remote: Compressing objects:  12% (251/2090)           
remote: Compressing objects:  13% (272/2090)           
remote: Compressing objects:  14% (293/2090)       
```

**Comment by bparees** [comment]
@gabemontero that file (/opt/openshift/passwd) should always be there and nss should always be getting used (that's why we put nss in the LD_PRELOAD).

@lvthillo can you "oc rsh" into your jenkins pod and do an "ls -l /opt/openshift/passwd" and also "whoami" ?

**Comment by rafabene** [comment]
I'm also facing this issue.

**Comment by bparees** [comment]
@rafabene can you provide the information i asked for from @lvthillo then?

and confirm you're on the latest openshift/jenkins-1-centos7 image?  (or tell me which one you are on)

**Comment by rafabene** [comment]
In fact it happened with registry.access.redhat.com/openshift3/jenkins-1-rhel7:latest I just dropped my CDK environment and recreating it to see what is happening.

**Comment by rafabene** [comment]
Not only I face this issue in pod log, but when I try to execute a Jenkinsfile pipeline.

>Started by user Jenkins Admin
[Pipeline] node
Running on master in /var/lib/jenkins/jobs/Hello Microservices/workspace
[Pipeline] {
[Pipeline] stage (Git checkout)
Entering stage Git checkout
Proceeding
[Pipeline] echo
Checking out git repository
[Pipeline] git
Cloning the remote Git repository
Cloning repository https://github.com/redhat-helloworld-msa/hello
 > git init /var/lib/jenkins/jobs/Hello Microservices/workspace # timeout=10
Fetching upstream changes from https://github.com/redhat-helloworld-msa/hello
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/redhat-helloworld-msa/hello +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/redhat-helloworld-msa/hello +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
-----> SNIP
NWRAP_ERROR(141) - nwrap_files_cache_reload: Unable to open '/opt/openshift/passwd' readonly -1:No such file or directory
fatal: unable to look up current user in the passwd file: No such file or directory
Unexpected end of command stream
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:506)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1057)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline`

**Comment by bparees** [comment]
@rafabene can you "oc rsh" into your jenkins pod and do an "ls -l /opt/openshift/passwd" and also "whoami" ?

and cat the passwd file if it exists.

**Comment by rafabene** [comment]
There it goes:

> oc rsh jenkins-1-f00sy
bash-4.2$ ls -l /opt/openshift/passwd
ls: cannot access /opt/openshift/passwd: No such file or directory
bash-4.2$ ls -l /opt/openshift/
total 8
-rw-rw-r--. 1 1001 root   74 May 16 12:08 base-plugins.txt
drwxrwxr-x. 2 1001 root    6 May 19 23:21 configuration
-rwxrwxr-x. 1 1001 root 2039 May 16 12:08 password-encoder.jar
bash-4.2$ whoami
whoami: cannot find name for user ID 1001
bash-4.2$

**Comment by rafabene** [comment]
> docker run -it --rm registry.access.redhat.com/openshift3/jenkins-1-rhel7

Also allows you to see the errors.

**Comment by bparees** [comment]
this issue has been fixed but a new rhel7 image has not yet been published.  For now you'll have to use the openshift/jenkins-1-centos7 image instead, which does contain the fix.

**Comment by rafabene** [comment]
Thanks. Updated to openshift/jenkins-1-centos7 and it seems to work,

**Comment by bparees** [comment]
ok, will close this once we publish a new rhel7 image.

**Comment by sdodson** [comment]
registry.access.redhat.com/openshift3/jenkins-1-rhel7:1.651.2-4 has finally gone live and is tagged latest as well.

**Comment by bparees** [comment]
tragically that image does not appear to contain the fix because /usr/local/bin/jenkins-common.sh still contains this line:
```
envsubst < /opt/openshift/passwd.template > /opt/openshift/passwd
```

**Comment by bparees** [comment]
this was the fix for the issue:
https://github.com/openshift/jenkins/commit/20a511b8ccf71a8ebd80519440403e530ccb6337

**Comment by maci0** [comment]
same issue here with
`registry.access.redhat.com/openshift3/jenkins-1-rhel7            latest              8fe7d109f5bd        2 weeks ago         556.9 MB`

**Comment by bparees** [comment]
@maci0 yeah see my 2 comments above.  fix has not been pushed yet, but you can use the centos image for now if you need a workaround.

**Comment by bparees** [comment]
the corrected image has now been pushed, thanks for your patience.
