### ISSUE TITLE
Check if we're labelling built Jenkins images wrongly

### ISSUE THREAD

**Issue by jim-minter** [openshift/jenkins#507]
for example: shouldn't https://github.com/openshift/jenkins/blob/openshift-3.7/2/Dockerfile.rhel7#L31 read `version="3.7" \` ?

**Comment by gabemontero** [comment]
@bparees do we need to worry about the 3.8 branch ? ... i'm guessing no, but wanted to double check

**Comment by bparees** [comment]
@gabemontero no, don't worry about 3.8.
