### ISSUE TITLE
New Jenkins LTS patch release available: 2.89.4

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#509]
Info: https://jenkins.io/security/advisory/2018-02-14/

**Comment by gabemontero** [comment]
thanks @grdryn 

I'll also pull in the various plugin updates from the Jan 22, Feb 5, and Feb 26 security advisories as well while I'm in here building an image and running regression

@bparees fyi ^^

**Comment by gabemontero** [comment]
Job to update rpm available for openshift-jenkins rhel builds:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/10/

**Comment by gabemontero** [comment]
The rhel update in dist-git for the new jenkins lts is now at http://pkgs.devel.redhat.com/cgit/rpms/jenkins/?h=rhaos-3.9-rhel-7

**Comment by grdryn** [comment]
Thanks for the quick turnaround! :)
