### ISSUE TITLE
can not perform oc operation in RHEL/Jenkins image

### ISSUE THREAD

**Issue by Yashu5** [openshift/jenkins#51]
Hi,

I have created a pod in openshift enterprise using "oc new-app registry.access.redhat.com/openshift3/jenkins-1-rhel7" , I can access jenkins console fine.

But whenever I try to run "oc" commands from jenkins job,

it gives me "default cluster has no server defined"

There in no such issue though with jenkins/centos image.

any thoughts??

**Comment by bparees** [comment]
are you running the sample job or your own job you've created?

if it's your own job, can you provide the commands you're running?

note that the sample job explicitly sets up an alias for oc to ensure certain arguments are passed:
```alias oc="oc -n $PROJECT --token=$AUTH_TOKEN --server=$OPENSHIFT_API_URL --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt "```

i just tested the rhel image myself and, after setting up that alias w/ a valid OPENSHIFT_API_URL value, it is working fine for me.

**Comment by Yashu5** [comment]
Hi Ben, Thanks , How do I get the AUTH_TOKEN here.

Below is the error I got while building sample job:

Started by user Jenkins Admin
Building in workspace /var/lib/jenkins/jobs/OpenShift Sample/workspace
[workspace] $ /bin/sh -xe /tmp/hudson5463768946706679320.sh
+ '[' -z pBgBeKcalFdDo_PVAYOfoK4z9el51lR1-7zIA2VrT14 ']'
+ '[' -e /run/secrets/kubernetes.io/serviceaccount/ca.crt ']'
+ alias 'oc=oc -n test --token=pBgBeKcaAYOfoK4z9el51lR1-7zIA2VrT14 --server=https://myhost:8443/ --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt '
++ oc -n test --token=pBgBeKcalFdDo_PVl51lR1-7zIA2VrT14 --server=https://myhost:8443/ --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt get service frontend -t '{{.spec.clusterIP}}{{":"}}{{ $a:= index .spec.ports 0 }}{{$a.port}}'
error: specifying a root certificates file with the insecure flag is not allowed
+ TEST_ENDPOINT=
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by bparees** [comment]
If you look at the sample jenkins job, you can see that it gets the auth token from the secret mounted into the pod:
```
AUTH_TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`
```

based on your output it was picked up correctly, as was the ca.crt.

@liggitt any theories on why oc would be reporting this error?  I don't see where the insecure flag is being set...

@Yashu5 can you confirm you've pulled the latest registry.access.redhat.com/openshift3/jenkins-1-rhel7 image, just so we're not debugging something stale?

**Comment by liggitt** [comment]
do you have an existing $KUBECONFIG or ~/.kube/config file present? If so, that is merged with any options you provide on the command line, and could be setting an insecure=true config value

**Comment by bparees** [comment]
there shouldn't be on in the jenkins image, at least not by default, so unless @Yashu5 rsh'd into the jenkins image and performed an oc login or something....

**Comment by liggitt** [comment]
Only relevant thing I see is https://github.com/openshift/jenkins/blob/013b2dfe34243d3ffec0e981f8aaeeb94e0b084a/1/test/testjob.xml#L75-L79

**Comment by bparees** [comment]
yeah based on the output provided, we're not in the --insecure path.

**Comment by liggitt** [comment]
the output of `oc config view` would be helpful to see

**Comment by Yashu5** [comment]
Hi ben and liggitt, thanks for responses here, I am using latest version of jenkins RHEL image only.

dont know what could be the issue, for temporary purpose i logged into the pod and did "oc login", after this I can run the job without any issue.

but I do not want to do  that for my other jenkins server running in different environment. Any help would be appreciated 


as asked by liggit below is output of "oc config view "

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.108.211.98:8443
  name: 10-18-2-00:8443
- cluster:
    certificate-authority-data: REDACTED
    server: https://50.22.250.152:8443
  name: 53-2-2-100:8443
contexts:
- context:
    cluster: 10-18-2-00:8443
    namespace: default
    user: system:admin/53-2-2-100:8443
  name: default/10-18-2-00:8443/system:admin
- context:
    cluster: 53-2-2-100:8443
    namespace: default
    user: system:admin/53-2-2-100:8443
  name: default/53-2-2-100:8443/system:admin
- context:
    cluster: 53-2-2-100:8443
    namespace: openshift-infra
    user: system:admin/53-2-2-100:8443
  name: openshift-infra/53-2-2-100:8443/system:admin
- context:
    cluster: 53-2-2-100:8443
    namespace: openshift
    user: system:admin/53-2-2-100:8443
  name: openshift/53-2-2-100:8443/system:admin
- context:
    cluster: 53-2-2-100:8443
    namespace: test
    user: system:admin/53-2-2-100:8443
  name: test/53-2-2-100:8443/system:admin
- context:
    cluster: 53-2-2-100:8443
    namespace: test
    user: testuser/53-2-2-100:8443
  name: test/53-2-2-100:8443/testuser
current-context: test/53-2-2-100:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/53-2-2-100:8443
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: testuser/53-2-2-100:8443
  user: {}

**Comment by bparees** [comment]
can you create a new jenkins job that just runs "oc config view", then does the aliasing the sample job does, then runs "oc config view" again, per @liggitt 's request?

**Comment by bparees** [comment]
closing based on lack of response, if you can reproduce this on a current image and want to revisit it, please reopen.
