### ISSUE TITLE
Set java heap for Maven in jenkins-slave-maven

### ISSUE THREAD

**Issue by bszeti** [openshift/jenkins#519]
Though the jenkins-slave-base image has a built in script to set max heap to half of the container memory (can be modified via env var CONTAINER_HEAP_PERCENT=0.50), it only applies to the Jenkins agent java process. In case of a Maven build we have important additional java processes running:
- The mvn command itself is a java tool
- The maven-surefire-plugin executes the unit tests in a forked JVM by default
At the end of the day we’ll have three java processes running at the same time in the container and it’s important to estimate their memory usage to avoid unexpectedly killed pods.

The heap should be automatically set for these java processes too.

**Current workaround:**
- Set JAVA_OPTS for the Jenkins agent. Its heap is set automatically as mentioned above, but we definitely shouldn’t let the agent have such a big heap. Memory is needed for the other two JVMs.
- Set MAVEN_OPTS to customize this java process.
- The JVM spawned by surefire for the unit tests can be customized by the argLine maven property. It can be set in the pom.xml, in a profile in settings.xml or simply by adding -DargLine=… to MAVEN_OPTS
Here is an example how to set these environment variables for the maven agent container:
JAVA_OPTS=-Xms64m -Xmx64m
MAVEN_OPTS=-Xms128m -Xmx128m -DargLine=${env.SUREFIRE_OPTS}
SUREFIRE_OPTS=-Xms256m -Xmx256m
These numbers worked for us with 1024Mi agent container memory limit building and running unit tests for a SpringBoot app.

**Comment by bparees** [comment]
We are setting JAVA_TOOL_OPTIONS which should be picked up by maven, this tells the JVM to tune itself to the container's memory limits:
https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L66-L71

There's nothing we can do about the processes your maven process is spawning, at that point you need to do your own tuning of the processes (including maven) being launched within the slave container.

@jim-minter i thought we also added logic to set MAVEN_OPTS, did we forgo that in lieu of JAVA_TOOL_OPTIONS?

**Comment by bszeti** [comment]
The JAVA_TOOL_OPTIONS helps some as it has -XX:+UseCGroupMemoryLimitForHeap (not in branch v3.7 I'm using), but the image is still risky to be used for maven builds (with unit tests) out of the box. As I understand the max heap is set as below by default:
- Jnlp agent: 1/2 memory
- Maven: 1/4 memory
- Surefire: 1/4 memory
it's only the heap... Memory usage still can go above the cgroup max allowed and Openshift will kill the pod.

it would be great to have a default config that works with 0.5-2GB container limit, like:
For agent: CONTAINER_HEAP_PERCENT=0.10
For Maven and Surefire: JAVA_TOOL_OPTIONS=-Xmx[0.20 * memory]

**Comment by bparees** [comment]
@bszeti we went through an extensive study of how to tune memory in a maven slave.  The conclusion we reached is that the memory usage patterns of the workloads are extremely difficult to predict and provide a useful default for.  The current settings represent our best guess at something "reasonable" while recognizing that basically anyone trying to use these images needs to do their own thinking+tuning to get an ideal value, in part of the reasons you noted (namely, the fact that processes may be forked and not all usage takes the form of java heap).

This is discussed some here:
https://docs.openshift.org/latest/using_images/other_images/jenkins_slaves.html#memory-requirements

and resulted in the introduction of a number of env variables to allow end users to fine tune the behavior:
https://docs.openshift.org/latest/using_images/other_images/jenkins_slaves.html#environment-variables

**Comment by jim-minter** [comment]
> i thought we also added logic to set MAVEN_OPTS, did we forgo that in lieu of JAVA_TOOL_OPTIONS?

@bparees no, I just went for JAVA_TOOL_OPTIONS.  The kicker was Gradle in this case - the equivalent Gradle env var handles the main gradle JVM process but not the test JVM process, hence wasn't adequate to handle a simple Gradle build workload including a unit test.

**Comment by bszeti** [comment]
@bparees Thanks for pointing out this page about the environment variables. Clearly there have been some enhancements since OCP v3.7. If the JVMs calculate default max heap by cgroup memory then it's probably enough for users to set a low (0.1) CONTAINER_HEAP_PERCENT, and the image probably will work for Maven builds (with the default one forked surefire JVM).

I see these changes in openshift/jenkins-slave-maven-centos7:v3.9 on docker hub. Do you know when these changes are expected to be added to jenkins-slave-rhel7-base?

**Comment by gabemontero** [comment]
On Mon, Mar 5, 2018 at 11:09 AM, bszeti <notifications@github.com> wrote:

> @bparees <https://github.com/bparees> Thanks for pointing out this page
> about the environment variables. Clearly there have been some enhancements
> since OCP v3.7. If the JVMs calculate default max heap by cgroup memory
> then it's probably enough for users to set a low (0.1)
> CONTAINER_HEAP_PERCENT, and the image probably will work for Maven builds
> (with the default one forked surefire JVM).
>
> I see these changes in openshift/jenkins-slave-maven-centos7:v3.9 on
> docker hub. Do you know when these changes are expected to be added to
> jenkins-slave-rhel7-base?
>
Will be available when 3.9 ships, which is suppose to be this month
