### ISSUE TITLE
Support server authentication credentials in jenkins-slave-maven

### ISSUE THREAD

**Issue by bszeti** [openshift/jenkins#520]
The MAVEN_MIRROR_URL can be used to set a maven mirror in settings.xml.
We should also have a similar solution for authentication. Maybe just simply have something like this in settings.xml:
```
<servers>
  <server>
   <id>mirror</id>
   <username>${env.MAVEN_SERVER_USERNAME}</username>
   <password>${env.MAVEN_SERVER_PASSWORD}</password>
  </server>
 </servers>
```

**Comment by bparees** [comment]
We are not interested in getting into owning extensive customization of the maven config file. If the existing one is insufficient for your needs, I suggest replacing it with one that is.
