### ISSUE TITLE
S2I build fails if init.groovy.d/ present

### ISSUE THREAD

**Issue by jlebon** [openshift/jenkins#528]
It looks like #440 might have caused a regression on client builds that want to bake in `init.groovy.d/` scripts:

```
---> Installing new Jenkins configuration ...
mv: cannot move ‘/tmp/tmp.isnFJKrzxzjenkins/configuration/init.groovy.d’ to ‘/opt/openshift/configuration/init.groovy.d’: Directory not empty
error: build error: non-zero (13) exit code from openshift/jenkins-2-centos7@sha256:8e5a8cfb470ac744b903cc2fc6607a78d3d98b7ee6af5e718a39f7730c6d9663
```

**Comment by bparees** [comment]
@gabemontero please revert this out of the 3.9 branch while we sort this out.  it's not needed for 3.9 anyway (the template changes are sufficient).

**Comment by gabemontero** [comment]
sure ... while users laying claim to the init.groovy file is speculative IMO, either in the top level dir or init.groovy.do subdir, the time needed to sort through that debate conflicts with our 3.9 timetable.

**Comment by jlebon** [comment]
I posted an easy fix for this in #529. Though I'm fine with reverting as well. Ideally, we would have "merge" semantics there.

**Comment by gabemontero** [comment]
On Tue, Mar 6, 2018 at 3:05 PM, Jonathan Lebon <notifications@github.com>
wrote:

> I posted an easy fix for this in #529
> <https://github.com/openshift/jenkins/pull/529>. Though I'm fine with
> reverting as well. Ideally, we would have "merge" semantics there.
>
Yep saw that - thanks.  That said, in theory there might be users who
assumed they could lay claim to the other file as well.
We'll want to give the issue proper consideration.

Thanks for the quick heads up by the way ;-)

**Comment by jlebon** [comment]
> Ideally, we would have "merge" semantics there.

I just updated #529 to do this.

**Comment by gabemontero** [comment]
On Tue, Mar 6, 2018 at 3:10 PM, Jonathan Lebon <notifications@github.com>
wrote:

> Ideally, we would have "merge" semantics there.
>
> I just updated #529 <https://github.com/openshift/jenkins/pull/529> to do
> this.
>
OK cool.  We'll certainly cross reference with that when we revisit this.
Thanks again.

**Comment by gabemontero** [comment]
This has been backed out with the recent centos image updates and is part of 3.9 rhel

I'll see about some form of what @jlebon proposed or some augmentation of that as part of the continuing resolution efforts around slow login ... place in the beginning of our 3.10 cycle so it can get more soaking / review

**Comment by jlebon** [comment]
Hmm, this is still an issue in the latest image:

```
---> Installing new Jenkins configuration ...
mv: cannot move ‘/tmp/tmp.jLJdqLB7DHjenkins/configuration/init.groovy.d’ to ‘/opt/openshift/configuration/init.groovy.d’: Directory not empty
error: build error: non-zero (13) exit code from openshift/jenkins-2-centos7@sha256:479d1df7a402d57ece188a90f23cd08accbeca1cfc053810f4a7f478c8ca3155
```

@gabemontero Have you had a chance to look at https://github.com/openshift/jenkins/pull/529?

Also a conceptual question: what's the correct way of using the v3.9 version of the S2I image? I'm mostly using the `oc cluster up` workflow, which gets me set up with the default `openshift/jenkins` imagestream. But it seems like the `2` tag just follows the `latest` tag of `jenkins-2-centos7` in the Docker Hub. Shouldn't that be versioned to the OpenShift version? Right now, I'm working around this by adding a new `2-v3.9` tag in the imagestream definition to track `v3.9` in the Hub.

**Comment by bparees** [comment]
correct, we introduced version based tagging in 3.7.

**Comment by gabemontero** [comment]
@jlebon - hey, yes, I had looked at https://github.com/openshift/jenkins/pull/529 previously, but the mv failing to replace an existing dir appears to have been lost in the shuffle when I reintroduced our use of init groovy scripts after we had shipped 3.9 (reverting the introduction of an init groovy fix was the original fix for your issue as part of getting our 3.9 image out the door).

So it was fixed, then re-broke.

We'll sort out some details on our end and either merge your PR or craft some approximation.

Thanks

**Comment by gabemontero** [comment]
I'm wondering if we need a more generic solution than https://github.com/openshift/jenkins/pull/529 in that a conflict with other files might pop up in the future.

After some testing, I'm inclined to replace our use of `mv` here with `rsync`.  

Did a series of experiments with `rsync -av <src dir>/ <dest dir>`

Note, the `/` after <src dir> is intended.

And my observations:

- it exists in our jenkins image already
- it will tolerate the presence of the init.d dir if it is there
- it will leave prexisting files in the destination that do not exist in the source ... and note, specifically with this init.groovy stuff, we now use a "non-default" file name for the groovy file that is specific to our needs
- it will still overwrite existing files (which is consistent with the old behavior with `mv`)

@bparees @jlebon any thoughts?

**Comment by bparees** [comment]
> @bparees @jlebon any thoughts?

what is/was the problem w/ using mv, which would also tolerate existing files and overwrite duplicated filenames?

**Comment by bparees** [comment]
> It in fact does not tolerate it. 

it tolerates existing files, doesn't tolerate existing dirs.  I'm not clear on what we actually expect users to be providing in the "s2i" dir?

if we were doing:
`mv userprovided/init.d/* system/init.d`

I would expect things to be ok.

`mv userprovided/* system/` would be(is) problematic (where both `userprovided` and `system` contain an init.d dir)

So I guess I need a little more background on what we expect to be in the target dir, and what we expect/intend/need to allow users to provide in their dir that we copy/move from.

**Comment by gabemontero** [comment]
On Wed, Apr 4, 2018 at 1:32 PM, Ben Parees <notifications@github.com> wrote:

> It in fact does not tolerate it.
>
> it tolerates existing files, doesn't tolerate existing dirs. I'm not clear
> on what we actually expect users to be providing in the "s2i" dir?
>
Yes, not tolerating existing dirs is more precise, and the key point here.

`rsync` tolerates both existing dirs and files.

the `s2i` was from @jlebon 's PR, where her proposed that we change our
image to store the groovy init files in directory that ended in `.s2i`
and then copy from there to the init.groovy.d dir
so as to not conflict with existing users who as part of extending the
jenkins image are decided to add such scripts

I'm advocating to not change our path, but by leveraging `rsync`, we can
handle the presence of those dirs.... any any future dirs that might arise.

if we were doing:
> mv userprovided/init.d/* system/init.d
>
> I would expect things to be ok.
>
> mv userprovided/* system/ would be(is) problematic (where both
> userprovided and system contain an init.d dir)
>
> So I guess I need a little more background on what we expect to be in the
> target dir, and what we expect/intend/need to allow users to provide in
> their dir that we copy/move from.
>
Was the above sufficient context ?

**Comment by bparees** [comment]
ok well after a foray into our assemble+run scripts i understand now the issue is w/ the conflict between /opt/openshift/configuration and any user provided "configuration" tree (which may contain the same subdirs as /opt/openshift/configuration.  In particular init.groovy.d.  "jobs" would also be a problematic dir, except we explicitly remove the existing "jobs" dir in the target configuration tree before copying the user supplied content).

I see a few paths:
1) rsync merge as you proposed

2) cp -r instead of mv, followed by an rm -rf of the source path (I believe this will merge dir contents)

3) should we be wiping out the "image provided" configuration entirely if someone provides their own configuration dir?  This is probably a change in behavior we can't make at this point, but i do wonder if it's what we should have done originally:  if you want to provide the config, you own the entire config (the argument against it was to allow people to easily contribute job definitions under the config dir, without overriding the image's config.xml)

**Comment by jlebon** [comment]
Yeah, `rsync -r` semantics makes sense to me. Keeping the previous behaviour for `jobs/` would require a special-case, though it seems like minimal baggage to carry.

> should we be wiping out the "image provided" configuration entirely if someone provides their own configuration dir?

I wouldn't want that I think. E.g. this would mean that people would have to carry the Kubernetes cloud config in their own builds and keep up with upstream, right? It'd also make fixes like the slow login issue much harder to implement.

**Comment by bparees** [comment]
> I wouldn't want that I think. E.g. this would mean that people would have to carry the Kubernetes cloud config in their own builds and keep up with upstream, right? It'd also make fixes like the slow login issue much harder to implement.

yeah i think i talked myself out of it.

> Yeah, rsync -r semantics makes sense to me. Keeping the previous behaviour for jobs/ would require a special-case, though it seems like minimal baggage to carry.

just requires us to keep the existing logic that removes the jobs dir if the user is supplying one:
https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/assemble#L30-L33

**Comment by bparees** [comment]
@gabemontero i guess so :)
