### ISSUE TITLE
Update Slave to Node.js 8

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins#533]
The current slave is currently two major versions behind. Happy to provide a PR for centos and rhel if welcome

**Comment by gabemontero** [comment]
On Tue, Mar 6, 2018 at 10:08 PM Justin Holmes <notifications@github.com>
wrote:

> The current slave is currently two major versions behind. Happy to provide
> a PR for centos and rhel if welcone
>
we are actually doing this change now though we are not just changing the
existing images but rather creating new ones and deprecating the existing
ones

We have some process related reqs driving all this

I can try and remember to tag you in our PR if you like once we get things
going I can

**Comment by bparees** [comment]
as @gabemontero notes, we're working on this now..the trello card is here:
https://trello.com/c/YQm7osws

closing this PR in deference to tracking it in trello.

**Comment by arnaud-deprez** [comment]
Hi @bparees @gabemontero,

Is that possible to have more information about these images change ? 
Unfortunately, I loose my access to RedHat bugzilla and I can't figure out how to get it back without involving the huge/slow process in my company.

I would like to submit a change for npm agent/slave.

Regards,

**Comment by bparees** [comment]
> Is that possible to have more information about these images change ?

what do you want to know?

> I would like to submit a change for npm agent/slave.

what sort of change?

**Comment by arnaud-deprez** [comment]
@bparees I don't see much difference between the old slave-nodejs and the new agent-nodejs-8 except the version and the name of the image so I'm wondering why we deprecated old image for these new images or I missed something else.

I would like to add [yarn](https://yarnpkg.com/) on top of nodejs agent/slave as we did for gradle as it becomes more and more used as an alternative to npm.

**Comment by gabemontero** [comment]
On Tue, Mar 13, 2018 at 9:05 AM, Arnaud Deprez <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> I don't see much difference between
> the old slave-nodejs and the new agent-nodejs-8 except the version and the
> name of the image so I'm wondering why we deprecated old image for these
> new images or I missed something else.
>
We've been informed the maven/nodejs versions in those original images are
going out of service May 2018.  This was the reason
for deprecation.  And reminder, we have wiggle room wrt marking an image
deprecated / EOL vs. removing said image from the redhat
registry.  We'll manage those distinctions as all this gets consumed by
users.

> I would like to add yarn <https://yarnpkg.com/> on top of nodejs
> agent/slave as we did for gradle as it becomes more and more used as an
> alternative to npm.
>
Open a separate issue or supply a PR and based on the mechanics (RPMs
available, etc.) we can go from there.

**Comment by arnaud-deprez** [comment]
Alright, thanks for the reply

**Comment by stujb** [comment]
Are new nodejs 8 jenkins slave images available from the redhat registry ? If so can you advise of the image name ?

**Comment by gabemontero** [comment]
It will be available at the redhat registry when v3.10 of OpenShift GA's.  The current target for that is July 2018.
