### ISSUE TITLE
Pull agent images from the cluster's internal registry

### ISSUE THREAD

**Issue by ppalaga** [openshift/jenkins#549]
I'd like to run Jenkins Pipelines in Minishift even if there is bad or no internet access (think of a conference).

The master container and the pipeline start well offline, but the maven agent cannot be started because the image cannot be pulled.

```
oc get events
...
Pod                     spec.containers{jnlp}                            Warning   Failed                           kubelet, localhost            Failed to pull image "docker.io/openshift/jenkins-agent-maven-35-centos7:v3.10": rpc error: code = 2 desc = Error while pulling image: Get https://index.docker.io/v1/repositories/openshift/jenkins-agent-m
....
```

The image is defined in `/var/lib/jenkins/config.xml`

```
<image>docker.io/openshift/jenkins-agent-maven-35-centos7:v3.10</image>
```

Could this perhaps be changed so that the image is pulled from the cluster's internal repo so that pipelines work also when the cluster has no access to the internet?

**Comment by gabemontero** [comment]
On Sun, Mar 18, 2018 at 1:58 PM Peter Palaga <notifications@github.com>
wrote:

> I'd like to run Jenkins Pipelines in Minishift even if there is bad or no
> internet access (think of a conference).
>
> The master container and the pipeline start well offline, but the maven
> agent cannot be started because the image cannot be pulled.
>
> oc get events
> ...
> Pod                     spec.containers{jnlp}                            Warning   Failed                           kubelet, localhost            Failed to pull image "docker.io/openshift/jenkins-agent-maven-35-centos7:v3.10": rpc error: code = 2 desc = Error while pulling image: Get https://index.docker.io/v1/repositories/openshift/jenkins-agent-m
> ....
>
> The image is defined in /var/lib/jenkins/config.xml
>
> <image>docker.io/openshift/jenkins-agent-maven-35-centos7:v3.10</image>
>
> Could this perhaps be changed so that the image is pulled from the
> cluster's internal repo so that pipelines work also when the cluster has no
> access to the internet?
>
you can manually change the pod template config on the jenkins console to
use the image pull policy you are asking for

**Comment by ppalaga** [comment]
Thanks for the hint, @gabemontero ! I tried it an it worked. Do you happen to know of some simple way to do this from a script using e.g. `oc rsh`?

**Comment by gabemontero** [comment]
A "simple" way ... not really unfortunately
You could
a) figure out the rest invocation against jenkins, including the post data, for changing this config vaule and do it via a curl ... does not sound simple to me 
b) extend the image and change https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L95 to the value you want
c) or sure, `oc rsh` into jenkins, sed/awk etc. the `/var/lib/jenkins/config.xml`, change the field in question ... you might need to restart jenkins via it rest api to pick it up

b) would be the "recommended" way all things being equal, and since you are not pulling the image from anywhere, providing your own image might be tolerable for you

**Comment by bparees** [comment]
another option would be to ignore the pre-defined podtemplates and supply your own pod template definition via one of the mechanisms described here:
https://docs.openshift.org/latest/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in

**Comment by ppalaga** [comment]
Thanks @bparees, the ConfigMap option looks very promising! If it works, I think this issue can be closed.

**Comment by gabemontero** [comment]
ok we'll close and you can reopen if you need some more help thanks
