### ISSUE TITLE
Execute bit set on /etc/passwd 

### ISSUE THREAD

**Issue by sthaha** [openshift/jenkins#557]
I see that https://github.com/openshift/jenkins/blob/3c0b6e955eeff983ef36e4f11062351e3039411b/2/Dockerfile#L54 sets execute bit on `passwd` which should actually be `664`. Is that a typo ?

I tried setting `644` which is usually the case with `passwd` files but found that `run` script fails when it executes `generate_passwd_file`

**Comment by bparees** [comment]
yes i think it should be 664.  Group permissions are needed to allow us to modify the file as non-root, but execute should not be needed.

**Comment by gabemontero** [comment]
was able to validate locally both starting up the image via `docker run` and logging in, as well as bringing up the image in an openshift pod

about to submit PR
