### ISSUE TITLE
Slave pods are getting created but not able to process builds

### ISSUE THREAD

**Issue by rcsrao** [openshift/jenkins#563]
I am using Openshiftv3.7 and able run builds within matser but on dynamic slaves by kubernetes.

9:33:29 AM | Normal | Killing | Killing container with id docker://jnlp:Need to kill Pod
-- | -- | -- | --
9:32:45 AM | Normal | Started | Started container
9:32:45 AM | Normal | Created | Created container
9:32:45 AM | Normal | Pulled | Container image "registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:v3.7" already present on machine
9:32:43 AM | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "default-token-gxms4"
9:32:43 AM | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "workspace-volume"
9:32:43 AM | Normal | Scheduled | Successfully assigned nodejs-rkxv4 to xxxxxxxxx.com

Kubernetes Plugin Configs:

Name: openshift
Kubernetes URL: https://xxxxx:443
Secret Key: xxxxx
Namespace: jenkins-dev
Test Connection: Success
 Jenkins URL:
Jenkins Tunnel: 

Kebernetes Pod Template:
Name: nodejs
Namespace:
lables: nodejs
usage: Use this node as much as possible
The name of the pod template to inherit from:

Container Template:
Name: jnlp
Docker image: registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:v3.7
Working directory: /tmp
Command to run: /bin/sh -c
Aruguments: cat
Allocate pseudo-tty: yes

Please help.

**Comment by rcsrao** [comment]
Any help please???

**Comment by bparees** [comment]
@rcsrao please provide the logs from your master jenkins pod and the slave pod that is being created.

**Comment by gabemontero** [comment]
also, the config.xml so we can verify all the details of your k8s plugin configuration

**Comment by gabemontero** [comment]
it is conceivable @rcsrao you may have to file a jira issue with the k8s pluging, but we'll verify a few things from a openshift jenkins image perspective first.

**Comment by rcsrao** [comment]
Issue has been resolved by creating a rout from Openshift and hookup the server IP with port on plugin configuration.

**Comment by lainekendall** [comment]
Could you provide some more details for the solution? I am having the exact same issue.
