### ISSUE TITLE
MAVEN_MIRROR_URL variable slave maven

### ISSUE THREAD

**Issue by dcdh** [openshift/jenkins#564]
In my pipeline, I use the maven node to checkout a project from github and build it. However, passing the MAVEN_MIRROR_URL parameter to my pipeline does not work in my build (my local nexus is not used).

Here is my complete pipeline:

```
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: helloworld-development-pipeline
  name: helloworld-development-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  serviceAccount: builder
  source:
    sourceSecret:
      name: bitbucketkey
    type: None
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus.ci.svc:8081/content/groups/public'
      jenkinsfile: |-
        try {
          timeout(time: 20, unit: 'MINUTES') {
            def brancheSelectionnee
            node("maven") {
              stage("update mirror") {
                sh "cat ~/.m2/settings.xml"
                sh "sed -i 's|<!-- ### configured mirrors ### -->|<mirror><mirrorOf>*</mirrorOf><url>http://nexus.ci.svc:8081/content/groups/public</url><id>mirror</id></mirror>|' ~/.m2/settings.xml"
                sh "cat ~/.m2/settings.xml"
              }
              stage("info") {
                sh "cat ~/.m2/settings.xml"
              }
              stage("Sélection de la branche") {
                brancheSelectionnee = input(
                  id: "selectionBranche", message: "Veuillez selectionner la branche a déployer sur l'environnement de développement", parameters: [
                  [$class: "TextParameterDefinition", defaultValue: "master", description: "Branche", name: "branche"]
                ])
              }
              stage("Build '${brancheSelectionnee}'") {
                git credentialsId: "ci-bitbucketkey", url: "git@bitbucket.org:dcdh/helloworld-openshift.git", branch: "${brancheSelectionnee}"
                sh "cd helloworld-openshift-app && mvn clean install -Pfabric8 -Dfabric8.namespace=developer"
              }
            }
            node("master") {
              stage("Deploy '${brancheSelectionnee}'") {
                openshift.withCluster() {
                  openshift.tag("developer/helloworld-app:${brancheSelectionnee}")
                }
              }
            }
          }
        } catch (err) {
           echo "in catch block"
           echo "Caught: ${err}"
           currentBuild.result = 'FAILURE'
           throw err
        }
    type: JenkinsPipeline
```

The MAVEN_MIRROR_URL parameter is not used in the master pod (so it is useless in my pipeline).

I have create this workaround to set up the nexus mirror (corresponding to my local nexus) to be used in the maven pod slave:

```
sh "sed -i 's|<!-- ### configured mirrors ### -->|<mirror><mirrorOf>*</mirrorOf><url>http://nexus.ci.svc:8081/content/groups/public</url><id>mirror</id></mirror>|' ~/.m2/settings.xml"
```

Is it a normal case or may I have missed something about using MAVEN_MIRROR_URL in pipeline ?

**Comment by bparees** [comment]
Assuming the env var is getting propagated to the jenkins slave pod, the maven settings should pick up your mirror env automatically:
https://github.com/openshift/jenkins/blob/master/slave-maven/contrib/bin/configure-slave

I'm not sure if the way you've defined the env var, it will be available to the slave pod(not just the pipeline itself) though, so it might be worth validating that first and foremost.

@gabemontero might have some tips as well on how env var propagation works.

**Comment by dcdh** [comment]
Thanks for your explanation.

**Comment by pittar** [comment]
This is incredibly annoying.  Is there an easier way to pass this variable?  We're trying to keep our OCP instance as "stock" as possible.  Passing an environment variable for MAVEN_MIRROR_URL (somehowe) seems like a much better option than having to alter the template or build our own maven slave image.

**Comment by bparees** [comment]
@gabemontero since the env var is going to be mapped to a jenkins job parameter (https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#jenkins-pipeline-strategy-environment), can't the pipeline then reference the parameter to setup the env var within the slave pod (or otherwise pass the parameter value to maven)?

**Comment by pittar** [comment]
I tried adding that to my buildconfig yesterday:
`  env:
    - name: "MAVEN_MIRROR_URL"
      value: "https://..."`

But no luck. It always tried to pull from Maven central.

If that *should* work, then I'll try again today and see if I just messed up the syntax or something.  Thanks for the quick reply.

**Comment by bparees** [comment]
I don't know that it will work just by adding the env var (@gabemontero addressed that approach above) but I think it will add a job parameter which your pipeline would then have to explicitly reference.  But @gabemontero is the expert here.

**Comment by gabemontero** [comment]
Yeah I believe you pieced it together @bparees before I got to these updates today in my post PTO queue :-)

However I have a bit of an update with good news.

The k8s plugin traditionally has not seeded the pod/container template env's with any env's from the job run.

However, with commit https://github.com/jenkinsci/kubernetes-plugin/commit/143f433295fbb1dcf42be634e1d4d739e74cd99f#diff-6758fa720d36f82a19137a65a09612bc from February of this year, they now do inject the run's env.

In which case we could use our pipeline build strategy mechanism for injecting env vars into the jenkins job run.

That commit appears to have made it into v1.2.1 of the kubernetes plugin.  As of our 3.10 rhel/centos images that are about to go out we are still shipping v1.2 of the kubernetes plugin.

However our very latest jenkins centos image is shipping at least v1.7.1, which means v3.11 should allow this.

@dcdh @pittar You could try manually bumping the k8s version in your deployments to v1.2.1 and try setting the env var either as a job param or an env var you your pipeline BC's.

Let us know how it goes ... based on the results, we could see about updating the older releases in our next errata.

**Comment by pittar** [comment]
@gabemontero , that's good news.  Unfortunately for us, 1/2 our environment is OpenShift Dedicated, so we don't have that sort of access.

Until then, I guess my best plan of attack is to try and use a configMap based template like this:
https://docs.openshift.com/container-platform/3.9/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in

Thanks for your help. I look forward to the k8s plugin and the convenience it will provide!

**Comment by bparees** [comment]
@pittar while you may not be able to control which jenkins image the default jenkins template in your cluster uses, you should be able to create your own template pointing to your own jenkins image, or update the plugin within a deployed jenkins instance.

**Comment by pittar** [comment]
Thanks @bparees .  Red Hat support sent me the following instructions (exactly what you just mentioned) and this worked fine.

The recommended approach would be to create a custom image to add your settings.xml into $JENKINS_HOME , eg:

~~
FROM registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7
COPY settings.xml /home/jenkins/.m2
~~

This image should be pushed into your project [2]. Finally, it's required to specify the path of your Jenkins Slave image on Jenkins settings. You should go to Jenkins -> Manage Jenkins -> Kubernetes -> Kubernetes Pod Template -> Container Template -> Docker image
