### ISSUE TITLE
can't trigger the pipeline from Gogs webhook 

### ISSUE THREAD

**Issue by MohamedElso** [openshift/jenkins#569]
hello,
i have this configured in my gogs for webhook
https://openshift.default.svc.cluster.local/oapi/v1/namespaces/cicd/buildconfigs/tasks-pipeline/webhooks/XPSJjqRT/generic
it created automatically but it doesn't trigger the pipeline and i got this message in test delivery in gogs
Delivery: Post https://openshift.default.svc.cluster.local/oapi/v1/namespaces/cicd/buildconfigs/tasks-pipeline/webhooks/xyz/generic: x509: certificate signed by unknown authority

i tried to change it to the url of the pipeline from openshift but didn't work also

https://master.openshift.xyz.com/oapi/v1/namespaces/cicd/buildconfigs/tasks-pipeline/webhooks/xyz/generic
it complains about certs .

anybody have an idea about how to solve this issue ?

thanks

**Comment by gabemontero** [comment]
Hi @MohamedElso 

Even though you are trying to ultimately invoke a pipeline strategy BC, based on where you are failing, you should be posting this as an issue against https://github.com/openshift/origin

From the looks of it, my first guess would be that the cert on your openshift master/nodes needs to be updated.

@bparees ptal ^^ ... am I forgetting how the flow works here ... the openshift build webhook endpoint is still the starting point for triggering pipeline strategy builds, right? .... it will do the start-build equivalent, and once the build is created, the sync plugin reads it, right?

**Comment by bparees** [comment]
> From the looks of it, my first guess would be that the cert on your openshift master/nodes needs to be updated.

or you need to provide gogs w/ the CA that signed your cluster's certs.

> @bparees ptal ^^ ... am I forgetting how the flow works here ... the openshift build webhook endpoint is still the starting point for triggering pipeline strategy builds, right? .... it will do the start-build equivalent, and once the build is created, the sync plugin reads it, right?

right.
