### ISSUE TITLE
Headless Chrome in NPM Slave

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins#570]
@gabemontero @bparees are you open to supporting headless chrome to be used for browser testing in the new https://github.com/openshift/jenkins/tree/master/agent-nodejs-8? 

@springdo - FYI

**Comment by bparees** [comment]
as long as it's not flakey/fragile i don't have any specific objections.  what sort of a test are you envisioning?

**Comment by sherl0cks** [comment]
@springdo is a bit closer to this and may have a slightly different perspective, but I suspect it will look like https://about.gitlab.com/2017/12/19/moving-to-headless-chrome/

**Comment by springdo** [comment]
@bparees - I would be running nightwatch.js tests in a headless manner as part of jenkins e2e test phase!

**Comment by gabemontero** [comment]
bump @springdo @sherl0cks - were you guys going to craft a PR for this?

**Comment by sherl0cks** [comment]
Sure can, I think we were looking for consensus that the approach would be acceptable if we did.

@springdo - lets give this a shot when time allows

**Comment by springdo** [comment]
@gabemontero , @sherl0cks  - yeah defo! we can take this on; won't be next week as we're at enablement but defo can look into it immediately afterwards!

**Comment by springdo** [comment]
@bparees @gabemontero - I am writing this PR now but trying to extend the tests with one for chrome too.... I've got golang to finally _run_ the tests but now it cannot connect to the docker deamon. I've checked and it's defo running etc. Im just wondering if this might be a Mac issue, in the way it's setup to run docker..... Have you guys seen this kinda thing before?

**Comment by bparees** [comment]
unfortunately neither of us are mac users.

**Comment by Gl4di4torRr** [comment]
Does this still need to be implemented?

**Comment by springdo** [comment]
Nah, I have it working. I was just busy last few weeks with customer work so now trying to get the testing framework to work to validate changes etc before pushing the PR. Is there any Docs for getting the testing to work? See my earlier comment....

**Comment by springdo** [comment]
PR opened @bparees / @Gl4di4torRr / @gabemontero  if any of yous wanna take a look.

**Comment by gabemontero** [comment]
Closing out based on discussion / discoveries in https://github.com/openshift/jenkins/pull/618
