### ISSUE TITLE
Jenkins Location Is Not Properly Set on Job Env Vars

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins#574]
It would be nice if the jenkins location was configured to the route used to expose it so that env vars like `JOB_DISPLAY_URL` were valid.

**Comment by sherl0cks** [comment]
So on double check, the value actually appears to be set, but `JOB_DISPLAY_URL=http://unconfigured-jenkins-location/job/my/job/url` is not properly set. Not sure what's up there, maybe it needs to be set in two places?

**Comment by gabemontero** [comment]
hey @sherl0cks 

Was previously unaware of the env var 

Some quick searching points me to the https://wiki.jenkins.io/display/JENKINS/Display+URL+API+Plugin plugin

Is that one you happen to be using?

**Comment by sherl0cks** [comment]
Looks like it you got it @gnufied . I was unaware it was a plugin. I'm currently doing a string replace on that env var with the contents of `oc get route jenkins` in Jenkinsfile, but it would be nice if the env vars were set and did require it.

**Comment by gabemontero** [comment]
Opened https://trello.com/c/SIJZ95Cl/1552-integration-with-the-display-url-api-plugin-jenkinsintegration

Closing per process
