### ISSUE TITLE
Improve infrastructure-as-code documentation

### ISSUE THREAD

**Issue by jedateach** [openshift/jenkins#575]
Infrastructure as code is a good devops practice to follow, but it's not particularly clear how to do this well with Jenkins.

The ability to configure Jenkins on container start via `configuration/init.groovy.d` appears to be the way to do this with the OpenShift containers.

The Groovy Jenkins API and Groovy language itself isn't well documented to aid developers in achieving a IAC setup.

I'd love to see:

- Tutorials
- Best practices around writing modular code for Jenkins setup
- Keeping secrets / env vars out of the config (plus where it should be)

It would be great if RedHat could throw some resources at improving this part of the Jenkins ecosystem.

Have I understood the current state of play correctly? Is this the right place to be brining this up?

**Comment by psiroky** [comment]
I believe the best place for this issue/question would be https://github.com/jenkinsci/jenkins. This repository only hosts sources for OpenShift specific Jenkins docker images.

You may also want to take a look at https://github.com/jenkinsci/configuration-as-code-plugin which will basically enable Jenkins configuration via YAML. That plugin is still in heavy development though.

**Comment by gabemontero** [comment]
Yeah, at most, we could provide a pointer to the init.groovy.do doc as part of our image extension overview, and if we find overall doc in upstream jenkinsic that assists running in containers/k8s/openshift.

We can use this issue to drive the init.groovy.d link

But work coming out of this repo isn't going to drive improvements in what upstream jenkinsci is doing.

@sspeiche @bparees fyi ^^

**Comment by jedateach** [comment]
Thanks folks - I think this is what I was looking for: https://github.com/jenkinsci/jep/tree/master/jep/201
