### ISSUE TITLE
nodejs 6 slave

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/jenkins#595]
I am trying to create a nodejs 6 slave. We are currently using Openshift 3.7. Is there some documentation to follow on updating slaves?

**Comment by gabemontero** [comment]
Hey @Gl4di4torRr 

Other than the contents of the repo's readme, and using the agent-* and slave-* directories as reference, there is no other documentation.

Certainly if you end up taking on this exercise, you can post specific questions here as they arise.  And we would be amenable to including any write up or notes you compile as part of that exercise as some form of how-to or cheat sheet.

Thanks.
