### ISSUE TITLE
mvn command not found in jenkins-slave-maven

### ISSUE THREAD

**Issue by MarWestermann** [openshift/jenkins#596]
Hi,
I have a problem running my jenkinsfile.

Environment:
minishift / openshift 3.9 on linux mint
deployed the jenkins container from the default template
logged in to jenkins and added new pipeline which points to my git url 
My git repo contains the following pipeline:

```
node('maven') {
    stage('Build') {
        container('jnlp') {
            echo 'Building..'
            sh 'mvn clean compile vertx:package fabric8:build fabric8:resource -pl bundle-registry-service -Popenshift'
        }
    }
}
```

result:

```
[qbus2-core_jenkins-IYIYBPCPUMWLQXTDVZYDX25KPV6OJPLOWT4B3HPDWKIK6JB6U5EA] Running shell script

+ mvn clean compile vertx:package fabric8:build fabric8:resource -pl bundle-registry-service -Popenshift

/tmp/workspace/qbus2-core_jenkins-IYIYBPCPUMWLQXTDVZYDX25KPV6OJPLOWT4B3HPDWKIK6JB6U5EA@tmp/durable-ba9f7f28/script.sh: line 2: mvn: command not found

script returned exit code 127
```

Jenkins itself has configured a kubernetes pod template named maven and the container template jnlp within uses the docker image docker.io/openshift/jenkins-slave-maven-centos7:v3.9

when I enter the maven-XXXX container shell while it is running I can successfully run mvn -version command, so I dont understand what the issue actually is.

**Comment by bparees** [comment]
please see the feedback in https://github.com/openshift/jenkins/issues/582
