### ISSUE TITLE
Use nvm to manage node versions in containers

### ISSUE THREAD

**Issue by springdo** [openshift/jenkins#598]
This is more of a suggestion than an issue; but keeping up with node releases and the versions that people want to use on projects can be a bit of a pain. As a suggestion; what do people thing about using [nvm](https://github.com/creationix/nvm) to install and manage node versions in the Jenkins slaves? 
We could then install v4, v6, v8 (and any other version really!) into the image and when a person runs their npm build in Jenkins; they can just set `nvm use v4` and away they go?

**Comment by gabemontero** [comment]
Hey @springdo 

Interesting idea, I would like to go this way.

Unfortunately, we cannot include binaries that are not packaged in rpm's and installable via yum/dnf on centos7 and rhel7.

Looking at link you provided, along with trying to install locally and searching a bit, I was unable to find rpms.

Certainly, if I have overlooked something and you can point me to a repo, let me know.

thanks

**Comment by springdo** [comment]
Yeah I think the nvm script uses the prebuilt binaries made specific for the os distro. Perhaps there is a way we achieve the same goal (multiple node versions just by selecting the one you want to use at execution) with the scl node versions in the existing slaves? Do you think its worth me lookin into this?

**Comment by bparees** [comment]
A single image w/ multiple SCL versions of nodejs installed seems plausible but it has not been the direction we've gone so far out of a desire to:

1) keep the images slightly smaller
2) avoid the issue that occurs when a particular version goes EOL:  if we have a single image w/ multiple versions, and then one version goes EOL, we have no choice but to publish a new version of the image that no longer includes the EOL version.  That would negatively affect anyone still trying to use the EOL version.  By having an image for each version, we can simply stop updating the image w/ the EOL version, while continuing to update the other images.  So it provides better granularity.

So i think it might be a reasonable thing to look into for your own agent image if you want to create one, but i don't think it's a pattern we'd adopt for the image we distribute.
