### ISSUE TITLE
clone private git repository in podTemplate

### ISSUE THREAD

**Issue by MarWestermann** [openshift/jenkins#601]
Hi I use default jenkins on minishift 3.9 and try to build a vertx project.
Therefor I added Jenkinsfile to my project and added a pipeline in jenkins. The source code can be checked out successfully so the Jenkinsfile is read and the pipeline is started.

But when I understood correctly I have to specify the git url again in the podTemplate as the checked out source code from jenkins is not provided to the pod?!

But in the pod the checkout fails with error.

My pipeline:

```
def label = "mypod-${UUID.randomUUID().toString()}"
podTemplate(label: label, cloud: 'openshift', containers: [
    containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat'),
  ]) {

    node(label) {
        stage('Checkout git project') {
            git url: 'git@XXXXXX.de:microservices/myproject-core.git', credentialsId: 'gitlab-credentials'

            container('maven') {
                stage('Build') {
                    echo 'Building..'
                    sh 'mvn clean compile'
                }
            }
         }
    }
}
```

Here are the logs from pipline execution:
https://pastebin.com/wP7RfpnC

Regards, Marco

**Comment by bparees** [comment]
@gabemontero looks like we aren't setting up /etc/passwd correctly in the slave startup to ensure the random uid is present there?

@MarWestermann you should be able to work around this by setting GIT_COMMITTER_NAME and GIT_COMITTER_EMAIL environment variables to some values (you can just use "openshift" and "openshift@openshift.com") when invoking git.

**Comment by gabemontero** [comment]
not sure @bparees, I will have to try and repro

I have noticed more recent changes in k8s plugin (i.e. after the 1.2 version we ship) that deal with the OpenShift randon uid.

I found this snippet in a more recent version of PodTemplateBuilder in k8s plugin:

```
        // Running on OpenShift Enterprise, security concerns force use of arbitrary user ID
        // As a result, container is running without a home set for user, resulting into using `/` for some tools,
        // and `?` for java build tools. So we force HOME to a safe location.
        env.put("HOME", workingDir);
```

**Comment by gabemontero** [comment]
We do have a pipeline in our regression test suite that does this:

```
                node("maven") {
                  stage("Checkout") {
                    git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}"
                  }
                  stage("Build WAR") {
                    sh "mvn clean package -Popenshift"
                    stash name:"war", includes:"target/ROOT.war"
                  }
                }
```

So part of me wonders if there is some friction point between the git plugins, the credential plugins, and slave images, and the user ID complaint in the pastebin.

Though a question to @MarWestermann - the `maven:3.3.9-jdk-8-alpine` image ... how was it built exactly?  Based on the name, I am assuming it is not the maven image we ship by default.

Otherwise, the only diff of note I see between our test and @MarWestermann 's example is the explicit use of a credential.

Working on my local repro now.

**Comment by gabemontero** [comment]
Yep, this works for me, even with v1.2 of the k8s plugin:

```
                node("maven") {
                  stage("Checkout") {
                    git url: "https://github.com/openshift/openshift-jee-sample.git", branch: "master", credentialsId: "ggmcreds"
                  }
                  stage("Build WAR") {
                    sh "mvn clean package -Popenshift"
                    stash name:"war", includes:"target/ROOT.war"
                  }
                }
```

Including this snippet where it is using the credential I supplied via the `credentialsId`:

```
Cloning repository https://github.com/openshift/openshift-jee-sample.git
 > git init /tmp/workspace/asdf # timeout=10
Fetching upstream changes from https://github.com/openshift/openshift-jee-sample.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/openshift/openshift-jee-sample.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/openshift/openshift-jee-sample.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/openshift/openshift-jee-sample.git # timeout=10
Fetching upstream changes from https://github.com/openshift/openshift-jee-sample.git
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/openshift/openshift-jee-sample.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 3ed799911cf2d7dd93086aaa6f394d6da5ceb0fd (refs/remotes/origin/master)

```

If I remove `credentialsId`, I dont' see the `GIT_ASKPASS` related items.

So, @MarWestermann - we need to understand the details of the `maven:3.3.9-jdk-8-alpine` image you are using.  Possibly its passwd file is not set up like it is in the maven agent/slave images we ship by default.

**Comment by bparees** [comment]
yeah sorry I wasn't paying attention that @MarWestermann wasn't using our slave image.

this is purely an issue w/ how that image starts up, it either needs to setup /etc/passwd like our images images do, or the env vars i specified earlier need to be set prior to invoking git.

**Comment by bparees** [comment]
@MarWestermann kubernetes does not run images using a random uid by default, as openshift does, that is likely why you are facing the issue when running on openshift and need to take one of the actions I suggested above.

**Comment by gabemontero** [comment]
Ah, ok.  Yes, unfortunately then, we have little control over the construction of that images, an it is without question missing the requirement @bparees noted in https://github.com/openshift/jenkins/issues/601#issuecomment-388890196 and the k8s plugin is also aware of as I noted in https://github.com/openshift/jenkins/issues/601#issuecomment-388865369 to run on OpenShift.

Your options are to try 
1) build an extension of that image that calls logic like https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/generate_container_user during its startup, like at https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L18
2) use the maven slave images produced from this repo, and similarly extend them as needed to add whatever is in the image you noted that they do not container

**Comment by bparees** [comment]
or (3), set the GIT env variables I mentioned which will keep git from trying to look up the current user.

**Comment by MarWestermann** [comment]
OK thank you very much for your help.. I start to get a better understanding of the system
