### ISSUE TITLE
Add ssh-agent plugin to base-plugins.txt

### ISSUE THREAD

**Issue by iyurinok** [openshift/jenkins#613]
https://jenkins.io/doc/pipeline/steps/ssh-agent/

base-plugins.txt
```
ssh-agent:1.15
```

**Comment by Gl4di4torRr** [comment]
@iyurinok j/w what is your use case? are you connecting to VMs outside of openshift?

**Comment by iyurinok** [comment]
@Gl4di4torRr I need it to provide git ssh credentials from jenkins pipeline to create tags.

Found solution here:
https://github.com/jenkinsci/pipeline-examples/blob/master/pipeline-examples/push-git-repo/pushGitRepo.groovy

**Comment by Gl4di4torRr** [comment]
@iyurinok i opened https://github.com/openshift/jenkins/pull/617

**Comment by bparees** [comment]
closing per the conclusion reached in https://github.com/openshift/jenkins/pull/617#issuecomment-398141871
