### ISSUE TITLE
Set Jenkins identity in build slaves and master for pushing tags

### ISSUE THREAD

**Issue by springdo** [openshift/jenkins#619]
In a pipeline; I want to be able to push git tags to a repository. When doing this in the npm slaves (and assumedly maven & master too) you get an error that Git doesn't know who you are. As the CI server is a service account and the slave images are ephemeral; it doesn't have a proper `user.name` or `user.email` set causing the tagging to fail builds. I suggest we add some config for Jenkins such as the following

```
# Set Jenkins for git pushing tags etc in pipeline
RUN git config --global user.email "jenkins@my-ci-server.com" && \
    git config --global user.name "jenkins"
```

Open to debate and happy to raise a PR

**Comment by bparees** [comment]
you can also work around this by setting the GIT_COMMITTER_NAME and GIT_COMMITTER_EMAIL env vars.

i'd sort of rather people do this explicitly lest we get questions about where the hardcoded value is coming from, but i'm not 100% against setting a default.

**Comment by Gl4di4torRr** [comment]
@bparees what are you think the default values should be?

**Comment by bparees** [comment]
`openshift@openshift.com` and `openshift` would be my recommendation i guess.
