### ISSUE TITLE
New 3.10 Docker Images now missing from registry/catalog

### ISSUE THREAD

**Issue by sbohan** [openshift/jenkins#620]
Having tried to upgrade the node version manually 4.x->8.x from the previous node slave images v3.9; I found the new 3.10 agents vs. slaves images and tried to use them in my deployed jenkins instances. 

However, it seems the docker images have disappeared from the registry from the links in README in this repo:

https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7
https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7

Gives the following response as of 2am GMT+1 31/05/2018:

![image](https://user-images.githubusercontent.com/5673909/40756415-330ead86-648c-11e8-8a7f-87800047840f.png)

Additionally when trying to retrieve the images via docker they are not found:

`$ docker pull registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7`
`Using default tag: latest
Error response from daemon: error parsing HTTP 404 response body: invalid character 'F' looking for beginning of value: "File not found.\""`

Could anyone explain what is happening here? This will cause a lot of build issues if people relying on these images in pipelines and I would hesitate to leverage them if they randomly go offline.

Thanks,

Shaun

**Comment by bparees** [comment]
They didn't disappear, they were never there. 3.10 hasn't shipped yet.

We publish centos versions in advance but the rhel images won't be published until OCP v3.10 ships.

Apologies for the confusion caused by the readme, we sometimes get ahead of ourselves trying to get things lined up in anticipation of the release. 

/close
