### ISSUE TITLE
How to use root user?

### ISSUE THREAD

**Issue by justintoo** [openshift/jenkins#656]
I'm trying to install additional software with `yum`, but I need `root` access. How do I do this?

```
sh-4.2$ yum install vim
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/Obsoletename'
You need to be root to perform this command.

sh-4.2$ id -a
uid=1001(default) gid=0(root) groups=0(root)
```

**Comment by bparees** [comment]
Depends how you're running the image.

Normally to extend the image in this way you'd write a dockerfile that extends our image, does USER root, then RUN yum install

And then docker build that dockerfile (or use openshift to build it)

**Comment by justintoo** [comment]
Okay, that will work for my purposes. Thank you!
