### ISSUE TITLE
Consider upgrading to the latest versions of declarative pipeline plugins

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#658]
There are some really great improvements in the newer versions of Declarative Pipeline, most notably the ability to restart a pipeline from a particular (top level) stage.

See the changelog on this plugin page for a full list of changes since the most recent version in this image (1.2.5): https://plugins.jenkins.io/pipeline-model-definition

**Comment by gabemontero** [comment]
Thanks for the prompting / pointer @grdryn 

Regression testing of course is the thing here.... especially since we would be pulling in a version of the plugin not pulled in by workflow-aggregator.  And its slew of dependencies.

I've been trying to get a sense on when a new version of workflow-aggregator might be coming out (2.5 is over a year old), but found nothing tangible yet.  You would think they should be doing it sometime in 2018.

How long have you all been running with later versions in your openshift jenkins image extension?

**Comment by grdryn** [comment]
Ah right, I didn't realise that it was through the `workflow-aggregator` that the pipeline plugin versions were decided. I see a PR in the repo for it to update, but even that PR hasn't seen any activity in around 6 months. It'd be good to know what the current status of that plugin is alright.

> How long have you all been running with later versions in your openshift jenkins image extension?

We haven't at all yet. I always come here first! :) I'll see if I can find some time to do something with our one using newer versions.

**Comment by svenstaro** [comment]
Just to note: `workflow-aggregator` can now be updated to version 2.6 but that in turn requires a more recent version of Jenkins.

**Comment by grdryn** [comment]
Ooh, that's interesting, thanks for the heads-up!

The diff of the pom.xml (where the aggregated plugin versions are defined since the previous version can be seen [here](https://github.com/jenkinsci/workflow-aggregator-plugin/compare/workflow-aggregator-2.5...workflow-aggregator-2.6#diff-600376dffeb79835ede4a0b285078036).

**Comment by gabemontero** [comment]
Well according to https://github.com/jenkinsci/workflow-aggregator-plugin/blob/workflow-aggregator-2.6/pom.xml#L65 it requires 2.130 ... of course as you know @grdryn we are at 2.138.2 now :-)

To some degree, I fear what "features" that they have added have broken us, but we can't sit pat forever.

If you have time to submit a PR @grdryn feel free.  We are a bit swamped here but if you do not do it I'll get to it at some point this month.

**Comment by grdryn** [comment]
I'll see if I can find time to upgrade our downstream image to it, and play around with that for a while. If I don't see any issues, I'll submit a PR here. :+1:
