### ISSUE TITLE
Add support of  HTTP_PROXY_HOST  to the maven agent image

### ISSUE THREAD

**Issue by akram** [openshift/jenkins#659]
Do the same to  #264 but for proxies.

The following variables have to be managed

HTTP_PROXY_HOST and $HTTP_PROXY_PORT environment variables. Optionally, you can also set the $HTTP_PROXY_USERNAME, HTTP_PROXY_PASSWORD, and HTTP_PROXY_NONPROXYHOSTS variables.

**Comment by akram** [comment]
should be fixed by #660

**Comment by bparees** [comment]
reverted https://github.com/openshift/jenkins/pull/660 to further discuss the proxy var we want to use.

**Comment by gabemontero** [comment]
See https://github.com/openshift/jenkins/pull/660#issuecomment-416244946 for @bparees 's latest analysis wrt copying what was done with the s2i wildfly image here

**Comment by akram** [comment]
closed in favour of #949

/close
