### ISSUE TITLE
FYI: jdk-tool has been split out into a plugin (since 2.112)

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#676]
I'll be installing this in my image (since I noticed a NoClassDefFoundError from the ssh-slaves plugin for it (I think)). Just mentioning it here so that you're aware in case you need/expect it in your image.

See:
https://issues.jenkins-ci.org/browse/JENKINS-22367
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/split-plugins.txt#L27
https://plugins.jenkins.io/jdk-tool

**Comment by gabemontero** [comment]
thanks for the heads up @grdryn 

for now i'm going to wait until we develop a specific need (we don't install the ssh-slaves currently for example)
