### ISSUE TITLE
Ability to configure Jenkins ( *.xml)  from configmap/secret

### ISSUE THREAD

**Issue by matihost** [openshift/jenkins#683]
Currently 
https://github.com/openshift/jenkins/blob/master/openshift/templates/jenkins-persistent.json#L170
assumes all data is single PV mount point (/var/lib/jenkins)

But there are  some configuration files like config.xml, credentials.xml , scriptApproval.xml etc. which are Jenkins installation specific -  these are typical  configuration fils.

When particular Jenkins instance needs to  be recreated from scratch - there needs to be custom process to populate the PV content with correct Jenkins configuration.

Usually it is custom Jenkins image with  overridden configuration dir  and/or s2i script - but it means it is one image per one Jenkins installation (not 12factor way..)
It requires addtional maintenance etc.

Proposal:
Mount additional configmap/secret with *.xml content  to some place in the Jenkins container upon startup
Before starting Jenkins -  copy these *.xml form configmaps/secret to  /var/lib/jenkins and then start Jenkins

Output:
- Jenkins configuration is separated from Jenkins image and PV
- Still it is possible to edit Jenkins configuration in runtime

**Comment by adambkaplan** [comment]
@gabemontero Any reason why we can't modify the s2i `run` script to copy this kind of data from a separate mount point? Ex: mount to `/opt/jenkins`

**Comment by bparees** [comment]
> @gabemontero Any reason why we can't modify the s2i run script to copy this kind of data from a separate mount point? Ex: mount to /opt/jenkins

would have to be done in a backwards compatible way (check the new location for content first, then fallback to the old location).

> But there are some configuration files like config.xml, credentials.xml , scriptApproval.xml etc. which are Jenkins installation specific - these are typical configuration fils.

Why does each of your jenkins instances not have its own PV?

The whole idea here is that your jenkins image contains the "bootstrapping" config, and then on startup, we copy that bootstrapping config into a PV and from there, you can manage that config via the jenkins console if you want (because the changes will be preserved on the PV and on restart, we will use the data from the PV).

If the existing bootstrapping config doesn't work for you, the intent is for you to extend our jenkins image, applying your generic/global/bootstrapping config into the image.  That is why it is an s2i builder that can consume config files.

**Comment by gabemontero** [comment]
@matihost - @bparees beat me to the punch and articulated our strategy/recommendations in this space wrt the openshift jenkins image.

Reopen if questions occur when going down the s2i extension path.

**Comment by matihost** [comment]
> Why does each of your jenkins instances not have its own PV?

Yes they have, but even with ephemeral case it has even more sense. Consider a developer willing to recreate non trivial installation, one project with Jenkins scanning buildconfigs from other projects.
In other to setup such config it is needed to manually configure Jenkins sync plugin (aka config.xml part)

>If the existing bootstrapping config doesn't work for you, the intent is for you to extend our jenkins image, applying your generic/global/bootstrapping config into the image. That is why it is an s2i builder that can consume config files.

It is ok if the bootstrap config is exactly the same for every Jenkins installation. It is is ok to put own plugins to the Jenkins.

But there are real life cases:
- different installation on the same cluster (aka to emulate multitenancy)
- different installation in different environments (in dev for CI, in higher envs for CD )
- requirement to recreate Jenkins installation without any human intervention or to replicate in different cluster

Keepeing config in PV is cumbersome. 
How to store that config in git and recreate a cluster  in case PV dies ? or just to replicate in different cluster?

**Comment by Gl4di4torRr** [comment]
@matihost I am doing one Jenkins master per application. Jenkins lives in DVL and promotes the app to stage and production. I would run Jenkins on one openshift cluster and copy images from cluster to cluster in the` Jenkinsfile` using `oc image mirror`.  We are moving away from a centralized Jenkins master. Sounds like you're using one master for multiple apps/buildconfigs. As stated above, you can extend the default Jenkins master and add any additional plugins and config you need.

**Comment by matihost** [comment]
I'm not talking about single Jenkins per cluster - but to have many of them (one per tenant where tenant is a group of ocp projects within same cluster)
Single Jenkins per application (or even OCP project) is at least resource waste for sure. 

And to have many of them and to automatically recreate their config in case PV crash etc. the recommendation is to  build Docker image for Jenkins master per every Jenkins configuration permutation? -  only because one config.xml has 2 lines difference per each permutation?

BTW
Is there a plan to create  k8s operator for Jenkins installation/management/update etc? That would solve every issue and hide whatever PV magic inside.

**Comment by bparees** [comment]
> Is there a plan to create k8s operator for Jenkins installation/management/update etc? That would solve every issue and hide whatever PV magic inside.

not sure why you'd assume it would solve this problem, that would very much depend on the operator implementation and what it chose to manage for you.  Having an operator that replicates all the config options jenkins has would be, frankly, incredibly impractical.

Which gets to my concern with what you're asking for.  You have selected a specific set of config files that, for you, would be better off on separate PVs(or coming from a configmap).  There is no guarantee your set is the same as someone else's set and we don't want to get into the role of trying to sort that out.  We already have some amount(probably too much) of "override" behavior built in to determine what config takes precedence from where, particularly on restarts, but we're pretty much at the limit of what is reasonable to do there imho.

If you have specific config files you'd prefer to load from a separate dir/PV/configmap on every start up, by all means take the jenkins run script and modify/augment it to process the config in the way you prefer for your needs.  Obviously you can already mount additional configmaps into the jenkins pod, so it's just a matter of having the startup script copy that content in.  The best way to do this is probably to write a run script that copies over your additional content, and removes the image content, then invokes the original run script (this way the original run script will not have any content to copy and it won't replace the files you got from the configmap).  But there are definitely other possible approaches.

> And to have many of them and to automatically recreate their config in case PV crash etc. the recommendation is to build Docker image for Jenkins master per every Jenkins configuration permutation? - only because one config.xml has 2 lines difference per each permutation?

This is actually pretty reasonable:
1) if it's really only 2 lines difference, then you're talking about a tiny additional layer on top of a common image, so it's no meaningful increase in storage or pulling the image.  The only pain point would be managing the multiple buildconfigs and recognizing that when the base image changes, those images all need to be rebuilt (which can be easily managed automatically).

2) Immutable images is pretty much the definition of 12-factor.  Keeping state on PVs(let alone multiple PVs) is going to be more problematic than an immutable image that is entirely self-contained and can be spun up anywhere, spawned into multiple instances, restarted, etc.

**Comment by matihost** [comment]
Thanks for detailed answer.
Essentially these two solution were coming to be delivered, both assume overriding run script.

Either way looking forward for whatever operator(s) it seems they will be everywhere soon.
