### ISSUE TITLE
New Jenkins LTS available, version 2.138.1

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#696]
See https://jenkins.io/changelog-stable/ for more info (quite a few changes!).

**Comment by bparees** [comment]
Thanks, we'll look into updating to this in the 4.0 timeframe (3.11 is locked down at this point).

**Comment by bparees** [comment]
tracking this in JIRA: https://jira.coreos.com/browse/DEVEXP-161

**Comment by gabemontero** [comment]
I seem to recall some problems when someone tried running one of our
plugins at 2.138 and I opened a jira to investigate further.

I’ll look for the jira when in front of a computer Friday.

**Comment by bparees** [comment]
> I seem to recall some problems when someone tried running one of our plugins at 2.138 and I opened a jira to investigate further.

good point, i think the k8s plugin had some issues?  hopefully resolved but if not we'll have to chase those upstream in the k8s plugin repo before we'll be able to move up.

**Comment by gabemontero** [comment]
Didn't create an devexp jira for it, but I did open jenkins jira https://issues.jenkins-ci.org/browse/JENKINS-53260

It is still unresolved.

**Comment by bparees** [comment]
thanks @gabemontero
