### ISSUE TITLE
thanks for good docs and images

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/jenkins#703]
@bparees @gabemontero I just wanted to thank you both for the base slave images and good documentation. I've been working on creating an image today and all your work has really helped me out. Thanks and have a great weekend! (sorry don't know how else to thank you guys.)

**Comment by gabemontero** [comment]
On Fri, Sep 21, 2018 at 1:29 PM Chris Bolton <notifications@github.com>
wrote:

> @bparees <https://github.com/bparees> @gabemontero
> <https://github.com/gabemontero> I just wanted to thank you both for the
> base slave images and good documentation. I've been working on creating an
> image today and all your work has really helped me out. Thanks and have a
> great weekend! (sorry don't know how else to thank you guys.)
>
Appreciate it ... glad this stuff is helping you guys out.

**Comment by bparees** [comment]
Same here, thanks @Gl4di4torRr!
