### ISSUE TITLE
Agent Support for newer JDK's

### ISSUE THREAD

**Issue by brix4dayz** [openshift/jenkins#722]
Using https://github.com/jenkinsci/kubernetes-plugin#container-group-support and the https://hub.docker.com/_/maven/ image, we're able to build newer Java apps with a custom agent defined in a configmap very easily. However, it'd be awesome if future OpenShift releases came with Maven agent images for JDK's 9 - 11... is that on the roadmap for you guys?

**Comment by gabemontero** [comment]
Not at this time @brix4dayz ... looked at you git profile, reminded myself you are at bandwidth

You all at bandwidth should file an RFE if this is important to you.

@sspeiche - fyi

**Comment by andyfeller** [comment]
@gabemontero : just to confirm the expectation is that Redhat is [supporting OpenJDK 8 until 2023](https://access.redhat.com/articles/1299013) including the OpenShift Docker images here, yes?

**Comment by fschmager** [comment]
I can understand if would want to skip 9 and 10, but you gotta consider doing 11. Pretty much everyone was waiting for 11 because long term support and all that jazz. Just outright rejecting supporting anything newer than 8 doesn't sound right to me.
Don't get me wrong. I appreciate this project existing and all the work you put into supporting it, but please reconsider your stance on "never anything newer".

**Comment by mguillem** [comment]
The slave-base image is not optimal as base image for a slave image using an other JDK as the "multi-arch check" in `slave-base/contrib/bin/run-jnlp-client` calls `alternatives` and may change the configured JDK. Personally I've just installed JDK11 on top of the base image and removed the problematic part of `run-jnlp-client` (https://github.com/mguillem/openshift-jenkins-maven-slave/) but it is still not optimal as JDK8 is still contained in the image.
If there is interest, I can prepare a pull request here to provide a cleaner maven slave based on OpenJDK11.

**Comment by bparees** [comment]
> The slave-base image is not optimal as base image for a slave image using an other JDK as the "multi-arch check" in slave-base/contrib/bin/run-jnlp-client calls alternatives and may change the configured JDK. Personally I've just installed JDK11 on top of the base image and removed the problematic part of run-jnlp-client

Someone with that concern can set the jvm arch env variable as part of their extending of the image to force the arch they want...

Anyway we are likely going to be removing the 32/64bit split soon and just always running 64bit.

> If there is interest, I can prepare a pull request here to provide a cleaner maven slave based on OpenJDK11.

Our challenge with this is how to provide it w/o breaking people on jdk8.  It really needs to be made available as a new image/repository (vs just being a new version of the existing image).  We're having similar discussions/debates w/ respect to the nodejs agent.  I would like to see us move away from providing configuration in the jenkins master that points to specific agent images, and instead move to a model where there is just a catalog of agent images (published by various people) that the jenkins master can be configured(by the end user) to use.

To that end, I think a great starting point would be to publish your jdk11 based agent images and submit a PR to the readme here referencing them.

**Comment by andyfeller** [comment]
This appears to have been done as part of https://github.com/openshift/jenkins/pull/913 for upgrading the sync plugin.
