### ISSUE TITLE
Sluggish performance with JAVA_GC_OPTS

### ISSUE THREAD

**Issue by major** [openshift/jenkins#723]
I'm running the Jenkins 2 server container in OpenShift 3.9. I was seeing very slow responses via the Jenkins web UI at various times during the day. Sometimes the response was so slow that OpenShift gave me 502 timeouts trying to reach the web UI or API. Jenkins also had some large CPU spikes at times where it wasn't doing anything.

I deployed Jenkins in another OpenShift 3.6 environment and saw the same sluggish performance there as well.

My Jenkins deployment has 2 CPUs and 4Gi of RAM allocated to it. As an experiment, I removed all of the default options provided in `$JAVA_GC_OPTS`. The idle memory usage has increased (from around 200-300MB to 500-700MB) but the responsiveness of Jenkins has increased drastically. The API and web UI are incredibly responsive and I've not noticed any timeouts even after sending through quite a few jobs.

I also tried using the default `$JAVA_GC_OPTS` along with `$CONTAINER_CORE_LIMIT` set to `2`, but I saw the same sluggish performance and UI/API timeouts.

I'm not sure if the default garbage collection options should be updated or if I will see horrible problems down the road if I leave them commented out. :)

**Comment by bparees** [comment]
There's unlikely to be any perfect GC options that apply across the board.  We've done our best w/ the experimenting we've done and involvement w/ our JVM experts, but beyond that it's tunable for a reason.  Your experience will vary with the nature of the jobs you're running, plugins you have installed, heap size available to the JVM, etc, there just isn't a one-size-fits-all GC options setting.

I don't think we're likely to change anything here.

**Comment by major** [comment]
@bparees Thanks for the quick reply, though. :)
