### ISSUE TITLE
Feature request - helm support

### ISSUE THREAD

**Issue by magick93** [openshift/jenkins#733]
# User Story

> As a PaaS admin (release manager etc) I would like to be able to build and deploy using jenkins pipelines. In particular, I would like to be able to deploy into a K8s cluster using the defacto package manager, Helm

Hopefully the above is explanatory enough. 

Basically, it would be nice to be able to call Helm from a pipeline.

**Comment by bparees** [comment]
Sorry, this is not a feature we would implement..  the images are easily extensible so if you'd like to add the helm binary(or some other specific client tool) to the jenkins master or agent image so you can invoke it from a pipeline, you can do so, but we are going to draw the line at adding (and then being obligated to support/maintain/update) a large(and ever growing) set of specific client tools to meet each end user's potential use case.
