### ISSUE TITLE
Would the custom-war-packager be useful here?

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins#735]
I've been reading a bit about the custom-war-packager project:

https://github.com/jenkinsci/custom-war-packager
https://jenkins.io/blog/2018/10/16/custom-war-packager/

It sounds like it would make Jenkins startup a lot faster by baking the desired plugins (and config?) directly into the war file ready to go, and is one of the things that enables the "Serverless Jenkins" initiative.

I haven't really thought about how it might fit into this project (maybe it wouldn't at all), and I might be misunderstanding or overstating the usefulness of it, but I thought I'd highlight it anyway since it sounds useful for a containerized/cloud Jenkins.

**Comment by gabemontero** [comment]
Yeah it could.

We are generally in monitoring mode wrt jenkins x / serverless jenkins / cloud native jenkins.  So far, we like the general direction, but are waiting this time for things to harden / mature a bit more.  We'll also most likely have to cross reference / defer to the devtools team at red hat wrt all this as well.  There is an effort for them to take more ownership in this space.

We'll leave this item open for now to remind us of this element of this as things move forward.

**Comment by gabemontero** [comment]
@sspeiche @nstielau @bparees fyi ... an interesting idea from one of our internal red hat consumers (@grdryn ) ... I would imagine this element is on the devtools radar, but let's be sure to include it on the list for any upcoming discussions.

**Comment by gabemontero** [comment]
FYI ... this would also require rework of not just this repo, but how we build this repo's images in osbs/brew
