### ISSUE TITLE
Merge back plugin versions from master into respective branches and make releases

### ISSUE THREAD

**Issue by svenstaro** [openshift/jenkins#769]
The base-plugins.txt has been updated quite a bit on master but those changes haven't been merged back to the respective branches. I think it would be useful if you merged them back into those branches and released new images to dockerhub. At least for us this would ease the process a bit.

**Comment by bparees** [comment]
We do not have the capacity to release older versions of images w/ updated versions of the plugins (primarily the regression testing required).  Short of bug fixes or CVEs, the plugin versions that those images shipped with, is the version they will stay at.  (Users are of course free to update the plugins within the image, in the same way they can add additional plugins).

**Comment by svenstaro** [comment]
Alright, but can we at least expect an updated version for OpenShift 4.0 once it comes out or is that branch fixed as well?

**Comment by bparees** [comment]
the openshift4 image will be based on what is currently the master branch of this repo.

**Comment by svenstaro** [comment]
Ok thanks.
