### ISSUE TITLE
Add the master url config to global Jenkins configs

### ISSUE THREAD

**Issue by siamaksade** [openshift/jenkins#78]
OpenShift mater url should be configurable in global Jenkins configs and one chosen as "default". Buildsteps should be set to the one chosen as "default" and show a dropdown list for picking the master url. Text field in each buildstep means a change in the url requires every buildstep to be manually updated by the user.

**Comment by gabemontero** [comment]
@siamaksade - I couldn't tell for sure if you were aware of this, so just in case, I'll mention that with the existing code you can create a global property today, put the name of that property as the setting for any of the configurable text fields of any of the build steps, and the plugin will substitute the value of the global property for the build step text field when running the job.

That said, I'll look into the jenkins jelly taglibs for drop downs (a quick skim turned up at least 3 of them) and see if there is one that works good for this scenario.

**Comment by gabemontero** [comment]
An update:  after some investigation of the jenkins jelly taglibs, I wasn't enamored with the usability of the non-deprecated options out there (most notably the combobox and select).  Got a second opinion from @bparees and he agreed.

We decided on a slightly different approach, but one which we think captures the desire of this item.  Also, this new approach dovetails with a separate discussion we had today with @mfojtik regarding picking up of the namespace / project name setting.

I've got a commit in hand for the plugin ready to push (the changes hence are technically for the jenkins-plugin repo, not the jenkins repo ... @bparees - at least with my level of authority, but perhaps even in general, I don't see how to move this issue over to that repo).

However, aside from giving @siamaksade a chance to comment, there is one detail (a potential change to the jenkins repo) I still want to confirm with @mfojtik (if he consented on IRC, I missed it).

Preamble over.  Details:
1) API URL and namespace params are still text fields, but no longer have default values (several other fields in fact will be losing defaults)
2) if not set, the plugin will pull the values for the namespace from the PROJECT_NAME env var now set by the jenkins image (@mfojtik - perhaps we should change this to OPENSHIFT_PROJECT_NAME), and for the api url from the KUBERNETES_SERVICE_HOST env var now set by the jenkins image.
3) the customer can still use the jenkins global key/value params, or the job level build parameter key/value params, as I mentioned in my last comment
4) or they can override with the actual value

**Comment by bparees** [comment]
Sounds good to me, with one minor note:
KUBERNETES_SERVICE_HOST is actually set by openshift/k8s (which is good, it means that variable won't be set when the image is running outside of openshift/k8s).

@siamaksade please let us know if you think this will address your issue.

**Comment by bparees** [comment]
@gabemontero yeah not aware of any way to move an issue between repos, but you can still reference this issue from your pull in that repo and vice versa.

**Comment by bparees** [comment]
fixed by https://github.com/openshift/jenkins-plugin/pull/22
