### ISSUE TITLE
Broken login with 2.150.2 update

### ISSUE THREAD

**Issue by isouza-daitan** [openshift/jenkins#786]
It appears the upgrade to 2.150.2 on https://github.com/openshift/jenkins/pull/783 has broken the login integration for us. We use the [role to jenkins permission](https://github.com/openshift/jenkins-openshift-login-plugin/#openshift-role-to-jenkins-permission-mapping) feature, which may be relevant in this case.

I have a build with 2.138.4 (before the v3.11 tag was updated) that works correctly (i.e. I'm able to login) and a build with 2.150.2 (after the v3.11 tag was updated) that I'm unable to login.

The logs are apparently the same with both versions.

**Comment by isouza-daitan** [comment]
Could be related to these: https://issues.jenkins-ci.org/browse/JENKINS-55669 https://issues.jenkins-ci.org/browse/JENKINS-55668

**Comment by isouza-daitan** [comment]
Also: https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+the+SECURITY-901+fix

**Comment by svenstaro** [comment]
Yes, we're getting the same thing. I suppose openshift-login has to be patched and a new version of this image with the fix has to be pushed. 

Frankly we depend a lot on Jenkins for OpenShift and would expect the QA for this image to be more thorough. Something as basic as the login has to work.

**Comment by arnaud-deprez** [comment]
I'm wondering if I have the same behaviour than you.

So basically, when I try to access jenkins: 

1. It gives the login page from openshift login plugin.
1. When I click on `Log in with Openshift`, it forwards me to the `Openshift Login page`.
1. Then I use my login/password and click on `Log in`
1. And finally redirected again to the login page from openshift login plugin resulting in an infinite loop.

This fully reproducible on `Minishift` with latest `Openshift v3.11` and when using the `Jenkins ephemeral template`

**Comment by isouza-daitan** [comment]
@arnaud-deprez that is the same behavior I'm experiencing.

**Comment by bparees** [comment]
> Frankly we depend a lot on Jenkins for OpenShift and would expect the QA for this image to be more thorough. Something as basic as the login has to work.

@svenstaro We appreciate your patience and apologize for the issues you've run into.

That said, we are currently undergoing a lot of churn between:

1) openshift 3 vs 4 api changes (and trying to support both versions in the login plugin)
2) our CI infrastructure being significantly refactored
3) updating jenkins itself to new LTSes which can change how plugins work

So we test as best we can given time+resource constraints, and the basic scenarios do work for our testing, however there are subtleties in environments, differences between web console + curl driven flows, etc.  

If you are interested in something with a higher level of quality assurance, the option exists to get an openshift subscription and use the officially supported product(which includes a rhel version of this jenkins image).  Those images go through a deeper level of QE prior to release as we have resources there that aren't available to support the community images.

**Comment by isouza-daitan** [comment]
For people looking for a workaround, you can use an older version of v3.11 (with Jenkins 2.138.4) with `openshift/jenkins-2-centos7:v3.11@sha256:d12d90a2a2e2590f05d3ef86ce1315bbc7b2fc74270e241b9a2b9f434623cf66`

**Comment by szEvEz** [comment]
I stumbled upon the same issue. 

@isouza-daitan That workaround works like a charm. Thanks!

**Comment by gabemontero** [comment]
A preliminary update:  the security advisory changes in 2.150.2 have been confirmed to impact security realm implementations like this plugin.

One of the upstream jenkins security leads recommended changes in https://github.com/jenkinsci/oic-auth-plugin/issues/54#issuecomment-455477406

I'm trying to mimic what was done in https://github.com/jenkinsci/oic-auth-plugin/pull/56/files but have not seen it work seamlessly for us as of yet, but am still debugging.

I will report back when I do.

Also, on testing: our PR testing does curl/bearer token based authentication to validate this plugin (automation of the browser based oauth flow is beyond our capabilities).  The aforementioned security advisory changes did not impact that flow.  As @bparees alluded to, our typical human based verifications follow that automated testing.

**Comment by isouza-daitan** [comment]
@gabemontero thanks for looking into it.

I would like to suggest releasing immutable tags with a major.minor.micro version number in addition to the current moving major.minor tag. I believe it wouldn't add much overhead to your process. A changelog would also be great.

**Comment by bparees** [comment]
> I would like to suggest releasing immutable tags with a major.minor.micro version number in addition to the current moving major.minor tag. I

Starting with v4 the jenkins images are published to quay.io and you can get a full tag history:
https://quay.io/repository/openshift/origin-jenkins?tab=history

Since the images are tied to openshift's release process, we can't control the major/minor/patch version, but you can at least go back in time and get an older image as needed.

Note that imagestreams are also intended as part of the solution to this problem:  you can pin your imagestream to a particular image sha, update it when you want, and rollback to a previous sha as needed.  So if you deploy your jenkins pods using the jenkins imagestream, you should be able to control specifically which image sha you are using.

**Comment by gabemontero** [comment]
v1.0.15 of the login plugin has been initiated with the jenkins update center

when it is available for download from there, we'll initiate new versions of the 3.11 openshift/jenkins images

**Comment by gabemontero** [comment]
https://github.com/openshift/jenkins/pull/788 should initiate the change to update the v3.11 image on docker.io  (though openshift hit some api limits on github today so execution could be delayed)

**Comment by gabemontero** [comment]
The new image is up on docker hub

openshift/jenkins-2-centos7                           v3.11               275373cb8d0e        8 hours ago         1.62GB

and it has 1.0.15 of the login plugin
