### ISSUE TITLE
NPM_MIRROR_URL not working voor nodejs-8 agent

### ISSUE THREAD

**Issue by jr00n** [openshift/jenkins#795]
When NPM_MIRROR_URL  env var is set, the npm registry is not set.
Due to the fact that the script "configure-agent" is nog run when Agent starts.
Dockerfile is missing an COPY entry for this file.
https://github.com/openshift/jenkins/blob/0f169bfb464638d250ba1b09bd9c91813cc9a5bc/agent-nodejs-8/Dockerfile#L12

**Comment by bparees** [comment]
thanks, looks like we need to fix this in the 3.11 branch too
