### ISSUE TITLE
OpenShift 3.11: Build for centos: Base image in Dockerfile must be tagged to v3.11 

### ISSUE THREAD

**Issue by jomeier** [openshift/jenkins#809]
Hi,

```
FROM quay.io/openshift/origin-cli
```
does not work for builds for centos because the latest tag in quay.io is set to version 4.0. 

```
FROM quay.io/openshift/origin-cli:v3.11
```

does work.

Could you change that or mention in the documentation, please?

Best regards,

Josef

**Comment by gabemontero** [comment]
hey @jomeier 

yeah, some big changes are happening as part of v4.0 of openshift 

among other things, the centos/rhel7 distinctions will be going away in large part

we won't be doing what you asked wrt switching to the v3.11, but PR https://github.com/openshift/jenkins/pull/819 includes README updates to start explaining things, as well as what if necessary if you want to build this repo locally (though that will only be supported for local dev now).

**Comment by gabemontero** [comment]
I will be resolving this issue among other things with that PR
