### ISSUE TITLE
how to add the slave in jenkins

### ISSUE THREAD

**Issue by thincal** [openshift/jenkins#82]
After deploying the jenkins in openshift platform, how to add the slave in jenkins ? thanks.

**Comment by bparees** [comment]
@mfojtik is working on a PR that walks through this.  you can see it here:
https://github.com/openshift/origin/pull/7145

**Comment by mfojtik** [comment]
@thincal should be merged today. Also see the official documentation: https://github.com/openshift/openshift-docs/pull/1580/files

**Comment by PI-Victor** [comment]
should this be closed now?
