### ISSUE TITLE
https://jenkins.io/security/advisory/2019-01-08/#SECURITY-1266

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/jenkins#820]
Seems like the `v3.10` tag is affected by this [security advisory](https://jenkins.io/security/advisory/2019-01-08/#SECURITY-1266). 

I can try updating the [plugins](https://github.com/openshift/jenkins/blob/openshift-3.10/2/contrib/openshift/base-plugins.txt) if y'all want me to

**Comment by adambkaplan** [comment]
We don't backport beyond v3.11 - see https://bugzilla.redhat.com/show_bug.cgi?id=1669513#c1

v3.10 clusters can upgrade their Jenkins to run the v3.11 image.

**Comment by gabemontero** [comment]
Our security advisory policy is also documented in this repo’s readme

**Comment by Gl4di4torRr** [comment]
@adambkaplan @gabemontero thanks!
