### ISSUE TITLE
Jenkins error on OpenShift: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied

### ISSUE THREAD

**Issue by pavankjadda** [openshift/jenkins#824]
I have an OpenShift origin (OKD) environment setup on AWS. I am trying to deploy `jenkins-persistent` image to bring up `jenkins` pod in an openshift project. For persistent storage, I am using Persistent Volume and Persistent Volume claims based on [Kubernetes documentation][1]. 

    [root@ip-10-0-0-7 BookStore]# oc get pv
    NAME           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM               STORAGECLASS   REASON    AGE
    jenkins        5Gi        RWO            Retain           Bound     cicd/jenkins        manual                   1h
    jenkins-data   5Gi        RWO            Retain           Bound     cicd/jenkins-data   manual                   3h
    [root@ip-10-0-0-7 BookStore]# oc get pvc
    NAME           STATUS    VOLUME         CAPACITY   ACCESS MODES   STORAGECLASS   AGE
    jenkins        Bound     jenkins        5Gi        RWO            manual         1h
    jenkins-data   Bound     jenkins-data   5Gi        RWO            manual         3h

I gave access permissions based on [OpenShift docs][2]. Now, whenever I try to deploy this image, I see error **Copying Jenkins configuration to /var/lib/jenkins ...
cp: cannot create regular file ‘/var/lib/jenkins/config.xml’: Permission denied**

Error Log:

    OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='512', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i386/jre/bin/java and /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i386/bin/javac
    Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
    mkdir: cannot create directory ‘/var/lib/jenkins/logs’: Permission denied
    /usr/libexec/s2i/run: line 306: /var/lib/jenkins/image-version: Permission denied
    Generating kubernetes-plugin configuration (/opt/openshift/configuration/config.xml.tpl) ...
    Generating administrative monitor configuration (/opt/openshift/configuration/config.xml.tpl) ...
    Generating kubernetes-plugin credentials (/var/lib/jenkins/credentials.xml.tpl) ...
    Copying Jenkins configuration to /var/lib/jenkins ...
    cp: cannot create regular file ‘/var/lib/jenkins/config.xml’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/config.xml.tpl’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/credentials.xml’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/credentials.xml.tpl’: Permission denied
    cp: cannot create directory ‘/var/lib/jenkins/init.groovy.d’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/jenkins.CLI.xml’: Permission denied
    cp: cannot create directory ‘/var/lib/jenkins/jobs’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/org.jenkinsci.main.modules.sshd.SSHD.xml’: Permission denied
    cp: cannot create directory ‘/var/lib/jenkins/users’: Permission denied
    mkdir: cannot create directory ‘/var/lib/jenkins/plugins’: Permission denied
    Copying 104 files to /var/lib/jenkins ...
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    cp: cannot create regular file ‘/var/lib/jenkins/plugins’: Permission denied
    Creating initial Jenkins 'admin' user ...
    ls: cannot access /var/lib/jenkins/users: No such file or directory
    ls: cannot access /var/lib/jenkins/users/: No such file or directory
    sed: can't read /var/lib/jenkins/users//config.xml: No such file or directory
    /usr/libexec/s2i/run: line 23: /var/lib/jenkins/password: Permission denied
    touch: cannot touch ‘/var/lib/jenkins/configured’: Permission denied
    Administrative monitors that contact the update center will remain active
    Migrating slave image configuration to current version tag ...
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    sed: can't read /var/lib/jenkins/config.xml: No such file or directory
    + exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xmx256m -Dfile.encoding=UTF8 -Djavamelody.displayed-counters=log,error -Duser.home=/var/lib/jenkins -Djavamelody.application-name=JENKINS -jar /usr/lib/jenkins/jenkins.war
    Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
    OpenJDK Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
    Running from: /usr/lib/jenkins/jenkins.war
    webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
    Mar 25, 2019 6:04:16 AM org.eclipse.jetty.util.log.Log initialized
    INFO: Logging initialized @971ms to org.eclipse.jetty.util.log.JavaUtilLog
    Mar 25, 2019 6:04:16 AM winstone.Logger logInternal
    INFO: Beginning extraction from war file
    Mar 25, 2019 6:04:16 AM winstone.Logger logInternal
    INFO: Jetty shutdown successfully
    java.io.FileNotFoundException: /var/lib/jenkins/war/META-INF/MANIFEST.MF (No such file or directory)
    	at java.io.FileOutputStream.open0(Native Method)
    	at java.io.FileOutputStream.open(FileOutputStream.java:270)
    	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    	at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:278)
    	at winstone.HostConfiguration.<init>(HostConfiguration.java:81)
    	at winstone.HostGroup.initHost(HostGroup.java:66)
    	at winstone.HostGroup.<init>(HostGroup.java:45)
    	at winstone.Launcher.<init>(Launcher.java:169)
    	at winstone.Launcher.main(Launcher.java:354)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at Main._main(Main.java:344)
    	at Main.main(Main.java:160)
    Mar 25, 2019 6:04:16 AM winstone.Logger logInternal
    SEVERE: Container startup failed
    java.io.FileNotFoundException: /var/lib/jenkins/war/META-INF/MANIFEST.MF (No such file or directory)
    	at java.io.FileOutputStream.open0(Native Method)
    	at java.io.FileOutputStream.open(FileOutputStream.java:270)
    	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    	at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:278)
    	at winstone.HostConfiguration.<init>(HostConfiguration.java:81)
    	at winstone.HostGroup.initHost(HostGroup.java:66)
    	at winstone.HostGroup.<init>(HostGroup.java:45)
    	at winstone.Launcher.<init>(Launcher.java:169)
    	at winstone.Launcher.main(Launcher.java:354)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at Main._main(Main.java:344)
    	at Main.main(Main.java:160)

  [1]: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
  [2]: https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc

**Comment by gabemontero** [comment]
what versions of openshift and the openshift/jenkins image are you using @pavankjadda ?

**Comment by pavankjadda** [comment]
I am using latest version from OKD cluster. It uses OpenSHift version 3.11

**Comment by gabemontero** [comment]
I just brought up a brand new 3.11 OKD cluster via `oc cluster up` using the 3.11 `oc` you can download from https://github.com/openshift/origin and my provisioning of the `jenkins-persistent` template worked just fine.  None of the errors you noted.

Something is wrong with your setup.

As a point of reference for you, my successful install was with
- `docker.io/openshift/jenkins-2-centos7@sha256:bafd84a63a6474e820e73c1dcd81da9c2c494e806199c081b4ccb1a2ab7968e8` is the precise image produced from this repository that was downloaded from docker.io
- the pvc that was created:
```
oc describe pvc jenkins
Name:          jenkins
Namespace:     myproject
StorageClass:  
Status:        Bound
Volume:        pv0090
Labels:        app=jenkins-persistent
               template=jenkins-persistent-template
Annotations:   openshift.io/generated-by: OpenShiftNewApp
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO,ROX,RWX
Events:        <none>
Mounted By:    jenkins-1-xxpbp
gmontero ~/Downloads/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit $ 
```

If you can provide the analogous pieces of information from your attempt, we can see if there is some obvious difference.  Providing the details on the PV associated with your PVC could also help (i.e. `oc describe pv <pv name>`

**Comment by gabemontero** [comment]
I've also gone through restart scenarios with the jenkins pod, and seen it pick up the pvc/pv from prior runs and maintain the set of config, plugins, etc.

**Comment by pavankjadda** [comment]
Never mind. This issue is related to AWS Elastic block permissions. Explained the resolution process in my [GitHub repo](https://github.com/pavankjadda/BookStore/issues/25)

**Comment by fjakop** [comment]
I have the very same issue with NFS mounts, is there a similar solution?

```
$ oc describe pvc jenkins
Name:          jenkins
Namespace:     sandbox
StorageClass:
Status:        Bound
Volume:        nfs-pv0004
Labels:        app=jenkins-persistent
               template=jenkins-persistent-template
               template.openshift.io/template-instance-owner=08f4940b-c348-11e9-8b7c-005056a24816
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
Events:        <none>

$ oc describe pv nfs-pv0004
Name:            nfs-pv0004
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller=yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:
Status:          Bound
Claim:           sandbox/jenkins
Reclaim Policy:  Retain
Access Modes:    RWO
Capacity:        2Gi
Node Affinity:   <none>
Message:
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    nfsserver
    Path:      /var/nfs/share01/openshift
    ReadOnly:  false
Events:        <none>`
```

**Comment by akram** [comment]
Hi @fjakop 
per history, it looks like it was permission related issue.
With NFS especially, if your Jenkins instance gets deleted and recreated, and you for some reasons get the same PV, you may run into permissions issues, and you will need to run a chown nobody:nobody -R and chmod -R 777  on the PVC .

But this is not related to Jenkins Plugin at all.
