### ISSUE TITLE
About the user for uid 1001

### ISSUE THREAD

**Issue by thincal** [openshift/jenkins#83]
If configuring the ssh key for jenkins container, it will report `No user exists for uid 1001` when running `ssh-keygen`.

some info FYI:

$ echo $USER
```

```

$ echo $UID
```
1001
```

$ id jenkins
```
uid=997(jenkins) gid=995(jenkins) groups=995(jenkins)
```

$ cat /opt/openshift/passwd
```
...
jenkins:x:1001:0:Jenkins Continuous Integration Server:/var/lib/jenkins:/bin/false
```

The problem should be there is no user created for the uid 1001, but it seems that it is trying to create a jenkins user with the uid 1001, right ? but the result shows jenkins user's uid is 997.

**Comment by bparees** [comment]
how are you running the image?

**Comment by thincal** [comment]
Followed the example https://github.com/openshift/origin/tree/master/examples/jenkins by running:
```
oc new-app jenkins-persistent-template.json
```

**Comment by bparees** [comment]
when you run an image in openshift you are actually a random user (run whoami to see it), so the 1001 is irrelevant.

As for how to solve this problem, we'll have to use nss_wrapper to ensure we can always map the current random uid to jenkins for programs that require the current uid be resolvable in /etc/passwd.  This is something we've done in other images.

**Comment by thincal** [comment]
$ whoami
whoami: cannot find name for user ID 1001

**Comment by bparees** [comment]
fundamentally yes that is the issue.  you must have openshift configured with a RunAsAny policy though, since the image is running as 1001 and not a random id.

regardless, the fix is what i described, we need to use nss_wrapper to map whatever uid the container is running as, to the jenkins user.

**Comment by thincal** [comment]
@bparees when will get the fix ? thanks.

**Comment by mfojtik** [comment]
@thincal i'm working on the fix today.

**Comment by mfojtik** [comment]
@thincal @bparees I think the problem is because of `docker exec`. It starts a shell but does not set the NSS_WRAPPER properly.

@thincal how exactly you invoking `docker exec` ? (I think something like: 

```console
$ docker exec 123456 /usr/libexec/s2i/run /bin/bash
```

should work). But I think the better solution would be to move the nss_wrapper into entrypoint wrapper.

**Comment by thincal** [comment]
@mfojtik yes after running as following
```
$ docker exec 123456 /usr/libexec/s2i/run /bin/bash
``
it is working.

**Comment by thincal** [comment]
And when executing the shell script inside the jenkins job, actually the user is set correctly already. So that this will not be a problem, thanks all for your attention and help.

I will close it now, thanks.
