### ISSUE TITLE
Option to specify ScriptApprovals when setting up Jenkins

### ISSUE THREAD

**Issue by kahootali** [openshift/jenkins#836]
There should be an option to specify script approvals when setting up Jenkins

**Comment by gabemontero** [comment]
You can extended the image @kahootali and add an init groovy script to turn this on.

At this point we are no longer adding more explicit environment variables to toggle Jenkins behavior.

Thanks for the interest in the product.

@pradeepto @sthaha @waveywaves fyi

**Comment by kahootali** [comment]
@gabemontero so how do other users do it? Do they manually approve scripts?

**Comment by akram** [comment]
Hi @kahootali and @gabemontero 

What I usually do, is simply override the scriptApproval.xml file using a config map using the following command:

```
oc create configmap jenkins-approval-scripts --from-file=scriptApproval.xml
oc set volume --add dc/jenkins -t configmap --mount-path=/var/lib/jenkins/scriptApproval.xml \
              --sub-path=scriptApproval.xml --configmap-name=jenkins-approval-scripts \
              --name=script-approval
```

You can have a look at this repository for an example of scriptApproval.xml.
https://github.com/akram/openshift-agentless-pipeline

**Comment by ahmedwaleedmalik** [comment]
Hi, are there any other workarounds for this ? Currently, this is acting as a blocker for me as well. Updating the volume doesn't seem like a viable solution.
