### ISSUE TITLE
Use mounted namespace secret for PROJECT_NAME

### ISSUE THREAD

**Issue by mfojtik** [openshift/jenkins#85]
The recent version of k8s (and openshift) has the namespace name mounted in into /var/run/secrets/kubernetes.io/serviceaccount/namespace. We should check if that file exists and use it as the `PROJECT_NAME` by default.. We need to preserve PROJECT_NAME for backward compatibility and to allow people override.

**Comment by PI-Victor** [comment]
close? https://github.com/openshift/jenkins/pull/86/files i'm guessing you fixed it

**Comment by bparees** [comment]
yup
