### ISSUE TITLE
Damaged repomd.xml

### ISSUE THREAD

**Issue by josephmichaelp** [openshift/jenkins#851]
Hello, currently i'm building the rhel7 dockerfile on openshift v3.11.0 by using binary build and everytime i run it this error always shows up=

![Screen Shot 2019-05-14 at 10 53 22](https://user-images.githubusercontent.com/46431222/57669822-d7106c00-7636-11e9-93ab-4483e85843d6.png)

Is there any way to fix this issue? i'm already running the subscription-manager register --auto-attach command but it seems that it didn't fix the issue, any help or feedback would be great. Thanks!

**Comment by gabemontero** [comment]
Can you clarify `using binary build` @josephmichaelp ?

Ideally, provide the precise command you are invoking.

I'm assuming the dockerfile you are referring to is https://github.com/openshift/jenkins/blob/openshift-3.11/2/Dockerfile.rhel7 , correct?

**Comment by josephmichaelp** [comment]
Correct gabe, what i mean about binary build is that i'm building the image in openshift from local Dockerfile files that based on the Dockerfile.rhel7 from the repository by using command like this = `oc start-build <IMAGE NAME> --from-file=/Users/macbook/Documents/Dockerfile` as seen on this documentation > https://docs.openshift.com/online/dev_guide/builds/build_inputs.html#binary-source

The repo problem was solved but now it shows this error =
![Screen Shot 2019-05-15 at 09 29 59](https://user-images.githubusercontent.com/46431222/57744615-24064800-76f4-11e9-888f-7fafeb0b90b9.png)

Is there any way to reproduce this issue or maybe change the code in repository?

**Comment by josephmichaelp** [comment]
Issues solved, thanks!
