### ISSUE TITLE
Jenkins agent has quite old git version of git

### ISSUE THREAD

**Issue by csviri** [openshift/jenkins#875]
Hi,
currently we are using jenkins agent image version: jenkins-slave-base-rhel7:v3.11 
this has git version: 1.8.3.1

which is quite old and has known issues with shallow cloning if I'm doint it from a Jenkinsfile.
It would be greate that in the future the agent comes with a more recent git version.

thank you.

**Comment by akram** [comment]
Hi @csviri 

the current image version is based on rhel7 which supports  git version 1.8.3.1 .
I still don't have the plans for images based on rhel8. But, rhel 8 comes with git version 2.18.1 .

So, the best thing would be to wait for this version and use it. Or, maybe extend the Jenkins Image to embed your own version of git.

cc @gabemontero @waveywaves

**Comment by gabemontero** [comment]
@adkram is correct about the `git` version being driven by the centos/rhel versions for all the OpenShift 3.x images that extend the openshift/cli image, not just the images in this repo.

Now, in 4.x, the images are based of the new RH UBI image (you can read all about it on https://access.redhat.com ), but are still on UBI 7 (the container image version of RHEL 7).

There is no officially release schedule for moving the openshift images to UBI 8 at this time, so @akram 's suggestion about extending the image is the only option at this time.

**Comment by csviri** [comment]
yes, so extending it is fine, and fixes the problem. We just wanted to note that this is a quite general problem, so at the end should be fixed globally. 
Thank you for the response.
