### ISSUE TITLE
Run slave in Jenkins pipelines

### ISSUE THREAD

**Issue by josephmichaelp** [openshift/jenkins#889]
I'm sorry for the amateur questions but i'm kinda confused, how to deploy and run the slave dockerfile on Jenkins master pipelines? The thing is i'm building the Jenkins image on Openshift by binary source so i'm not quite sure how to do it. Thanks.

**Comment by josephmichaelp** [comment]
@akram Hey thank you for the response sorry i'm late. Basically i'm already done the things you said and already build the dockerfile but i was wondering, how to make the slaves that's been build in the openshift cluster integrates with jenkinsfile for jenkins pipeline? is there any way to trigger the build on the jenkinsfile or am i having wrong perception of it? Thanks.

**Comment by akram** [comment]
@josephmichaelp I suggest you to have a look at the openshift documentation, where we give some details on how to create pipeline that integrates with binary build.

https://docs.openshift.com/container-platform/3.6/dev_guide/dev_tutorials/binary_builds.html#binary-builds-pipeline-binary-artifacts

**Comment by josephmichaelp** [comment]
@akram Thanks appreciate it.
