### ISSUE TITLE
Plugin update on fresh Jenkins deployment on Openshift Online results in broken install

### ISSUE THREAD

**Issue by redtux** [openshift/jenkins#893]
## Reported issue
Restarting a fresh Jenkins instance on Openshift Online after a plugin update results in a broken installation. :disappointed_relieved: 

## How to reproduce
1. Create your instance (in my case with persistent volume)
`oc new-project jenkins-persistent`
`oc new-app jenkins-persistent`
`oc get route`
`oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=<URL>/securityRealm/finishLogin --overwrite`
`oc status`
2. Log in
3. Check warnings (5)
4. Update plugins
5. Restart Jenkins…

* **IMAGE REPOSITORY**
  * `image-registry.openshift-image-registry.svc:5000/jenkins-persistent/jenkins2`
* **PUBLIC IMAGE REPOSITORY**
  * `default-route-openshift-image-registry.apps.us-east-1.online-starter.openshift.com/jenkins-persistent/jenkins2`
* **dockerImageReference**
  * `quay.io/openshift/origin-jenkins@sha256:d9349faa564019921f36ad9fea9fa6483c9cb2ebb6e97957d12ae7f659cafe9f`

## Expected behavior
Jenkins and its plugins should already be up-to-date and/or upgrading the installed plugins (and the Jenkins binary, which I have not tried) should just work. :smiley_cat: 

## Assumed error
I guess there is some permission problem. Probably this is an issue with some plugin needing root permissions, which is not allowed. I checked, and `/var/lib/jenkins/` belongs to the default user and group, so this should be correct. (Otherwise, the Docker container would not start anyway, I guess.)

Here goes the stacktrace from Jenkins:
```
java.lang.NullPointerException
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127)
	at com.google.api.client.auth.oauth2.AuthorizationCodeFlow$Builder.setTransport(AuthorizationCodeFlow.java:537)
	at com.google.api.client.auth.oauth2.AuthorizationCodeFlow$Builder.<init>(AuthorizationCodeFlow.java:486)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.newOAuthSession(OpenShiftOAuth2SecurityRealm.java:945)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm.doCommenceLogin(OpenShiftOAuth2SecurityRealm.java:1165)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:537)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:789)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:221)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.openshift.jenkins.plugins.openshiftlogin.OpenShiftPermissionFilter.doFilter(OpenShiftPermissionFilter.java:247)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by akram** [comment]
Hi @redtux 

can you provide more logs if you have? especially the logs which makes you think about a file permission issue?

**Comment by redtux** [comment]
Hi @akram, thank you for your reply!

This was not more than a blind guess, as I am often having troubles with stuff that wants to run as root. :smiley_cat:

I have been trying almost the same install in OpenShift / OKD on-premise before, and everything was working fine, so probably my guess is completely wrong.

Uploading the full log here did not work, so I just pasted it [here](https://pastebin.pl/view/edcffb4b).

**Comment by akram** [comment]
Based on these logs, it looks like there is an issue with the JVM keystore. The INFO log message would probably be an ERROR level than info.

```
OpenShift OAuth provider token endpoint failed unexpectedly using the JVMs default keystore
```
Which leads to the NPE a few lines above. The transport for jvmKeystore cannot be determined.
Can you please give more details about the JDK version you are using?

**Comment by waveywaves** [comment]
```
6. INFO: OpenShift OAuth got a SSL error when accessing the issuer's token endpoint when using the SA certificate
```
@redtux  I fyou check the line above in the logs snippet you have sent it seems to be an issue with the route which you have provided to the service account.

Can you help us out with the commands being run below and what behaviour are you trying to get from the same.
```
oc get route
oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=<URL>/securityRealm/finishLogin --overwrite
```

Please do forward your service account and route configuration. 
Using the following commands.

```
oc get route jenkins -o yaml
oc get sa jenkins -o yaml
```

**Comment by waveywaves** [comment]
@redtux Do append "https://" before the route like this 
```
oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1 https://<URL>/securityRealm/finishLogin --overwrite
```
and let us know how it goes. Based on the Stack trace, the nullPointerException is cased on the transportToUse function where is is not finding the transport in the URI, be it HTTP or HTTPS.

**Comment by redtux** [comment]
Thank you for your help! I have been following this mini howto: https://github.com/openshift/origin/tree/master/examples/jenkins – and as reported before updating the plugins and restarting everything worked fine. I just wanted to report this as it could also happen to others. The versions installed should not differ from those in the above Docker image, as I have not done any upgrade.

```
sh-4.2$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

```
sh-4.2$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

```
sh-4.2$ uname -a
Linux jenkins-1-z97j9 4.18.0-80.4.2.el8_0.x86_64 #1 SMP Fri Jun 14 13:20:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

`$ oc get route jenkins -o yaml`
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 4m
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/host.generated: "true"
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  creationTimestamp: 2019-07-21T16:20:18Z
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  name: jenkins
  namespace: jenkins-persistent
  resourceVersion: "3080823"
  selfLink: /apis/route.openshift.io/v1/namespaces/jenkins-persistent/routes/jenkins
  uid: 6e0cfc5c-abd3-11e9-96e9-0a580a8100b5
spec:
  host: jenkins-jenkins-persistent.apps.us-east-1.online-starter.openshift.com
  subdomain: ""
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2019-07-21T16:20:18Z
      status: "True"
      type: Admitted
    host: jenkins-jenkins-persistent.apps.us-east-1.online-starter.openshift.com
    routerCanonicalHostname: apps.us-east-1.online-starter.openshift.com
    routerName: default
    wildcardPolicy: None
```

`$ oc get sa jenkins -o yaml`
```
apiVersion: v1
imagePullSecrets:
- name: jenkins-dockercfg-hcd6s
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
    serviceaccounts.openshift.io/oauth-redirecturi.1: https://jenkins-jenkins-persistent.apps.us-east-1.online-starter.openshift.com/securityRealm/finishLogin
  creationTimestamp: 2019-07-21T16:20:19Z
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  name: jenkins
  namespace: jenkins-persistent
  resourceVersion: "3083744"
  selfLink: /api/v1/namespaces/jenkins-persistent/serviceaccounts/jenkins
  uid: 6e65e546-abd3-11e9-a036-1212969a920a
secrets:
- name: jenkins-dockercfg-hcd6s
- name: jenkins-token-qgnzv
```

I have checked my history now, and I can confirm that I've been using https as described above.

`$ oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=https://jenkins-jenkins-persistent.apps.us-east-1.online-starter.openshift.com/securityRealm/finishLogin --overwrite`

Anyway, I did not know I do not actually need this, and I will now try again with a fresh install without the annotate part as suggested. (Still, the question remains, why it worked fine before restarting… Is this completely unrelated to the plugin upgrade then?)

**Comment by redtux** [comment]
1. Create project
`oc new-project jenkins-test`
2. Create app
`oc new-app jenkins-persistent`
3. Log in [here](https://jenkins-jenkins-test.apps.us-east-1.online-starter.openshift.com)
4. Authorize RO access to `user:info` and `user:check-access` for service account `jenkins`
5. Redirect [here](https://jenkins-jenkins-test.apps.us-east-1.online-starter.openshift.com/securityRealm/finishLogin?code=_X1PZbG23VbvGhzXNQt_Lyi4NaBVEbxqnuW1ydF0YBQ&state=Nzk5MDNhZDMtNWMyYi00)
6. Java stacktrace [here](https://pastebin.pl/view/raw/9f8119be)
7. Finally, [here](https://jenkins-jenkins-test.apps.us-east-1.online-starter.openshift.com/securityRealm/finishLogin) I see the same error as before (after having restarted Jenkins during my first try)
8. `$ oc get route jenkins -o yaml`
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 4m
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/host.generated: "true"
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  creationTimestamp: 2019-07-22T23:17:44Z
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  name: jenkins
  namespace: jenkins-test
  resourceVersion: "4282386"
  selfLink: /apis/route.openshift.io/v1/namespaces/jenkins-test/routes/jenkins
  uid: e9389cec-acd6-11e9-96e9-0a580a8100b5
spec:
  host: jenkins-jenkins-test.apps.us-east-1.online-starter.openshift.com
  subdomain: ""
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2019-07-22T23:17:44Z
      status: "True"
      type: Admitted
    host: jenkins-jenkins-test.apps.us-east-1.online-starter.openshift.com
    routerCanonicalHostname: apps.us-east-1.online-starter.openshift.com
    routerName: default
    wildcardPolicy: None
```

Anybody should be able to reproduce this by registering for a free starter tier of [OpenShift Online](https://manage.openshift.com/register/confirm) (limited to one project).

**Comment by redtux** [comment]
@bparees, are you the mantainer of this Docker image? Do you have a clue what could be wrong here — or at least a hint where to look for possible configuration errors? (The issue is reproducable.)

**Comment by akram** [comment]
Hi @redtux ,
I am currently trying to reproduce it. It was not clear that setting HTTPS did not work for you.
Give me a few minutes.

**Comment by akram** [comment]
@redtux, I followed your instructions and do not reproduce the issue.

Also, if we follow the mini howto that you sent, you should not reference the route in the serviceaccounts.openshift.io/oauth-redirecturi.1 annotation but rather use the service IP and port.

```
 $ oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=http://<jenkins_service_ip:jenkins_service_port>/securityRealm/finishLogin --overwrite

```



However, I followed your example, and it worked anyway: Here is the instance that I use: 
```
https://jenkins-jenkins-persistent.apps.us-east-1.online-starter.openshift.com/securityRealm/commenceLogin
```

**Comment by redtux** [comment]
@akram Thank you, I will try this again and report my results within the next hour. In the second run I have tried without the annotate part. So I might have misunderstood your question. As you were asking what I am intending by this I assumed that this step was not needed. 😃

**Comment by redtux** [comment]
I have now added `serviceaccounts.openshift.io/oauth-redirecturi.1: https://jenkins-jenkins-test.apps.us-east-1.online-starter.openshift.com/securityRealm/finishLogin` to `/api/v1/namespaces/jenkins-test/serviceaccounts/jenkins`, but the problem remains. Am I doing something wrong here?

**Comment by akram** [comment]
Can you try this:

```
oc get svc jenkins # get the IP address and port of the jenkins service
oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=http://<jenkins_service_ip:jenkins_service_port>/securityRealm/finishLogin --overwrite
```

**Comment by bparees** [comment]
> @bparees, are you the mantainer of this Docker image?

not anymore, no..we are working on getting that metadata updated.  You're in good hands w/ @akram

**Comment by redtux** [comment]
@akram: Is this really needed?
`oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=http://<jenkins_service_ip:jenkins_service_port>/securityRealm/finishLogin --overwrite`

I have just tried it out on a private OKD on-premise install with only `oc new-app jenkins-persistent`, and the route has been created automatically and everything works just fine.

**Comment by redtux** [comment]
BTW, here is the requested `sa/jenkins` yaml from the non-working OpenShift Online deployment using the internal IP now (if I correctly understood). The problem persists. But if I was wrong and this is not reproducible, feel free to close this issue, please. I just thought there was something wrong with the Dockerfile, with Jenkins running in OpenShift (which I know normally is behaving fine), or with the howto.

```
apiVersion: v1
imagePullSecrets:
- name: jenkins-dockercfg-rb6sz
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins-test
  selfLink: /api/v1/namespaces/jenkins-test/serviceaccounts/jenkins
  uid: e9906e9d-acd6-11e9-a036-1212969a920a
  resourceVersion: '6997956'
  creationTimestamp: '2019-07-22T23:17:45Z'
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}
    serviceaccounts.openshift.io/oauth-redirecturi.1: 'http://172.30.65.102:80/securityRealm/finishLogin'
secrets:
  - name: jenkins-dockercfg-rb6sz
  - name: jenkins-token-fmkp7
```

**Comment by redtux** [comment]
@akram: I have tried two more times now, both with FQDN & ClusterIP – and always get the same error after updating the plugins and restarting Jenkins. (Have you done the plugin upgrade?) I do see no difference between our settings… :disappointed: (Also on the on-premise install I had problems during plugin upgrade, btw.)

**Comment by akram** [comment]
We will keep your issue open for investigation. I will be off for 4 days

**Comment by waveywaves** [comment]
@redtux Everything should work just fine if you dont follow the step below.
`oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=http://<jenkins_service_ip:jenkins_service_port>/securityRealm/finishLogin --overwrite`

You would only have to perform it when you "do not have a router or your host system does not support nip.io name resolution" as given in [the doc](https://github.com/openshift/origin/tree/master/examples/jenkins) which you followed.

**Comment by waveywaves** [comment]
As for the testing, this behaviour is interesting and we would like to see why this is happening exactly. Till now on @akram s Openshift Online cluster this isn't happening. I will test this out and get back to you. IN the meanwhile can you try running the following command.

`oc annotate sa/jenkins serviceaccounts.openshift.io/oauth-redirecturi.1=https://172.30.65.102:80/securityRealm/finishLogin --overwrite`

**Comment by laasth** [comment]
We are also having this same issue.

Openshift 4.1.13 , and a valid *.apps.ocp.XX.XX certificate.

The first startup after "oc new-app jenkins-persistent", everything work as expected.
If we restart jenkins, it just just prints the 'same' stacktrace as this issue.

`Sep 04, 2019 1:40:22 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
INFO: OpenShift OAuth: provider: OpenShiftProviderInfo: issuer: https://oauth-openshift.apps.ocp.XX.XX auth ep: https://oauth-openshift.apps.ocp.XX.XX/oauth/authorize token ep: https://oauth-openshift.apps.ocp.XX.XX/oauth/token
Sep 04, 2019 1:40:22 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm useProviderOAuthEndpoint
INFO: OpenShift OAuth server is 4.x, specifically OpenShiftVersionInfo: major: 1 minor: 13+ gitVersion: v1.13.4+a8c5f5b
Sep 04, 2019 1:40:22 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm transportToUse
INFO: OpenShift OAuth got a SSL error when accessing the issuer's token endpoint when using the SA certificate
Sep 04, 2019 1:40:22 PM org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm transportToUse
INFO: OpenShift OAuth provider token endpoint failed unexpectedly using the JVMs default keystore`

**Comment by redtux** [comment]
This is why I do not understand how this is not reproducable. I have tried it several times… 😃

**Comment by akram** [comment]
/assign @waveywaves 

@waveywaves can you find some guys from OpenShift Online Team so we can have help to reproduce it properly?

**Comment by waveywaves** [comment]
@akram Working on it.

**Comment by akram** [comment]
@laasth  or @redtux could you please try setting the following annotation instead of the "static" one ?
```
 oc annotate sa jenkins serviceaccounts.openshift.io/oauth-redirectreference.first="{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"jenkins\"}}"
```

**Comment by akram** [comment]
@redtux and @laasth 
I am investigating this with another user who faced this bug. We went able to move a step further by delete the secret for the service account Jenkins, but we then hit another error. Can you try this:
```
oc delete secret jenkins-token-<the-id-of-your-two-tokens>
```

**Comment by akram** [comment]
Hi @redtux and @laasth 

good news: we have a fix in https://github.com/openshift/jenkins-openshift-login-plugin/pull/80

**Comment by redtux** [comment]
Sorry, it seems like I'm late! 😃 Congratulations for fixing the issue! 🎉 Still any testing needed?

**Comment by laasth** [comment]
@akram Hi! I'm a bit late! :D Been away for the last week.
But nice! When\how can i test the fix? 💃

**Comment by akram** [comment]
Hi @laasth and @redtux 

if you could please test the fix that would help indeed. You need do build my branch and upload the openshift-login.hpi to your instance.

If you have access to your Jenkins instance, you can upload the new plugin version using Upload Manager, but if you don't have access to it,  you will need `oc rsh` to fix your running instance.

Build locally and upload to Jenkins pod:
```
git clone https://github.com/akram/jenkins-openshift-login-plugin.git
cd jenkins-openshift-login-plugin
git checkout bz-1750588-fix-only-oauth
mvn clean package
oc cp target/openshift-login.hpi <your_pod>:/tmp
```

By doing this, you have uploaded your plugin in /tmp in your pod. Then, you need to force installation of it:

```
oc rsh <your_pod>
cp /tmp/openshift-login.hpi /var/lib/jenkins/plugins/openshift-login.jpi
cd /var/lib/jenkins/plugins/openshift-login
unzip -o /tmp/openshift-login.hpi  
kill 1
```

This will then restart your Jenkins container with the updated plugin. And you should be able to login to your openshift instance then.
Can you please give it a try ?

If you need help, I am also available on coreos.slack.com

**Comment by akram** [comment]
@laasth or @redtux , did you see my previous comment?

**Comment by laasth** [comment]
@akram,
Yes! I'm on it now. Will replay as soon as I'm done building\testing!

**Comment by laasth** [comment]
@akram, Works like a charm :D Thanks for this! (y)
Then the move from ocp3 to 4 can begin ⭕️

**Comment by akram** [comment]
excellent 👍 
Thanks for your feedback

**Comment by redtux** [comment]
Not here – build failed! :smirk_cat:  Unfortunately, I get the following compilation error:
```
[ERROR] error: java.nio.file.NoSuchFileException: /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/org.kohsuke.stapler.export.ExportedBean
[ERROR] error: java.nio.file.NoSuchFileException: /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/hudson.Extension
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:01 min
[INFO] Finished at: 2019-09-17T13:31:47+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project openshift-login: Compilation failure: Compilation failure:
[ERROR] error: java.nio.file.NoSuchFileException: /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/org.kohsuke.stapler.export.ExportedBean
[ERROR] error: java.nio.file.NoSuchFileException: /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/hudson.Extension
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Regarding the reported file exception:

```
cat /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/org.kohsuke.stapler.export.ExportedBean
org.openshift.jenkins.plugins.openshiftlogin.OpenShiftUserInfo
org.openshift.jenkins.plugins.openshiftlogin.OpenShiftUserInfo$Metadata

cat /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/hudson.Extension
cat: /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/hudson.Extension: No such file or directory

ls -l /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/ 
total 4
-rw-rw-r-- 1 redtux redtux 135 Sep 17 13:31 org.kohsuke.stapler.export.ExportedBean
```

What am I missing?

Regarding the older questions:

```
oc get pods G Running
jenkins-9-fnjs9   1/1       Running   0          4d4h

oc get events
No resources found.

oc describe sa/jenkins
Name:                jenkins
Namespace:           origin-jenkins
Labels:              app=jenkins-persistent
                     template=jenkins-persistent-template
Annotations:         openshift.io/generated-by=OpenShiftNewApp
                     serviceaccounts.openshift.io/oauth-redirectreference.jenkins={"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}
                     serviceaccounts.openshift.io/oauth-redirecturi.1=http://172.30.51.184/securityRealm/finishLogin
Image pull secrets:  jenkins-dockercfg-g5lkd
Mountable secrets:   jenkins-dockercfg-g5lkd
                     jenkins-token-m6mw7
Tokens:              jenkins-token-7wvph
                     jenkins-token-m6mw7
Events:              <none>

oc delete secret jenkins-token-7wvph
secret "jenkins-token-7wvph" deleted

oc delete secret jenkins-token-m6mw7
secret "jenkins-token-m6mw7" deleted
```
NB: As expected, after deleting the tokens, new ones are being created.

**Comment by akram** [comment]
@redtux it looks like you had an issue while compiling? Can you run separately `mvn clean` and `mvn compile` and then `mvn package` to see which one is failing.
Also, we are usually building on Java 8. Can you tell me about your Java version?

**Comment by redtux** [comment]
https://paste.ubuntu.com/p/sWbH3Q4TxX/

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project openshift-login: Compilation failure
[ERROR] error: java.nio.file.NoSuchFileException: /home/redtux/tmp/jenkins-openshift-login-plugin/target/classes/META-INF/annotations/hudson.Extension
```

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)
```

**Comment by akram** [comment]
@redtux  Do you have the possibility of compiling using Java 8 ?

**Comment by redtux** [comment]
Oracle Java 8? :open_mouth: I am afraid not, since the WebUpd8 PPA repository has been closed after Oracle's license change this April. (OpenJDK 12 or 13 would also make sense, right?)

Is there a Docker image? Could not find any.
