### ISSUE TITLE
Request to update documentation for maven slave image regarding MAVEN_MIRROR_URL environment variable

### ISSUE THREAD

**Issue by jijiechen** [openshift/jenkins#900]
From the [source code of bootstrap script](https://github.com/openshift/jenkins/blob/master/agent-maven-3.5/contrib/bin/configure-agent) of the maven slave image, I saw the support of setting a maven repository mirror server URL using `MAVEN_MIRROR_URL` environment variable.

But this is not documented on the [OpenShift documentation website](https://docs.openshift.com/container-platform/3.11/using_images/other_images/jenkins_slaves.html). I just tested it this afternoon, and found it worked like a charm.

Thanks for this wonderful feature.
Can you also update the documentation to add some instructions regarding this feature?

**Comment by waveywaves** [comment]
Hello @jiajliu ,
Glad you liked the feature.

We will update the documentation on this.

/assign @waveywaves

**Comment by ianwilliams1** [comment]
I don't suppose there's a mechanism to separately declare a `MAVEN_PLUGIN_MIRROR_URL` ?
A Maven pom has two artifact resolution sections, one for dependencies and one for plugins. This is explained in [Plugin_Repositories](https://maven.apache.org/pom.html#Plugin_Repositories)

Notwithstanding the "I have yet to hear a convincing argument for doing so", we have this implemented in our Nexus repository. "The pluginRepository elements each specify a remote location of where Maven can find new plugins."

We can't seem to work around this. Should a separate issue be created to implement such?

**Comment by waveywaves** [comment]
@ianwilliams1 Please do open a separate issue for this feature, It would be easier for us to track and work on that way.
