### ISSUE TITLE
Jenkins Agent for nodejs 10

### ISSUE THREAD

**Issue by djbrown** [openshift/jenkins#907]
According to the nodejs [Long Term Support (LTS) schedule](https://nodejs.org/en/about/releases/), maintenance for nodejs 8 will end by the end of this year.
Can we have a nodejs 10 Agent for Jenkins in OpenShift similar to [agent-nodejs-8](https://github.com/openshift/jenkins/tree/master/agent-nodejs-8)?

**Comment by waveywaves** [comment]
The [slave-base](https://github.com/openshift/jenkins/tree/master/slave-base) template can be utilized for creating such agent.
In this case we will work on getting a agent-nodejs-10. Thank you for letting us know about the LTS on nodejs8. We will take this up on priority.

/assign @waveywaves

**Comment by hiredgunhouse** [comment]
Actually can we also get Node 12 agent? 
I don't understand why you did not release Node 10 or 12 agent sooner.

**Comment by hiredgunhouse** [comment]
I'm gonna create a separate issue for that.

**Comment by akram** [comment]
#940

**Comment by waveywaves** [comment]
New agent for 10 has been added
