### ISSUE TITLE
Container image should include Jenkins version as a label

### ISSUE THREAD

**Issue by jlebon** [openshift/jenkins#924]
So that a e.g. `skopeo inspect` is enough to know what the version is.

**Comment by waveywaves** [comment]
Hello @jlebon , 
Thanks for opening this issue. 

This is a good idea. 
/assign waveywaves

**Comment by akram** [comment]
Hi @waveywaves 
as discussed on slack, that's good idea. And we will have a specific label since we didn't find a generic one amongst openshift images.

**Comment by akram** [comment]
This is fixed here https://github.com/openshift/jenkins/pull/925

/close
