### ISSUE TITLE
4.x -- Centos 7 image for openshift/jenkins-agent-maven-35-centos7 not found

### ISSUE THREAD

**Issue by brianotte** [openshift/jenkins#927]
The 4.x -- Centos 7 image for openshift/jenkins-agent-maven-35-centos7 not found.  

https://hub.docker.com/r/openshift/jenkins-agent-maven-35-centos7 indicates the following:

DEPRECATED: this image is now maintained at quay.io/openshift/origin-jenkins-agent-maven

However, those images are all RedHat based.  Do they require a liscence to use? 

We use Centos 7 in Dev / Test labs, as it does not require licensing fees.

Will a 4.x Centos version get released? If so, can the location for those images be relayed?
Are the RedHat images found at quay.io/openshift/origin-jenkins-agent-maven allowed for OpenSource use?

**Comment by akram** [comment]
Hi @brianotte 

the jenkins images are now UBI (Universal Base Image) based. You can still run the Jenkins images (server and agents) on CentOS as you were doing previously.

These questions are adressed in this FAQ: https://developers.redhat.com/articles/ubi-faq/

feel free to close the issue

**Comment by brianotte** [comment]
With UBI images are we free to run these images without licensing concerns?
