### ISSUE TITLE
MAVEN_PLUGIN_MIRROR_URL environment variable addition

### ISSUE THREAD

**Issue by waveywaves** [openshift/jenkins#931]
Based on https://github.com/openshift/jenkins/issues/900#issuecomment-530181698

A Maven pom has two artifact resolution sections, one for dependencies and one for plugins. This is explained in [Plugin_Repositories](https://maven.apache.org/pom.html#Plugin_Repositories)

Notwithstanding the "I have yet to hear a convincing argument for doing so", we have this implemented in our Nexus repository. "The pluginRepository elements each specify a remote location of where Maven can find new plugins."

**Comment by akram** [comment]
@ianwilliams1 and @waveywaves , based on maven documentation the mirrorOf repository features applies both to artifacts and plugins. And, you can have multiple mirrors defined.

If you want to manage your plugin repositories separately, in can also do it in the distributionManagement section of the pom.xml of the project.

That said, I think it is preferable to close this issue unless there are other elements coming from @ianwilliams1 .

**Comment by waveywaves** [comment]
I think we can close this one then
