### ISSUE TITLE
Provide agent with Node.js 12

### ISSUE THREAD

**Issue by hiredgunhouse** [openshift/jenkins#940]
Please provide an agent image with Node.js version 12.

**Comment by akram** [comment]
Hi @hiredgunhouse 

we do not have plan for now to provide an agent for nodejs12 because we want to rely on software for which there is also corporate support.

I will keep the issue open, but we encourage community contributions.

**Comment by djbrown** [comment]
Was this issue resolved in the meantime? https://catalog.redhat.com/software/containers/openshift3/jenkins-agent-nodejs-12-rhel7/5ed780025a1346074ecce6a6

**Comment by akram** [comment]
@djbrown , yes it was, thanks for the reminder
I will close it then
/close
