### ISSUE TITLE
Bump to latest 2.190.1 LTS release

### ISSUE THREAD

**Issue by jlebon** [openshift/jenkins#963]
There's a new LTS out with a bunch of security fixes: https://jenkins.io/changelog-stable/

**Comment by akram** [comment]
Hi @jlebon ,

thank you for reporting this. We have been advised 2 days ago of its availability, and we are cutting a new release for soon.

cc @waveywaves 
cc @sbose78

**Comment by leigh-j** [comment]
2.190.2 is now latest stable

**Comment by akram** [comment]
Hi @leigh-j and @jlebon 
as the changelog is quite heavy for 2.190.x we will wait a few weeks before upgrading to it.
For now, as we are mostly concerned with CVE's , we updated to 2.176.4 which has the same security fixes.

If by any chance you have run 2.190.x with our last versions of plugins please let us know, that would help to tackle issues.

Greetings
Akram

**Comment by svenstaro** [comment]
Isn't this done now with #978?

**Comment by akram** [comment]
yes, it is for the 4.x image.
Backporting for 3.11 is pending.
/close
