### ISSUE TITLE
Jenkins URL configuration broken after upgrading image

### ISSUE THREAD

**Issue by adam-sandor** [openshift/jenkins#969]
After upgrading the Jenkins image we use on our Openshift clusters we are getting two errors on the configuration screen:
* You have data stored in an older format and/or unreadable data.
* Jenkins root URL is empty but is required for the proper operation of many Jenkins features like email notifications, PR status update, and environment variables such as BUILD_URL.

Jenkins versions:
* old image: `openshift3/jenkins-2-rhel7:v3.11.135-2`
* new image: `openshift3/jenkins-2-rhel7:v3.11.146-1`

We are not sure the first error is causing any real problems but the second definitely is.

Additional information:
* This happens with a newly created Jenkins with an empty disk.
* If we open the Jenkins configuration page the `Jenkins URL` is actually filled in under `Jenkins Location`. If we save the configuration now (without editing anything) the second error gets fixed. This is not a workable solution for as we are spinning up new Jenkinses for developers all the time, but it can give a hint on what's wrong
* When the Jenkins starts up there is no `/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml` file on disk. After saving the configuration this file gets created and the second error is fixed.
* The older format data error isn't fixed even after the configuration is saved and the Jenkins restarted.

Any ideas how to fix this problem, or what could be causing it? I'm not sure how this piece of configuration is supposed to be managed in the first place. I only managed to find the `io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getJenkinsURL()` method that reads the path from Openshift, but it doesn't look like it gets used to set the BASE_URL for example. Thanks up front for any help you can provide!

**Comment by akram** [comment]
Hi Adam,

thank you for reporting these 2 issues and providing a workaround. . If the issues are really different, it is better to open 2 different issues for followup.

Regarding the first issue: "You have data stored in an older format and/or unreadable data." , this one can usually be dismissed if Jenkins is working properly, and is generally caused if you disabled a plugin that you were using previously (the data plugin configuration may still be present in config.xml ) .

Regarding the second issue about BUILD_URL, we will work on a fix based on your findings.

**Comment by adam-sandor** [comment]
Thank you for the quick solution! I will look into the "old/unreadable" data problem and possibly create a new issue for it. 
How can I track when this change makes it into a new image released on the Redhat Container Catalog?

**Comment by akram** [comment]
Hi @adam-sandor 
We will release it with OCP 4.3. 
For now, we don’t think that we will backport  this issue to 4.2

4.3 is planned for December

**Comment by adam-sandor** [comment]
I see, we'll have wait for a while to get that (on 3.11 still), but as we have our own workaround now that is not a big problem.
