### ISSUE TITLE
How to pass system properties to Jenkins process

### ISSUE THREAD

**Issue by dokaspar** [openshift/jenkins#999]
Hi,

How can I pass on system properties (e.g., `-Dhudson.model.UpdateCenter.never=true`) to a Jenkins image deployed in Openshift?
https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties

Regards,
Dominik

**Comment by akram** [comment]
Hi @dokaspar 

you can use the JAVA_TOOL_OPTIONS environment variable to do so.
`oc set env JAVA_TOOL_OPTIONS=-Dhudson.model.UpdateCenter.never=true" `
